Review ' Variables' article
javascript-tutorial/it.javascript.info pull request #144
Opened 2020-11-30 20:16 UTC by longo-andrea

2020-12-01 17:09 UTC, mean2me requested changes
Just some few typos.

2020-12-01 17:09 UTC, mean2me commented on 1-js/02-first-steps/04-variables/article.md
> +...O anche con la virgola a su nuova riga:
What did you mean "a su nuova riga"? :)

2020-12-01 17:09 UTC, mean2me commented on 1-js/02-first-steps/04-variables/article.md
> +Possiamo comprendere meglio il concetto di "variabile" se la immaginiamo come una scatola per dati, con appiccicata un etichetta univoca.
Fix: "un etichetta" => "un'etichetta"

2020-12-01 17:09 UTC, mean2me commented on 1-js/02-first-steps/04-variables/article.md
>  Quando dovremmo utilizzare lettere maiuscole per una costante, e quando invece trattarle come normali variabili? Facciamo un pò di chiarezza.
Fix: "un pò" => "un po'"

2020-12-01 17:09 UTC, mean2me commented on 1-js/02-first-steps/04-variables/article.md
> +Una variabile in più va bene, non sono il diavolo.
Proporrei un'espressione più italiana qua: "una variabile in più non è necessariamente un male" o qualcosa del genere... 🤔

2020-12-01 19:57 UTC, longo-andrea commented on 1-js/02-first-steps/04-variables/article.md
> +...O anche con la virgola a su nuova riga:
Ahaha I mean nothing, thanks for have reported :) Now is "su nuova riga", do you think is okay?

2020-12-01 20:03 UTC, longo-andrea commented
/done

2020-12-26 17:25 UTC, pasor1 approved these changes
Mi sembra tutto ok :ok_hand:

2020-12-26 18:26 UTC, merged