Custom errors, extending Error
javascript-tutorial/it.javascript.info pull request #153
Opened 2020-12-28 18:11 UTC by mrkrash

2021-01-05 15:55 UTC, pasor1 requested changes
Qualche piccolo errore da sistemare, grazie del lavoro :+1:

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Poniamo attenzione: alla linea `(1)` richiamiamo il construtto genitore. JavaScript ci richiede di richiamare `super` nel construtto figlio, allora è obbligatorio. Il construtto genitore imposta la p
JavaScript ci richiede di richiamare `super` nel costrutto figlio, ~allora~ quindi  è obbligatorio

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Il blocco `try..catch` nel codice qui sopra gestisce sia il nostro `ValidationError` e l'errore `SyntaxError` incorporato `JSON.parse`.
gestisce sia il nostro `ValidationError` che l'errore

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Poniamo particolare attenzione a come usiamo `instanceof` per verificare errori specifici alla linea `(*)`.
per verificare errori specifici ~alla~ nella linea

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Poniamo particolare attenzione che `this.name` nel construttore `PropertyRequiredError` è di nuovo assegnato manualmente. Questa cosa potrebbe risultare un po noiosa -- assegnare `this.name = <class
Poniamo particolare attenzione +al fatto+ che

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Quindi chiamamola `MyError`.
Quindi ~chiamamola~ chiamiamola

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +  readUser()  // La potenziale fonte dell'errore
La potenziale fonte ~dell'~ di errore

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +    // gestisco l'errore di validazione
gestisco gli errori di validazione

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +    // gestisco l'errore di sintassi
gestisco gli errori di sintassi

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Nel codice qui sopra, `readUser` funziona perfettamente come descritto -- la sintassi di cattura, la validazione degli errori e il rilancio degli errori `ReadError` (gli errori sconosciuti saranno ri
-- <del>la sintassi di cattura, la validazione degli errori e il rilancio degli errori `ReadError`</del>
-- Intercetta gli errori di sintassi e di validazione e lancia l'errore `ReadError`

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Quindi il codice più esterno controllerà per `instanceof ReadError` e basta. Non è necessario controllare per tutti i tipi di errori.
Non è necessario controllare ~per~ tutti i tipi di errori

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +Questo approccio è chiamato "wrapping exceptions", perchè controlliamo le eccezioni di "basso livello" e le "ingobliamo" in `ReadError` che è più astratto. Questo approccio è largamente utilizzato ne
le eccezioni di "basso livello" e le <del>"ingobliamo"</del> "inglobiamo" in

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/2-custom-errors/article.md
> +- Possiamo ereditare da `Error` e altri classi di errori incorporate. Dobbiamo fare attenzione alla proprietà `name` e non di dimenticare di richiamare `super`.
Possiamo ereditare da `Error` e altri classi di errore incorporate. Dobbiamo fare attenzione alla proprietà `name` e non dimenticare di richiamare `super`.

2021-01-05 15:55 UTC, pasor1 commented on 1-js/10-error-handling/1-try-catch/1-finally-or-code-after/task.md
> +importanza: 5
"importance" all' inizio di ogni esercizio non va tradotto, ha un' utilità lato server nel codice originale in inglese, e se tradotto non viene più mostrato.

2021-01-08 20:59 UTC, longo-andrea commented
@mrkrash I take in charge the requested changes

2021-01-08 21:27 UTC, closed without merging