Update article.md
javascript-tutorial/it.javascript.info pull request #156
Opened 2021-01-04 21:22 UTC by pierangelomiceli

Aggiornato articolo.
Translation completed

2021-01-05 11:01 UTC, mean2me requested changes
Ci sono svariati errori di battitura e alcune traduzione sono troppo letterali e in italiano risultano poco chiare e poco fluide.

2021-01-05 11:01 UTC, mean2me commented on 5-network/12-server-sent-events/article.md
> +- `id:` -- aggiorna il `lastEventId`, inviato dentro `Last-Event-ID` in fase di riconnnessione.
- Typo: "riconnnessione" ( ci sono 3 "n")
- Typo: "intrpretata" => "interpretata"

2021-01-05 11:01 UTC, mean2me commented on 5-network/12-server-sent-events/article.md
> +- `retry:` -- raccomnda una ritardo nel tentativo di riconessione in millisecondi. Non c'&egrave; modo di impostarlo da JavaScript.
- Typo: "raccomnda"

2021-01-20 22:28 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +  //logghera' 3 volte per il data stream poco sopra
no. ovviamente in italiano si scirve correttamente come dici tu loggherà, ma per convenzione nei commenti in javascript non si usano i caratteri speciali e i caratteri con gli accenti, onde evitare problemi di codifica.

2021-01-20 22:29 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +: Lo stato corrente della connessione: uno tra `EventSource.CONNECTING (=0)`, `EventSource.OPEN (=1)` o `EventSource.CLOSED (=2)`.
inserito

2021-01-20 22:29 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +In pratica, i messaggi complessi sono solitamente inviati tramite oggetti codificati in JSO. I Line-breaks sono codificati come `\n` tra essi, e in questo modo i messaggi `data:` multiriga non sono n
ok

2021-01-20 22:30 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- Per inviare un line break `\n`, possiamo inviare immediatamente un altro `data:` (il terzo messaggio poco pi&ugrave; sopra).
ok

2021-01-20 22:30 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- Un messaggio di testo che va dopo `data:`, lo spazio dopo la virgola &egrave; opzionale.
ok

2021-01-20 22:30 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +Abbiamo necessit&agrave; di rivcevere un data stream da un server: forse messaggi di chat o prezzi dei mercati. Quusto &egrave; ci&ograve; per cui `EventSource` &egrave; fatto. Supporta anche l'uto r
la mia versione stranamente aveva già queste correzioni.

2021-01-20 22:34 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +: In caseo di error, inclusi sia la connessione persa (si riconnetter&agrave; automaticamente), e errori fatali. Possiamo controllare `readyState` per vedere se &egrave; stata tentata la riconnession
inserito questa forma:In caso di errori, inclusi la connessione persa (con riconnessione automatica) ed errori fatali.

2021-01-20 22:34 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +Il server pu&ograve; impostare un evento custom dentro `event:`. Questi eventi andrebbero gestiti usando `addEventListener`, e non `on<event>`.
ok!

2021-01-20 22:36 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- `id:` -- aggiorna il `lastEventId`, inviato dentro `Last-Event-ID` in fase di riconnnessione.
fatto

2021-01-20 22:36 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- `retry:` -- raccomnda una ritardo nel tentativo di riconessione in millisecondi. Non c'&egrave; modo di impostarlo da JavaScript.
fatto

2021-01-20 22:38 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- `retry:` -- raccomnda una ritardo nel tentativo di riconessione in millisecondi. Non c'&egrave; modo di impostarlo da JavaScript.
aggiungo che questo PR si può eliminare perchè parte da una versione sconosciuta, tra le altre cose la versione del mio repo ed anche quella già presente nel repo master italiano non presentano già alcuni di questi errori.
Nel mio repo ho già inserito le correzioni che sono state suggerite, in pratica tutte tranne una (quelle del commento in javacript) inoltre eliminerò le html entities nel testo.

2021-01-20 22:39 UTC, pierangelomiceli commented on 5-network/12-server-sent-events/article.md
> +- `retry:` -- raccomnda una ritardo nel tentativo di riconessione in millisecondi. Non c'&egrave; modo di impostarlo da JavaScript.
seguirà una nuova pull request che comprenderà queste modifiche.

2021-01-20 22:50 UTC, closed without merging