Resync
javascript-tutorial/it.javascript.info pull request #158
Opened 2021-01-06 17:31 UTC by pasor1

trying to sync with en repo

2021-01-06 17:31 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=158) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you all sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=158) before we can accept your contribution.<br/>**3** out of **12** committers have signed the CLA.<br/><br/>:white_check_mark: iliakan<br/>:white_check_mark: joaquinelio<br/>:white_check_mark: pasor1<br/>:x: heypano<br/>:x: tokou<br/>:x: Danziger<br/>:x: RapTho<br/>:x: raycon<br/>:x: Georgy-Losenkov<br/>:x: imaverage<br/>:x: wolfter12<br/>:x: LLyaudet<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/it.javascript.info?pullRequest=158) it.</sub>

2021-01-06 18:02 UTC, pasor1 commented
Aggiornato leggermente readme.md con info sul server locale di prova e procedure per sfruttare il bot

2021-01-06 21:31 UTC, longo-andrea commented on 1-js/03-code-quality/06-polyfills/article.md
> +Ad esempio, `Math.trunc(n)` è una funziona che "taglia" la parte decimale di un numero, es. `Math.trunc(1.23) = 1`.
qui propongo di utilizzare "tronca" al posto di "taglia"

2021-01-06 21:39 UTC, longo-andrea commented on 1-js/05-data-types/11-date/article.md
> +- `YYYY-MM-DD` -- è la data: ano-mese-giorno.
ano-mese-giorno => anno-mese-giorno

2021-01-06 21:42 UTC, longo-andrea commented on 1-js/06-advanced-functions/04-var/article.md
> +Con `var`, possiamo ri-dichiarare una variabile quante volte vogliamo. Se proviamo ad utilizzare `var` con una variabile già dichiarata, verrà semplicemente ignorato:
ignorato => ignorata

2021-01-06 21:49 UTC, longo-andrea commented on 1-js/11-async/05-promise-api/article.md
> +La compriamo per poiché, poiché è usata raramente in codice reale.
ma hahah spero di non essere stato io a tradurre sta frase 🤣 ci ho messo un pò a risalire a cosa dovrebbe esserci scritto.
La frase giusta è "la copriamo per completezza, poiché viene usata raramente nel codice reale"

2021-01-06 21:51 UTC, longo-andrea commented on 2-ui/1-document/02-dom-nodes/article.md
> +Qui abbiamo utilizzato `style.background` per cambiare il color del background di `document.body`, ma ci sono molte altre proprietà, come:
color => colore
in questo caso si intende colore di background, non la proprietà color del CSS

2021-01-06 21:52 UTC, longo-andrea commented on 2-ui/1-document/02-dom-nodes/article.md
> +- `innerHTML` -- il o HTML del nodo.
qui penso sia stata cancellata la parola per sbaglio. La frase è 
`innerHTML` -- il contenuto HTML del nodo.

2021-01-06 21:57 UTC, longo-andrea commented on 5-network/04-fetch-abort/article.md
> +1. The one that performs a cancelable operation, it sets a listener on `controller.signal`.
perché qui ci sono due righe in inglese? Questo dobbiamo segnarlo come da rivedere

2021-01-06 22:07 UTC, longo-andrea requested changes
Review completata. Ho lasciato un paio di commenti, ma in generale mi sembra okay. Gli articoli in lingua originale non li ho verificati, visto che dobbiamo ancora tradurli e potrebbero subire altri cambiamenti

2021-01-07 07:51 UTC, pasor1 commented on 1-js/03-code-quality/06-polyfills/article.md
> +Ad esempio, `Math.trunc(n)` è una funziona che "taglia" la parte decimale di un numero, es. `Math.trunc(1.23) = 1`.
/done

2021-01-07 07:53 UTC, pasor1 commented on 1-js/05-data-types/11-date/article.md
> +- `YYYY-MM-DD` -- è la data: ano-mese-giorno.
:sweat_smile:  /done

2021-01-07 07:54 UTC, pasor1 commented on 1-js/06-advanced-functions/04-var/article.md
> +Con `var`, possiamo ri-dichiarare una variabile quante volte vogliamo. Se proviamo ad utilizzare `var` con una variabile già dichiarata, verrà semplicemente ignorato:
modificato in "Se proviamo ad utilizzare `var` con una variabile già dichiarata, esso verrà semplicemente ignorato e la variabile verrà normalmente riassegnata:"

2021-01-07 07:57 UTC, pasor1 commented on 1-js/11-async/05-promise-api/article.md
> +La compriamo per poiché, poiché è usata raramente in codice reale.
/done

2021-01-07 08:00 UTC, pasor1 commented on 2-ui/1-document/02-dom-nodes/article.md
> +Qui abbiamo utilizzato `style.background` per cambiare il color del background di `document.body`, ma ci sono molte altre proprietà, come:
/done

2021-01-07 08:03 UTC, pasor1 commented on 2-ui/1-document/02-dom-nodes/article.md
> +- `innerHTML` -- il o HTML del nodo.
/done

2021-01-07 08:12 UTC, pasor1 commented on 5-network/04-fetch-abort/article.md
> +1. The one that performs a cancelable operation, it sets a listener on `controller.signal`.
tradotto

2021-01-07 08:13 UTC, pasor1 commented
/done

2021-01-07 13:08 UTC, merged