Article/11 logical operators
javascript-tutorial/it.javascript.info pull request #181
Opened 2021-01-22 13:28 UTC by Dorin-David

Ho finito la revisione dell'articolo sui logical operators. C'erano un pochino di cosette da sistemare. Per favore controllare e fatemi sapere so mi sono perso qualcosa.

2021-01-23 07:25 UTC, Dorin-David commented
@pasor1 Chiariscimi un dubbio cortesemente. Sto revisionando l'articolo sui loop, dove negli snippet con codici i commenti sono scritti in italiano; in questo articolo, pero', li ho lasciati in inglese. Come ci comportiamo a riguardo? Dovremmo farlo presente anche agli altri, non penso sia chiara la cosa...

2021-01-23 14:17 UTC, pasor1 reviewed
> @pasor1 Chiariscimi un dubbio cortesemente. Sto revisionando l'articolo sui loop, dove negli snippet con codici i commenti sono scritti in italiano; in questo articolo, pero', li ho lasciati in inglese. Come ci comportiamo a riguardo? Dovremmo farlo presente anche agli altri, non penso sia chiara la cosa...

Come regola, negli esempi di codice  traduciamo solo i commenti, non traduciamo il codice (variabili, funzioni, ecc...)

2021-01-23 15:21 UTC, pasor1 requested changes

2021-01-23 15:21 UTC, pasor1 commented on 1-js/02-first-steps/11-logical-operators/article.md
> +**Un valore viene ritornato nella sua forma originale, non nella sua conversione booleana.
```suggestion
Un valore viene ritornato nella sua forma originale, non nella sua conversione booleana.
```

2021-01-23 15:21 UTC, pasor1 commented on 1-js/02-first-steps/11-logical-operators/article.md
> +    Gli operandi, oltre che valori, possono essere anche espressioni arbitrarie. L'operatore OR esegue la valutazione da sinistra a destra e si ferma al primo risultato vero, che viene ritornato. Il
```suggestion
    Gli operandi, oltre che valori, possono essere anche espressioni arbitrarie. L'operatore OR esegue la valutazione da sinistra a destra e si ferma al primo risultato vero, il quale viene ritornato. Il processo è chiamato "valutazione a corto-circuito" perché cerca di concludersi il prima possibile, senza dover elaborare tutti gli operandi. 
```

2021-01-23 15:21 UTC, pasor1 commented on 1-js/02-first-steps/11-logical-operators/article.md
> +2. Ritorna il valore **inverso.
```suggestion
2. Ritorna il valore inverso.
```
Anche precedentemente ho notato un "bold" (**) non chiuso.... è voluto o un refuso?

2021-01-23 15:21 UTC, pasor1 commented on 1-js/02-first-steps/11-logical-operators/article.md
> +C'è un modo molto più lungo per fare la stessa cosa -- una funzione *built-in* di `Boolean`:
```suggestion
C'è un modo molto più lungo per fare la stessa cosa, usare la funzione `Boolean`, integrata in JavaScript:
```

2021-01-23 22:48 UTC, Dorin-David commented on 1-js/02-first-steps/11-logical-operators/article.md
> +2. Ritorna il valore **inverso.
Refuso perche' ho scordato di chiudere. Io **inverso** lo lascerei bold, penso aiuti. O preferisci attenerti alla versione originale? Dovrei evitare di prendermi questa liberta' in prossime review?

2021-01-23 23:12 UTC, longo-andrea commented on 1-js/02-first-steps/11-logical-operators/article.md
> +2. Ritorna il valore **inverso.
opinione personale, io toglierei il grassetto.. mi sembra che il paragrafo renda già chiaro di cosa si sta parlando, quindi non è necessario mettere in risalto il fatto che il valore si inverte...
Per quanto riguarda prendersi la libertà di fare modifiche, non vorrei dare regole stringenti, vale sempre il discorso del buon senso... se una frase tradotta letteralmente non ha senso, chiaramente vanno apportate delle modifiche... in questo specifico caso però non mi sembra un valore aggiunto necessario

2021-01-24 06:53 UTC, Dorin-David commented on 1-js/02-first-steps/11-logical-operators/article.md
> +2. Ritorna il valore **inverso.
Got it! :)

2021-01-24 07:08 UTC, Dorin-David commented
/done

2021-01-24 09:13 UTC, pasor1 approved these changes
:+1:

2021-01-24 09:14 UTC, merged