02-object-copy
javascript-tutorial/it.javascript.info pull request #182
Opened 2021-01-22 15:32 UTC by pasor1

2021-01-23 10:18 UTC, longo-andrea requested changes

2021-01-23 10:18 UTC, longo-andrea commented on 1-js/04-object-basics/02-object-copy/article.md
> +**Una variabile assegnata ad un oggetto non contiene l'oggetto in sè, ma il suo "indirizzo in memoria" -- in altre parole "un riferimento" all'oggetto.**
```suggestion
**Una variabile assegnata ad un oggetto non contiene l'oggetto in sé, ma il suo "indirizzo in memoria" -- in altre parole "un riferimento" all'oggetto.**
```

2021-01-23 10:18 UTC, longo-andrea commented on 1-js/04-object-basics/02-object-copy/article.md
> +**Quando una variabile oggetto viene copiata, in realtà viene copiato il riferimento, ma l'oggetto in sè non viene duplicato.**
```suggestion
**Quando una variabile oggetto viene copiata, in realtà viene copiato il riferimento, ma l'oggetto in sé non viene duplicato.**
```

2021-01-23 10:18 UTC, longo-andrea commented on 1-js/04-object-basics/02-object-copy/article.md
> +Questa differenza è facile da comprendere se guardiamo cosa succede sotto al cofano quando copiamo un valore.
questo `sotto il cofano` mi fa strano da leggere, però è vero che tenere `under the hood` sarebbe altrettanto brutto. Si potrebbe pensare di riscrivere la frase in qualcosa del tipo:

`Questa differenza è facile da comprendere se andiamo a guardare il comportamento del linguaggio quando compiamo un valore`

2021-01-23 10:18 UTC, longo-andrea commented on 1-js/04-object-basics/02-object-copy/article.md
> +Anche questo è fattibile, ma con un po' di difficoltà visto Javascript non integra alcun metodo per farlo. In realtà non è un'operazione frequente, il più delle volte la copia pèr riferimento è adatt
```suggestion
Anche questo è fattibile, ma con un po' di difficoltà visto che JavaScript non integra alcun metodo per farlo. In realtà non è un'operazione frequente, il più delle volte la copia per riferimento è adatta alla situazione.
```

2021-01-23 14:06 UTC, pasor1 commented on 1-js/04-object-basics/02-object-copy/article.md
> +Questa differenza è facile da comprendere se guardiamo cosa succede sotto al cofano quando copiamo un valore.
Mi sembra una buona alternativa, modifico...

2021-01-23 16:04 UTC, pasor1 commented
/done

2021-01-23 21:11 UTC, longo-andrea approved these changes

2021-01-23 21:11 UTC, longo-andrea commented on 1-js/04-object-basics/02-object-copy/article.md
> +Questa differenza è facile da comprendere se andiamo a guardare il comportamento del linguaggio quando copiamo un valore
```suggestion
Questa differenza è facile da comprendere se andiamo a guardare il comportamento del linguaggio quando copiamo un valore.
```

Manca il punto alla fine, il resto okay!

2021-01-23 21:12 UTC, longo-andrea commented
Per me l'articolo va bene cosi, essendo che è alla sua prima traduzione non sarebbe male ricevere una seconda revisiona da un terza persona

2021-01-24 07:15 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +L'oggetto è archiviato da qualche parte nella memoria (sulla destra dell'immagine), mentre la variabile `user` (sulla sinistra) contiene il "riferimento" ad esso.
*Sulla* [destra/sinistra] o *a*. "Sulla" non mi suona tanto bene...

2021-01-24 07:26 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +**Quando una variabile oggetto viene copiata, in realtà viene copiato il riferimento, ma l'oggetto in sé non viene duplicato.**
Sono un po' dubbioso su *variabile oggetto*. Penso sia piu' intuitivo nella versione inglese. In italiano, credo, potrebbe confondere (siccome abbiamo frasi come 'la legge oggetto di revisione', 'l'oggetto dei miei studi' ecc). Che ne dici di aggiungere delle virgolette? *"variabile oggetto"*. Toglierei altresì il *ma* alla fine. Infine sono anche un po' dubbioso su *in sé*. E' corretto e suona bene, ma penso possa essere piu' intuitivo *l'oggetto riferito* (così utilizziamo anche la terminologia tecnica)

2021-01-24 07:34 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Qui, invece, due oggetti identici (entrambi vuoti) ma indipendenti, non soddisfano l'uguaglianza:
(opionione personalissima: aggiungerei una virgola dopo la parentesi). Non mi convince a pieno 'non soddisfano l'uguaglianza'... Non è molto chiaro. Funzionerebbe bene insieme a una traduzione di *equality query*; ad esempio (so che non suona bene, e' solo un esempio) *interrogazione d'uguaglianza* o *non soddisfa i criteri d'uguaglianza del comparison operator ['==']*. Che ne pensi?

2021-01-24 07:41 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Anche questo è fattibile, ma con un po' di difficoltà visto che JavaScript non integra alcun metodo per farlo. In realtà non è un'operazione frequente, il più delle volte la copia per riferimento è a
Suggerirei *Javascript non ha alcun metodo integrato per farlo*, mi sembra piu' chiaro di 'non integra'

2021-01-24 07:45 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
>  for (let key in user) {
aggiungerei 'nella variabile' prima di *clone*, cosi' si capisce che ci stiamo riferendo alla variabile. So che la mia e' una pignoleria ma a una prima lettura (specialmente per un principiante) 'copiare in clone' puo' confondere, sembra quasi una metodologia per copiare

2021-01-24 07:53 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +- Il primo argomento `dest` è l'oggetto di destinazione.
Non mi convince moltissimo *di destinazione*. Sarebbe piu' chiaro, magari, se aggiungessimo 'delle proprieta' da copiare'. (Nemmeno i sinonimi mi convincono molto; dalla treccani: finalità, fine, meta, mira, obiettivo, scopo, *target*, traguardo; forse "l'oggetto di mira"?)

2021-01-24 07:58 UTC, pasor1 commented on 1-js/04-object-basics/02-object-copy/article.md
> +L'oggetto è archiviato da qualche parte nella memoria (sulla destra dell'immagine), mentre la variabile `user` (sulla sinistra) contiene il "riferimento" ad esso.
ci ho pensato, ma qui ci si riferisce alla parte destra e sinistra dell'immagine e non a posizioni destra/sinistra rispetto all'immagine... vediamo se così va meglio
```suggestion
L'oggetto è archiviato da qualche parte nella memoria (parte destra dell'immagine), mentre la variabile `user` (parte sinistra) contiene il "riferimento" ad esso.
```

2021-01-24 08:01 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +- Gli argomenti successivi `src1, ..., srcN` (possono essere quanti vogliamo) sono gli oggetti sorgente.
'oggetti sorgente' mi lascia un po' perplesso. Sorgente di usa come aggettivo, 'sorgente di incompresioni', 'sorgente di guerra', non come termine tecnico. Mi piace come idea, per molti (quasi tutti forse) e' intuitivo, ma se uno andasse a cercare 'oggetto sorgente' troverebbe "In informatica, di codice o programma scritto in un linguaggio simbolico, prima che il compilatore lo traduca in linguaggio macchina e lo renda eseguibile dal computer." Il che puo' confondere ancor di piu' le idee. Suggerirei un piu' semplice 'oggetti da cui copiare'

2021-01-24 08:02 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Se una delle proprietà copiate è già presente nell'oggetto di destinazione, verrà sovrascritta.
Vedi sopra (anche se, ti diro',  qui e' intuitivo)

2021-01-24 08:03 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Vengono copiate tutte le proprietà di `user` nell'oggetto vuoto, quindi esso viene restituito.
Non mi convince molto 'quindi esso'. Suggerisco (questa la copio da un suggerimento che hai fatto a una mia PR) 'il quale'

2021-01-24 08:07 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Per correggere questo problema, dobbiamo usare un ciclo di clonazioni che esaminerà ogni valore di `user[key]` e, nel caso sia un oggetto, replichi anche la sua struttura. Questa operazione è chiamat
Un 'risolvere' invece di 'correggere' mi sembra piu' chiaro, in questo contesto (ed e' piu' vicino a 'fix'). Anche perche' non stiamo esattamente *correggendo*, tecnicamente non c'e' nessun errore.

2021-01-24 08:09 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +````smart header="Gli oggetti dichiarati con Const possono essere modificati"
Qui *Const* lo lascerei con la minuscola

2021-01-24 08:10 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +In altre parole, `const user` restituisce un errore solo se se proviamo a riassegnare del tutto `user=...`.
Qui metterei *in toto* invece di 'del tutto'

2021-01-24 08:11 UTC, Dorin-David requested changes
Ho suggerito un paio di modifiche. Tutte piccolezze, ottima traduzione e' stato un piacere leggerla!

2021-01-24 08:24 UTC, pasor1 commented on 1-js/04-object-basics/02-object-copy/article.md
> +**Quando una variabile oggetto viene copiata, in realtà viene copiato il riferimento, ma l'oggetto in sé non viene duplicato.**
D'accordo sulle virgolette, vedo di correggere tutte le istanze. Mentre per _oggetto riferito_ mi sembra un po' troppo difficile, ricordiamoci che il tutorial nasce con l'intento di essere facile da leggere.

2021-01-24 08:34 UTC, pasor1 commented on 1-js/04-object-basics/02-object-copy/article.md
> +- Il primo argomento `dest` è l'oggetto di destinazione.
piu' letteralmente "target" sarebbe "obiettivo", ma in questo caso "destinazione" mi sembra renda meglio l'idea

2021-01-24 08:45 UTC, pasor1 commented
/done

2021-01-24 09:55 UTC, Dorin-David commented on 1-js/04-object-basics/02-object-copy/article.md
> +Tutte le operazione su un riferimento duplicato (come aggiungere o rimuovere proprietà) hanno effetto sul medesimo oggetto.
*operazioni*

2021-01-24 10:14 UTC, pasor1 commented
/done

2021-01-24 16:19 UTC, Dorin-David approved these changes

2021-01-24 16:22 UTC, Dorin-David approved these changes
Test

2021-01-24 16:28 UTC, merged