Introduction to browser events
javascript-tutorial/it.javascript.info pull request #183
Opened 2021-01-23 00:15 UTC by pierangelomiceli

C'è una nota del traduttore (N.d.T.), che chiarisce un po' il concetto

2021-01-23 13:54 UTC, longo-andrea requested changes
L'articolo è okay, ti ho lasciato un paio di appunti.

Ti chiedo due cose però:
- rimuovere il file 'Server Sent Events' dalla PR
- tradurre anche i tasks e le solutions

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +- `DOMContentLoaded` -- quando l'HTML viene caricato e processato, e la struttura del DOM è stata completata.
```suggestion
- `DOMContentLoaded` -- quando l'HTML viene caricato e processato, e la costruzione del DOM è stata completata.
```

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Per reagire agli eventi possiamo assegnare un *gestore* (handler), che non è che una funzione che viene eseguita contestualmente alla generazione di un evento.
```suggestion
Per reagire agli eventi possiamo assegnare un *gestore* (handler), che non è altro che una funzione che viene eseguita contestualmente alla generazione di un evento.
```

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +### Attributo HTML (HTML-attribute)
```suggestion
### Attributo HTML
```

Mi sembra abbastanza chiaro il significato, non credo serva specificarlo

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Al click del mouse, il codice dentro `onclick` verrà eseguito.
```suggestion

Al click del mouse, il codice dentro `onclick` verrà eseguito.
```

Cerchiamo di rispettare gli 'a capo' come nella versione originale, cosi durante i sync non diventiamo matti con i diff

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  1. Only HTML:
```suggestion
1. Solo HTML:
```

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se il gestore viene assegnato usando un attributo HTML, il browser lo riconosce, crea una nuova funzione partendo dal contenuto dell'attributo e la scrive nella proprietà del DOM.
```suggestion

Se il gestore viene assegnato usando un attributo HTML, il browser lo riconosce, crea una nuova funzione partendo dal contenuto dell'attributo e la scrive nella proprietà del DOM.
```

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Mettiamo il caso che una parte del nostro codice serva ad evidenziare un pulsante al click, e che un altro serva a mostrare un messaggio al medesimo click.
```suggestion
Ipotizziamo che una parte del nostro codice serva ad evidenziare un pulsante al click, e che un altro serva a mostrare un messaggio al medesimo click.
```

Mi sembra più elegante `ipotizziamo`, che ne pensi?

2021-01-23 13:54 UTC, longo-andrea commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Il gestore non verrà rimosso, perchè `removeEventListener` prende come parametro un'altra funzione: è certamente con lo stesso codice, ma questo non ha alcuna rilevanza, dal momento che è un oggetto
```suggestion
Il gestore non verrà rimosso, perchè `removeEventListener` prende come parametro un'altra funzione: è certamente con lo stesso codice, ma questo non ha alcuna rilevanza, dal momento che è un oggetto funzione differente (fanno riferimento a due differenti indirizzi di memoria).
```

Mi sembra una buona spiegazione 👍  Rimuovo N.d.T

2021-01-23 20:56 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Per reagire agli eventi possiamo assegnare un *gestore* (handler), che non è che una funzione che viene eseguita contestualmente alla generazione di un evento.
/done

2021-01-23 20:56 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +- `DOMContentLoaded` -- quando l'HTML viene caricato e processato, e la struttura del DOM è stata completata.
/done

2021-01-23 20:56 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +### Attributo HTML (HTML-attribute)
/done

2021-01-23 20:57 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Al click del mouse, il codice dentro `onclick` verrà eseguito.
/done

2021-01-23 20:57 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
>  1. Only HTML:
/done

2021-01-23 20:57 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se il gestore viene assegnato usando un attributo HTML, il browser lo riconosce, crea una nuova funzione partendo dal contenuto dell'attributo e la scrive nella proprietà del DOM.
/done

2021-01-23 20:57 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Mettiamo il caso che una parte del nostro codice serva ad evidenziare un pulsante al click, e che un altro serva a mostrare un messaggio al medesimo click.
/done

2021-01-23 23:00 UTC, longo-andrea commented
/done

2021-01-23 23:03 UTC, longo-andrea approved these changes

2021-01-24 17:39 UTC, pasor1 requested changes
Qualche piccola correzione... Solo la prima è importante ;-)

2021-01-24 17:39 UTC, pasor1 commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se aggiungessimo le parentesi, allora `sayThanks()` diverrebbe una chiamata a funzione, di conseguenza il valore dell'assegnazione dell'ultima riga dell'esempio, sarebbe il risultato della chiamata,
```suggestion
Se aggiungessimo le parentesi, allora `sayThanks()` diverrebbe una chiamata a funzione. Di conseguenza il valore dell'assegnazione dell'ultima riga dell'esempio, sarebbe il risultato della chiamata, ossia `undefined` (dato che la funzione non restituisce nulla), e verrebbe assegnato ad `onclick`. Ovviamente così non potrebbe andare bene, ed inoltre non sarebbe nemmeno l'effetto voluto.
```

2021-01-24 17:39 UTC, pasor1 commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +````warn header="La rimozione prevede la stessa identica funzione"
```suggestion
````warn header="La rimozione richiede la stessa identica funzione"
```

2021-01-24 17:39 UTC, pasor1 commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se assegniamo un gestore dentro l'HTML, possiamo usare l'oggetto `evento`:
```suggestion
Anche se assegniamo un gestore dentro l'HTML, possiamo usare l'oggetto `evento`:
```

2021-01-24 17:39 UTC, pasor1 commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Nei prossimi capitoli, avremo modo di approfondire il tema degli eventi in generale ed le loro differenti tipologie.
```suggestion
Nei prossimi capitoli, avremo modo di approfondire il tema degli eventi in generale e le loro differenti tipologie.
```

2021-01-24 17:48 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Nei prossimi capitoli, avremo modo di approfondire il tema degli eventi in generale ed le loro differenti tipologie.
/done

2021-01-24 17:48 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se assegniamo un gestore dentro l'HTML, possiamo usare l'oggetto `evento`:
/done

2021-01-24 17:49 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +````warn header="La rimozione prevede la stessa identica funzione"
/done

2021-01-24 17:49 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Se aggiungessimo le parentesi, allora `sayThanks()` diverrebbe una chiamata a funzione, di conseguenza il valore dell'assegnazione dell'ultima riga dell'esempio, sarebbe il risultato della chiamata,
/done

2021-01-24 17:50 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Per reagire agli eventi possiamo assegnare un *gestore* (handler), che non è altro che una funzione che viene eseguita contestualmente alla generazione di un evento.
/done

2021-01-24 17:51 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +Ci sono tanto altri eventi più specifici, che verranno affrontati in dettaglio nei prossimi capitoli.
/done

2021-01-24 17:51 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +# Introduzione agli aventi del browser
/don

2021-01-24 17:51 UTC, pierangelomiceli commented on 2-ui/2-events/01-introduction-browser-events/article.md
> +# Introduzione agli aventi del browser
/done

2021-01-24 18:04 UTC, pasor1 approved these changes

2021-01-24 18:07 UTC, pasor1 approved these changes

2021-01-24 18:08 UTC, merged