Optional chaining '?.'
javascript-tutorial/it.javascript.info pull request #187
Opened 2021-01-24 14:25 UTC by longo-andrea

Ho tradotto ```optional chaining``` in ```concatenazione opzionale```.. all'inzio non ero molto convinto, però cercando online mi sembra che generalmente venga tradotto... voi che ne pensate?

2021-01-24 16:14 UTC, pasor1 requested changes

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Se non esiste alcuna variabile `user`, allora `user?.anything` lancerà un errore:
```suggestion
Se non esiste alcuna variabile `user`, allora `user?.anything` provocherà un errore:
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Come detto in precedenza, il costrutto `?.` interrompe immediatamente (va in "corto circuito") la valutazione, se la proprietà a destra non esiste.
```suggestion
Come detto in precedenza, il costrutto `?.` interrompe immediatamente (manda in "corto circuito") la valutazione, se la proprietà a destra non esiste.
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Quindi, nel caso ci siano ulteriori chiamate a funzione o side-effect, questi non avverranno.
```suggestion
Quindi, nel caso ci siano ulteriori chiamate a funzione o side-effects, questi non verranno elaborati.
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Qui, in entrambe le righe come prima cosa abbiamo utilizzato il punto (`user1.admin`) per ottenere la proprietà `admin`, poiché l'oggetto `user` deve necessariamente esistere, quindi l'accesso è sicu
```suggestion
Qui, in entrambe le righe, come prima cosa abbiamo utilizzato il punto (`user1.admin`) per ottenere la proprietà `admin`, poiché l'oggetto `user` deve necessariamente esistere, quindi l'accesso è sicuro.
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Anche la funzione `?.[]` funziona, se volessimo usare le parentesi `[]` per accedere alle proprietà, invece del punto `.`. In maniera simile ai casi precedenti, potremmo accedere con sicurezza ad una
```suggestion
La sintassi `?.[]` funziona anche se volessimo usare le parentesi `[]` per accedere alle proprietà, invece del punto `.`. In maniera simile ai casi precedenti, potremmo accedere con sicurezza ad una proprietà di un oggetto, che potrebbe non esistere.
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +1. `obj?.prop` -- ritorna `obj.prop` se `obj` esiste, altrimenti `undefined`.
```suggestion
1. `obj?.prop` -- ritorna `obj.prop` se `obj` esiste, altrimenti ritorna `undefined`.
```

2021-01-24 16:14 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +2. `obj?.[prop]` -- ritorna `obj[prop]` se `obj` esiste, altrimenti `undefined`.
```suggestion
2. `obj?.[prop]` -- ritorna `obj[prop]` se `obj` esiste, altrimenti ritorna `undefined`.
```

2021-01-24 16:16 UTC, pasor1 commented
Secondo me "concatenamento opzionale" va bene come traduzione di "Optional chaining", magari ad inizio articolo lasciamo un (Optional chaining) come riferimento al termine tecnico in inglese

2021-01-24 20:43 UTC, longo-andrea commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +... Un altro esempio. Nello sviluppo web, possiamo ottenere un oggetto che corrisponde ad un elemento di una pagina web, utilizzando una chiamata ad un metodo speciale, come `document.querySelector('
con `ricevere` è già meglio, ma non mi convince al 100%... l'unica alternativa che mi viene in mente è girare la frase in questo modo:

`
Il metodo `document.querySelector('.elem')` restituisce un oggetto che corrisponde ad un elemento della pagina web.
`

2021-01-24 20:46 UTC, longo-andrea commented
/done

2021-01-24 20:49 UTC, pasor1 commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +... Un altro esempio. Nello sviluppo web, possiamo ottenere un oggetto che corrisponde ad un elemento di una pagina web, utilizzando una chiamata ad un metodo speciale, come `document.querySelector('
Ottimo, così è ancora più chiaro

2021-01-25 10:02 UTC, pasor1 approved these changes
:+1:

2021-01-26 09:53 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Se avete appena cominciato a leggere il tutorial e a imparare JavaScript, forse questo problema non lo avete ancora vissuto, ma è piuttosto comune.
```suggestion
Se avete appena cominciato a leggere il tutorial e a imparare JavaScript, forse questo problema non lo avete ancora affrontato, ma è piuttosto comune.
```
Non mi convince molto 'vissuto', non ho mai incontrato 'problema vissuto'

2021-01-26 09:56 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +... Un altro esempio. Il metodo `document.querySelector('.elem')` restituisce un oggetto che corrisponde ad un elemento della pagina web, che ritorna `null` quando l'elemento non esite.
```suggestion
... Un altro esempio. Il metodo `document.querySelector('.elem')` ritorna un oggetto che corrisponde ad un elemento della pagina web, che ritorna `null` quando l'elemento non esite.
```
*ritorna* mi sembra piu' chiaro (e' usato anche nella specifica); che ne pensi (non potrebbe restituire, comunque, nemmeno se lo volesse, perche' in realta' non ha preso nulla)

2021-01-26 09:57 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Di nuovo, se un elemente non esiste, otterremo un errore nel tentativo di accedere a `.innerHTML` di `null`. In alcuni casi, in cui l'assenza di un elemento è normale, vorremo evitare l'errore e acce
```suggestion
Di nuovo, se un elemente non esiste, otterremo un errore nel tentativo di accedere a `.innerHTML` di `null`. In alcuni casi, in cui l'assenza di un elemento è normale, vorremo evitare l'errore e accettare come risultato `html = null`.
```
Il *che* finale e' superfluo, e suona anche maluccio

2021-01-26 09:59 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Questo è semplicemente terribile, un codice del genere potrebbe anche essere difficile da comprendere.
```suggestion
Questo è semplicemente terribile, un codice del genere potrebbe essere difficile da comprendere.
```
*anche* mi sembra superfluo

2021-01-26 10:01 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Questo è il motivo per cui la concatenazione opzionale `?.`, è stata aggiunta al linguaggio. Per risolvere questo problema una volta per tutte!
```suggestion
Questo è il motivo per cui la concatenazione opzionale `?.` è stata aggiunta al linguaggio. Per risolvere questo problema una volta per tutte!
```
mi sembra suoni piu' chiaramente senza la virgola, che ne pensi?

2021-01-26 10:04 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Ad esempio, guardando la logica del nostro codice, l'oggetto `user` deve necessariamente esistere, mentre `address` è opzionale, quindi dovremmo scrivere `user.address?.street`, non `user?.address?.s
```suggestion
Ad esempio, considerando la logica del nostro codice, l'oggetto `user` deve necessariamente esistere, mentre `address` è opzionale, quindi dovremmo scrivere `user.address?.street`, non `user?.address?.street`.
```
*considerando* mi suona piu' preciso e formale. Che ne pensi?

2021-01-26 10:05 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Come detto in precedenza, il costrutto `?.` interrompe immediatamente (manda in "corto circuito") la valutazione, se la proprietà a destra non esiste.
```suggestion
Come detto in precedenza, il costrutto `?.` interrompe immediatamente (manda in "corto circuito") la valutazione se la proprietà a destra non esiste.
```
rimuoverei la parentesi, suona meglio. Che ne pensi?

2021-01-26 10:17 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +La sintassi `?.[]` funziona anche se volessimo usare le parentesi `[]` per accedere alle proprietà, invece del punto `.`. In maniera simile ai casi precedenti, potremmo accedere con sicurezza ad una
```suggestion
La sintassi `?.` funziona anche con le parentesi `[]` (invece del punto `.`). Come nei casi precedenti, possiamo accedere con sicurezza ad una proprietà di un oggetto che potrebbe non esistere.
```
La frase originale non e' chiarissima (anche in inglese). Io l'accorcerei, si capisce bene anche cosi'.

2021-01-26 10:18 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +La concatenazione opzionale `?.` non ha alcun significato alla sinistra di un assegnazione.
```suggestion
La concatenazione opzionale `?.` non ha alcun significato alla sinistra di un'assegnazione.
```

2021-01-26 10:19 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +La concatenazione opzionale `?.` possiede tre forme:
```suggestion
La concatenazione opzionale `?.` ha tre forme:
```
penso suoni meglio un piu' modesto 'ha' :)

2021-01-26 10:25 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +Come possiamo vedere, le tre forme sono semplici da utilizzare. Il costrutto `?.` verifica che la parte sinistra non sia `null/undefined` e permette alla valutazione di proseguire in caso contrario.
```suggestion
Come possiamo vedere, le tre forme sono semplici da utilizzare. Il costrutto `?.` verifica che la parte sinistra non sia `null/undefined`; se non lo è, permette alla valutazione di proseguire, altrimenti interrompe immediatamente la valutazione.
```
Nella tua traduzione dici: 'X non deve essere null/undefined'. Io passo una variabile che non lo e', ad esempio y = 'Hello world'; hai aggiunto pero' 'in caso contrario'; quindi ora, perche' l'operatore ? prosegua, y **non deve essere diversa da null/undefined** (probabilmente ti ho confuso piu' le idee con questo commento; se leggi bene ti accorgerai della sottigliezza in cui sei incappato)

2021-01-26 10:26 UTC, Dorin-David commented on 1-js/04-object-basics/07-optional-chaining/article.md
> +La concatenazione di `?.` permette di accedere in sicurezza alle proprietà annidate.
```suggestion
La concatenazione di `?.` permette di accedere in sicurezza a proprietà annidate.
```
Suggerisco *a*, e' piu' generale e si presta a piu' casi

2021-01-26 10:27 UTC, Dorin-David requested changes
Ottima traduzione! Ho suggerito un paio di cosette

2021-01-26 20:44 UTC, longo-andrea commented
/done

2021-01-26 20:45 UTC, merged