The "new Function" syntax
javascript-tutorial/it.javascript.info pull request #194
Opened 2021-01-27 18:18 UTC by pasor1

2021-01-27 19:02 UTC, pasor1 commented
Non capisco cosa ho combinato, ma insieme all' articolo tradotto sono passate anche alcune correzioni ortografiche fatte su altri articoli :disappointed_relieved:

2021-01-27 21:34 UTC, longo-andrea commented
okay, guardando i file che hai toccato direi che non ci sta lavorando nessuno... quindi se riusciamo a fare merge con le correzioni ancora meglio 😄

2021-01-27 21:40 UTC, longo-andrea commented on 1-js/06-advanced-functions/07-new-function/article.md
> +Nelle funzioni create con `new Function`, `[[Environment]]` fa riferimento al Lexical Environment globale, non a quello esterno. Quindi queste funzioni non possono utilizzare variabili esterne. In re
```suggestion
Nelle funzioni create con `new Function`, `[[Environment]]` fa riferimento al Lexical Environment globale, non a quello esterno. Quindi queste funzioni non possono utilizzare variabili esterne. In realtà ciò è un bene perché ci mette al riparo da errori. Passare i parametri in modo esplicito è un metodo migliore dal punto di vista architetturale e non causa problemi con i minifiers.
```

2021-01-27 21:40 UTC, longo-andrea approved these changes

2021-01-31 12:17 UTC, Dorin-David commented on 1-js/06-advanced-functions/07-new-function/article.md
> +La differenza dalle altre modalità di creazione funzioni che abbiamo visto, è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
Non suona benissimo 'creazione funzioni';  che ne pensi di:
```suggestion
La differenza dalle altre modalità di creazione delle funzioni che abbiamo visto, è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
```
oppure: 

```suggestion
La differenza dalle altre modalità di creazione delle funzioni che abbiamo visto, è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
```
oppure:

```suggestion
La differenza dalle altre modalità che abbiamo visto di creazione delle funzioni  è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
```
(Propenderei per l'ultima; so che anche i miei suggerimenti suonano male, ma scrivere direttamente 'creazione funzioni' senza l'articolo non mi sembra corretto). Che ne pensi?

2021-01-31 12:25 UTC, Dorin-David commented on 1-js/06-advanced-functions/07-new-function/article.md
> +La differenza dalle altre modalità di creazione funzioni che abbiamo visto, è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
Altra piccolezza: quando, qui sopra, diciamo 'lettaralmente' intendiamo una specie di termine tecnico per 'estrazione da una stringa' oppure il classico modo di dire 'letteralmente'? Perche', nel qual caso fosse la seconda, metterei: 
```suggestion
La differenza dalle altre modalità di creazione funzioni che abbiamo visto, è che  qui la funzione viene letteralmente creata da una stringa, che viene passata in fase di esecuzione.
```

2021-01-31 12:26 UTC, Dorin-David commented on 1-js/06-advanced-functions/07-new-function/article.md
> +Viene utilizzato in casi molto specifici, come quando riceviamo codice da un server, o per compilare dinamicamente una funzione da un modello, in applicazioni web complesse.
```suggestion
Viene utilizzato in casi molto specifici, come quando riceviamo un codice da un server, o per compilare dinamicamente una funzione da un modello, in applicazioni web complesse.
```

2021-01-31 12:27 UTC, Dorin-David commented on 1-js/06-advanced-functions/07-new-function/article.md
> +Di solito, una funzione memorizza dove è nata nella proprietà speciale `[[Environment]]`. Questa fa riferimento al Lexical Environment da cui è stata creata (lo abbiamo trattato nel capitolo <info:cl
```suggestion
Di solito, una funzione memorizza dove è nata nella proprietà speciale `[[Environment]]`. Questa fa riferimento al Lexical Environment in cui è stata creata (lo abbiamo trattato nel capitolo <info:closure>).
```
La funzione non viene creata *dal* Lexical Environment ma *nel* Lexical Environment

2021-01-31 12:31 UTC, Dorin-David commented on 1-js/09-classes/02-class-inheritance/article.md
> +Anche se, si verifica un comportamento strano quando proviamo ad accedere ad un campo sovrascritto nel costruttore padre, piuttosto differente da altri linguaggi di programmazione.
```suggestion
Anche se, si verifica un comportamento strano quando proviamo ad accedere ad un campo sovrascritto nel costruttore genitore, piuttosto differente da altri linguaggi di programmazione.
```
genitore mi sembra un termine piu' generico e tecnico

2021-01-31 12:34 UTC, Dorin-David commented on 1-js/09-classes/02-class-inheritance/article.md
> +E questo è quello che ci aspetteremo. Quando il costruttore genitore viene invocato da una classe derivata, utilizzate i metodi sovrascritti.
```suggestion
E questo è quello che ci aspetteremmo. Quando il costruttore genitore viene invocato da una classe derivata, utilizzate i metodi sovrascritti.
```
intendevi forse **aspetteremmo**,  'prima persona plurale del **condizionale** presente'? (hai tradotto 'that's what we'd expect'?)

2021-01-31 12:35 UTC, Dorin-David commented on 1-js/09-classes/02-class-inheritance/article.md
> +Fortunatamente, questo comportamento si verifica solamente se un campo dati va a sovrascrivere quelli della classe genitore. Potrebbe essere difficile da capire come comportamento, per questo lo abbi
```suggestion
Fortunatamente, questo comportamento si verifica solamente se un campo dati va a sovrascrivere quelli della classe genitore. Potrebbe essere difficile da capire come comportamento, per questo lo abbiamo spiegato.
```
Il 'qui' finale mi sembra superfluo

2021-01-31 12:36 UTC, Dorin-David requested changes
Gran traduzione! Aggiusterei giusto due cosette...

2021-01-31 13:17 UTC, pasor1 commented on 1-js/06-advanced-functions/07-new-function/article.md
> +La differenza dalle altre modalità di creazione funzioni che abbiamo visto, è che  qui la funzione viene creata letteralmente da una stringa, che viene passata in fase di esecuzione.
Io l'ho inteso piu' come termine "tecnico" ... per quello ho tradotto così ;-)

2021-01-31 13:23 UTC, merged