Property getters and setters
javascript-tutorial/it.javascript.info pull request #199
Opened 2021-01-30 18:33 UTC by longo-andrea

2021-01-31 10:03 UTC, pasor1 requested changes
Qualche suggerimento

2021-01-31 20:25 UTC, longo-andrea commented on 1-js/07-object-properties/02-property-accessors/article.md
> +## Descritto degli accessors
Cosa ho scritto qua haha

2021-01-31 20:26 UTC, longo-andrea commented
/done

2021-02-03 08:16 UTC, pasor1 approved these changes

2021-02-06 15:17 UTC, merged