Dispatching custom events
javascript-tutorial/it.javascript.info pull request #201
Opened 2021-02-02 23:41 UTC by pierangelomiceli

2021-02-03 21:49 UTC, longo-andrea requested changes

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +Gli eventi personalizzati (custom events) possono essere usati per creare "componenti grafici". Ad esempio un elemento radice del nostro menù basato su JavaScript, può innescare degli eventi che indi
Qui la traduzione sarebbe anche okay, ma non mi convince per nulla la frase, nemmeno il lingua originale a voler essere onesti... se si sta parlando di eventi, esempio "open" io lo intuisco come evento di qualcosa che è successo e non come "stato di apertura del menu".... infatti un evento come "click" indica che l'elemento ha subito un click, non sta dicendo se quell'elemento è già stato cliccato... Quindi ti propongo un suggerimento, ma è assolutamente opzionale.
```suggestion
Gli eventi personalizzati (custom events) possono essere usati per creare "componenti grafici". Ad esempio un elemento radice del nostro menù basato su JavaScript, potrebbe innescare eventi che indicano al menù come comportarsi: `open` (aprire il menu), `select` (selezionare un elemento) e così via. Del codice in altre aree, potrebbe mettersi in ascolto per questi eventi e tenere traccia di cosa sta avvenendo nel menù.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +Possiamo generare non solo eventi del tutto nuovi, creati apposta per i nostri scopi, ma anche quelli predefiniti del linguaggio, come `click`, `mousedown` etc. Questo può essere utile per dei testi
```suggestion
Possiamo generare non solo eventi del tutto nuovi, creati apposta per i nostri scopi, ma anche quelli predefiniti del linguaggio, come `click`, `mousedown` etc. Questo può essere utile per i test automatici.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +- *type* -- tipo dell'evento, una stringa come `"click"` oppure una personale come `"mio-evento"`.
anche qui "personale" non mi piace troppo, nemmeno in inglese

```suggestion
- *type* -- tipo dell'evento, una stringa come `"click"` oppure una personalizzata come `"mio-evento"`.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +Per poter distinguere un evento generato da un utente "reale", da una generato da script esiste un modo.
```suggestion
Per poter distinguere un evento generato da un utente "reale", da uno generato da script esiste un modo.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +1. Per i nostri eventi personalizzati dobbiamo usare `addEventListener`, in quanto `on<event>` esiste solo per quelli predefiniti: `document.onhello` non funziona.
```suggestion
1. Per i nostri eventi personalizzati dobbiamo usare `addEventListener`, in quanto `on<event>` esiste solo per quelli predefiniti: quindi `document.onhello` non funzionerà.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +Tecnicamente, possiamo aggirare il problema assegnandogli direttamente `event.clientX=100` dopo la creazione. Ma è una questione di comodità oltre che di aderenza alle regole. Gli eventi generati dal
```suggestion
Tecnicamente, possiamo aggirare il problema assegnandogli direttamente `event.clientX=100` dopo la creazione. Ma è una questione di comodità oltre che di aderenza alle regole. Gli eventi generati dal browser garantiscono sempre di avere il tipo corretto.
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +La lista completa delle proprietà, per i vari venti della UI sono descritti nelle specifiche, ad esempio, [MouseEvent](https://www.w3.org/TR/uievents/#mouseevent).
```suggestion
La lista completa delle proprietà, per i vari eventi della UI sono descritti nelle specifiche, ad esempio, [MouseEvent](https://www.w3.org/TR/uievents/#mouseevent).
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +## Gli eventi negli eventi sono sincroni
Anche qui, proposta totalmente opzionale
```suggestion
## Gli eventi annidati sono sincroni
```

2021-02-03 21:49 UTC, longo-andrea commented on 2-ui/2-events/05-dispatch-events/article.md
> +Non dovremmo generare eventi del browser perché una pratica poco elegante e sporca nell'esecuzione dei gestori. La maggior parte delle volte, si tratta di cattiva architettura.
```suggestion
Non dovremmo generare eventi del browser perché è una pratica poco elegante e sporca nell'esecuzione dei gestori. La maggior parte delle volte, si tratta di cattiva architettura.
```

2021-02-05 21:44 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Non dovremmo generare eventi del browser perché una pratica poco elegante e sporca nell'esecuzione dei gestori. La maggior parte delle volte, si tratta di cattiva architettura.
/done

2021-02-05 21:44 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +## Gli eventi negli eventi sono sincroni
/done

2021-02-05 21:44 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +La lista completa delle proprietà, per i vari venti della UI sono descritti nelle specifiche, ad esempio, [MouseEvent](https://www.w3.org/TR/uievents/#mouseevent).
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Tecnicamente, possiamo aggirare il problema assegnandogli direttamente `event.clientX=100` dopo la creazione. Ma è una questione di comodità oltre che di aderenza alle regole. Gli eventi generati dal
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +1. Per i nostri eventi personalizzati dobbiamo usare `addEventListener`, in quanto `on<event>` esiste solo per quelli predefiniti: `document.onhello` non funziona.
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Per poter distinguere un evento generato da un utente "reale", da una generato da script esiste un modo.
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +- *type* -- tipo dell'evento, una stringa come `"click"` oppure una personale come `"mio-evento"`.
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Possiamo generare non solo eventi del tutto nuovi, creati apposta per i nostri scopi, ma anche quelli predefiniti del linguaggio, come `click`, `mousedown` etc. Questo può essere utile per dei testi
/done

2021-02-05 21:45 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Gli eventi personalizzati (custom events) possono essere usati per creare "componenti grafici". Ad esempio un elemento radice del nostro menù basato su JavaScript, può innescare degli eventi che indi
/done

2021-02-06 14:52 UTC, longo-andrea commented
/done

2021-02-06 14:53 UTC, longo-andrea commented
/done

2021-02-09 18:13 UTC, pasor1 approved these changes
Solo qualche piccola correzione. Bel lavoro :muscle:

2021-02-09 18:13 UTC, pasor1 commented on 2-ui/2-events/05-dispatch-events/article.md
> +Allora potremmo sia inserire `dispatchEvent` (o un altra chiamata che generi un evento) alla fine di  `onclick` o, forse anche meglio, avvolgerlo in un `setTimeout` a ritardo zero:
```suggestion
Allora potremmo sia inserire `dispatchEvent` (o un altra chiamata che generi un evento) alla fine di  `onclick` oppure, forse anche meglio, incapsularlo in un `setTimeout` a ritardo zero:
```

2021-02-09 18:13 UTC, pasor1 commented on 2-ui/2-events/05-dispatch-events/article.md
> +Adesso `dispatchEvent` viene eseguito in maniera asincrona, dopo che l'esecuzione del codice corrente è terminata, incluso `menu.onclick`, ed in questo modo i gestori sono totalmente separati.
```suggestion
Adesso `dispatchEvent` viene eseguito in maniera asincrona dopo che l'esecuzione del codice corrente è terminata, incluso `menu.onclick`, ed in questo modo i gestori sono totalmente separati.
```

2021-02-09 18:13 UTC, pasor1 commented on 2-ui/2-events/05-dispatch-events/article.md
> +Altri costruttori di eventi nativi come `MouseEvent`, `KeyboardEvent` e così via, accettano proprietà specifiche per quel tipo di evento. Ad esempio, `clientX` per glie eventi del mouse.
```suggestion
Altri costruttori di eventi nativi come `MouseEvent`, `KeyboardEvent` e così via, accettano proprietà specifiche per quel tipo di evento. Ad esempio, `clientX` per gli eventi del mouse.
```

2021-02-09 18:13 UTC, pasor1 commented on 2-ui/2-events/05-dispatch-events/article.md
> +Gi eventi nativi possono essere generati quando:
```suggestion
Gli eventi nativi possono essere generati:
```

2021-02-09 19:05 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +A questo punto, il gestore reagisce su di esso come se fosse un evento del browser normale. Se l'evento è stato creato con l'opzione `bubbles` attivata, allora procederà con il bubbling.
/done

2021-02-09 19:06 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Oltretutto, la classe evento descrive "che tipo di evento" sia, e se si tratta di un evento personalizzato, allora possiamo usare `CustomEvent` anche solo per palesare di cosa si tratti.
/done

2021-02-09 19:06 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Allora potremmo sia inserire `dispatchEvent` (o un altra chiamata che generi un evento) alla fine di  `onclick` o, forse anche meglio, avvolgerlo in un `setTimeout` a ritardo zero:
/done

2021-02-09 19:06 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Adesso `dispatchEvent` viene eseguito in maniera asincrona, dopo che l'esecuzione del codice corrente è terminata, incluso `menu.onclick`, ed in questo modo i gestori sono totalmente separati.
/done

2021-02-09 19:06 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Altri costruttori di eventi nativi come `MouseEvent`, `KeyboardEvent` e così via, accettano proprietà specifiche per quel tipo di evento. Ad esempio, `clientX` per glie eventi del mouse.
/done

2021-02-09 19:06 UTC, pierangelomiceli commented on 2-ui/2-events/05-dispatch-events/article.md
> +Gi eventi nativi possono essere generati quando:
/done

2021-02-09 19:42 UTC, longo-andrea approved these changes

2021-02-09 19:42 UTC, merged