Event delegation
javascript-tutorial/it.javascript.info pull request #203
Opened 2021-02-06 00:16 UTC by pierangelomiceli

2021-02-06 14:56 UTC, longo-andrea commented
@pierangelomiceli intanto correggo l'articolo, manca però la traduzione degli esercizi e delle soluzioni

2021-02-06 15:00 UTC, longo-andrea reviewed
ho fatto solamente un check dei typos, dopo leggo l'articolo e ti do un feedback più dettagliato

2021-02-06 17:12 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Come risultato, averemo un codice di evidenziazione veloce ede efficiente, indipendente dal numero di `<td>` nella tabella.
/done

2021-02-06 20:42 UTC, longo-andrea requested changes

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +Nel gestore avremo a disposizione `event.target` per controllare l'elemento dal quale sia partito l'evento e poterlo quindi gestire di conseguenza.
```suggestion
Nel gestore avremo a disposizione `event.target` per controllare l'elemento dal quale è partito l'evento e poterlo quindi gestire di conseguenza.
```

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +Invece di assegnare un gestore all'`onclick` per ogni `<td>` (potrebbero essercene tantissime) -- andiamo a impostare un gestore del tipo "catturali tutti" sull'elemento `<table>`.
non mi convince tantissimo questa sezione, piccolo suggerimento
```suggestion
Invece di assegnare un gestore all'`onclick` per ogni `<td>` (potrebbero essercene tantissime) -- andiamo a impostare un gestore che sarà in grado di "catturali tutti" sull'elemento `<table>`.
```

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +3. Ne caso di tabelle annidate, `event.target` potrebbe essere un `<td>`, ma fuori dalla tabelle corrente. Quindi andiamo a controllare se sia il `<td>` della *nostra tabella*.
```suggestion
3. Nel caso di tabelle annidate, `event.target` potrebbe essere un `<td>`, ma fuori dalla tabelle corrente. Quindi andiamo a controllare se sia il `<td>` della *nostra tabella*.
```

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +3. Ne caso di tabelle annidate, `event.target` potrebbe essere un `<td>`, ma fuori dalla tabelle corrente. Quindi andiamo a controllare se sia il `<td>` della *nostra tabella*.
```suggestion
3. Ne caso di tabelle annidate, `event.target` potrebbe riferirsi ad `<td>`, ma fuori dalla tabelle corrente. Quindi andiamo a controllare se `<td>`  appartiene alla *nostra tabella*.
```

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +### Comportamento: contator
```suggestion
### Comportamento: contatore
```

2021-02-06 20:42 UTC, longo-andrea commented on 2-ui/2-events/03-event-delegation/article.md
> +Questo può essere davvero conveniente -- nessuna necessità di scrivere codice JavaScript per ogni nuovo elemento di questo genere. Basta solo usare il comportamento. Il gestore a livello di documento
```suggestion
Questo può essere davvero conveniente -- nessuna necessità di scrivere codice JavaScript per ogni nuovo elemento di questo genere. Ci basta solo applicare il comportamento. Il gestore a livello di documento fa in modo che funzioni per ogni elemento nella pagina.
```

2021-02-06 22:07 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Invece di assegnare un gestore all'`onclick` per ogni `<td>` (potrebbero essercene tantissime) -- andiamo a impostare un gestore del tipo "catturali tutti" sull'elemento `<table>`.
no, ma ok.

2021-02-06 22:08 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +3. Ne caso di tabelle annidate, `event.target` potrebbe essere un `<td>`, ma fuori dalla tabelle corrente. Quindi andiamo a controllare se sia il `<td>` della *nostra tabella*.
/done

2021-02-06 22:08 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Nel gestore avremo a disposizione `event.target` per controllare l'elemento dal quale sia partito l'evento e poterlo quindi gestire di conseguenza.
/done

2021-02-06 22:08 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Invece di assegnare un gestore all'`onclick` per ogni `<td>` (potrebbero essercene tantissime) -- andiamo a impostare un gestore del tipo "catturali tutti" sull'elemento `<table>`.
/done

2021-02-07 10:18 UTC, longo-andrea commented
/done

2021-02-07 13:45 UTC, longo-andrea commented
Gli esercizi tradotti sono nella PR #205

2021-02-09 18:42 UTC, pasor1 approved these changes
Qualche pioccola nota

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +Il concetto alla base è che se abbiamo una serie di elementi gestiti in maniera simile, allora invece di assegnare un gestore per ognuno di essi, possiamo metterne uno solo sui loro antenati comuni.
```suggestion
Il concetto di base è che se abbiamo una serie di elementi gestiti in maniera simile, allora, invece di assegnare un gestore per ognuno di essi, possiamo metterne uno solo sui loro antenati comuni.
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +Poniamo il caso che volessimo fare un menù con i pulsanti "Save", "Load", "Search" e cosi via, e che via sia un oggetto con i metodi `save`, `load`, `search`... Come potremmo distinguerli?
```suggestion
Poniamo il caso che volessimo fare un menù con i pulsanti "Save", "Load", "Search" e cosi via, e che vi sia un oggetto con i metodi `save`, `load`, `search`... Come potremmo distinguerli?
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +Nota bene che `this.onClick` è collegato a `this` nel punto `(*)`.  Questo è importante, altrimenti `this` potrebbe riferirsi all'elemento del DOM (`elem`), e non l'oggetto `Menu`, di conseguenza `th
```suggestion
Nota bene che `this.onClick` è collegato a `this` nel punto `(*)`.  Questo è importante, altrimenti `this` si riferirebbe all'elemento del DOM (`elem`), e non l'oggetto `Menu`, di conseguenza `this[action]` non farebbe quello di cui abbiamo bisogno.
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +2. Un gestore su tutto il documento tiene traccia degli eventi, e se viene scaturito un evento su un elemento con l'attributo -- esegue l'azione.
```suggestion
2. Un gestore su tutto il documento tiene traccia degli eventi, e se viene attivato un evento su un elemento con quell'attributo -- esegue l'azione.
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +Per esempio, qui l'attributo `data-counter` aggiunge un comportamento: "aumenta il valore al click" sui pulsanti:
```suggestion
Per esempio, qui l'attributo `data-counter` aggiunge un comportamento: "incrementa il valore al click" sui pulsanti:
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +```warn header="Pe gestori a livello di documento -- usare sempre `addEventListener`"
```suggestion
```warn header="Per gestori a livello di documento -- usare sempre `addEventListener`"
```

2021-02-09 18:42 UTC, pasor1 commented on 2-ui/2-events/03-event-delegation/article.md
> +Quando assegniamo un gestore di eventi all'oggetto `document`, dovremmo sempre usare `addEventListener`, e non `document.on<event>`, perché il secondo causerebbe conflitti: dei nuovi gestori sovrascr
```suggestion
Quando assegniamo un gestore di eventi all'oggetto `document`, dovremmo sempre usare `addEventListener`, e non `document.on<event>`, perché il secondo causerebbe conflitti: i nuovi gestori sovrascriverebbero i precedenti.
```

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Il concetto alla base è che se abbiamo una serie di elementi gestiti in maniera simile, allora invece di assegnare un gestore per ognuno di essi, possiamo metterne uno solo sui loro antenati comuni.
/done

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Poniamo il caso che volessimo fare un menù con i pulsanti "Save", "Load", "Search" e cosi via, e che via sia un oggetto con i metodi `save`, `load`, `search`... Come potremmo distinguerli?
/done

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Nota bene che `this.onClick` è collegato a `this` nel punto `(*)`.  Questo è importante, altrimenti `this` potrebbe riferirsi all'elemento del DOM (`elem`), e non l'oggetto `Menu`, di conseguenza `th
/done

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +2. Un gestore su tutto il documento tiene traccia degli eventi, e se viene scaturito un evento su un elemento con l'attributo -- esegue l'azione.
/done

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Per esempio, qui l'attributo `data-counter` aggiunge un comportamento: "aumenta il valore al click" sui pulsanti:
/done

2021-02-09 19:10 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +```warn header="Pe gestori a livello di documento -- usare sempre `addEventListener`"
/done

2021-02-09 19:11 UTC, pierangelomiceli commented on 2-ui/2-events/03-event-delegation/article.md
> +Quando assegniamo un gestore di eventi all'oggetto `document`, dovremmo sempre usare `addEventListener`, e non `document.on<event>`, perché il secondo causerebbe conflitti: dei nuovi gestori sovrascr
/done

2021-02-09 19:41 UTC, longo-andrea approved these changes

2021-02-09 19:41 UTC, merged