Prototypal inheritance
javascript-tutorial/it.javascript.info pull request #207
Opened 2021-02-07 17:23 UTC by longo-andrea

2021-02-08 07:45 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
> +2. Nei moderni engine, che valutano le performance, non c'è alcuna differenza tra il prelevare una proprietà dall'oggetto oppure direttamente dal suo prototype. Sono in grado di ricordare da dove è s
```suggestion
2. Nei moderni engine, che valutano la performance, non c'è alcuna differenza tra il prelevare una proprietà dall'oggetto oppure direttamente dal suo prototype. Sono in grado di ricordare da dove è stata presa la proprietà e riutilizzarla alla prossima richiesta.
```
lascerei performance al singolare

2021-02-08 07:46 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/2-search-algorithm/solution.md
> +    Ad esempio, per `pockets.glasses` loro ricordano dove hanno trovato `glasses` (in `head`), quindi la prossima volta la cercheranno proprio li. Sono anche abbastanza intelligenti da aggiornare la
```suggestion
    Ad esempio, per `pockets.glasses`  ricordano dove hanno trovato `glasses` (in `head`), quindi la prossima volta la cercheranno proprio li. Sono anche abbastanza intelligenti da aggiornare la cache interna nel caso qualcosa cambi, quindi questa ottimizzazione è sicura.
```
Il 'loro' e' superfluo, si capisce il soggetto della frase

2021-02-08 07:48 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/3-proto-and-this/solution.md
> +Questo accade perché `this` fa riferimento all'oggetto prima del punto, quindi `rabbit.eat()` modifica `rabbit`.
```suggestion
Questo perché `this` fa riferimento all'oggetto prima del punto, quindi `rabbit.eat()` modifica `rabbit`.
```

2021-02-08 07:49 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
> +Guardiamo attentamente a cosa succende nella chiamata `speedy.eat("apple")`.
```suggestion
Guardiamo attentamente cosa succede nella chiamata `speedy.eat("apple")`.
```

2021-02-08 07:50 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/solution.md
> +Una soluzione comune, tutte le proprietà che descrivono un particolare stato dell'oggetto, come `stomach`, dovrebbero essere memorizzate nell'oggetto. In questo modo eviteremo il problema.
```suggestion
Come soluzione comune, tutte le proprietà che descrivono un particolare stato dell'oggetto, come `stomach`, dovrebbero essere memorizzate nell'oggetto. In questo modo eviteremo il problema.
```

2021-02-08 07:51 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
> +# Perché entrabi i criceti sono sazi?
```suggestion
# Perché entrambi i criceti sono sazi?
```

2021-02-08 07:51 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/4-hamster-proto/task.md
> +Quando nutriamo uno di loro, anche l'altro è sazio. Perché? Come possiamo sistemare?
```suggestion
Quando nutriamo uno di loro, anche l'altro è sazio. Perché? Come possiamo sistemare il problema?
```

2021-02-08 08:02 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Nella programmazione, spesso vogliamo prendere qualcosa ed estenderlo.
```suggestion
Nella programmazione, spesso vogliamo prendere qualcosa ed estenderla.
```

2021-02-08 08:04 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +In JavaScript, possiedono una speciale proprietà nascosta `[[Prototype]]` (come definito nella specifica), questo può valere `null` oppure può contenere il riferimento ad un altro oggetto. Quell'ogge
```suggestion
In JavaScript, gli oggetti possiedono una speciale proprietà nascosta `[[Prototype]]` (come definito nella specifica); questo può valere `null` oppure può contenere il riferimento ad un altro oggetto. Quell'oggetto viene definito "prototype" (prototipo):
```

2021-02-08 08:04 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Quando leggiamo una proprietà da `object`, e questa non esiste, JavaScript prova automaticamente a recuperarla dal suo prototype. In programmazione, questo comportamento viene definito "prototypal in
```suggestion
Quando leggiamo una proprietà da `object`, e questa non esiste, JavaScript prova automaticamente a recuperarla dal suo prototype. In programmazione, questo comportamento viene definito "prototypal inheritance". Presto vederemo diversi esempi di questo tipo di ereditarietà, e vedremo anche delle interessanti caratteristiche del linguaggio basate su di essa. 
```

2021-02-08 08:05 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Uno di questi è quello di utilizzare la nomenclatura speciale `__proto__`, in questo modo:
```suggestion
Uno di questi è quello di utilizzare la nomenclatura speciale `__proto__`:
```
toglierei l'ultima parte, che ne dici?

2021-02-08 08:05 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +rabbit.__proto__ = animal; // imposta il prototy di rabbit,.[[Prototype]] = animal
```suggestion
rabbit.__proto__ = animal; // imposta il prototype di rabbit,.[[Prototype]] = animal
```

2021-02-08 08:07 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +In questo caso possiamo dire che "`animal` è il prototype di `rabbit`" o, in alternativa, che "`rabbit` prototypically inherits (eredità dal prototipo) da `animal`"
```suggestion
In questo caso possiamo dire che "`animal` è il prototype di `rabbit`" o, in alternativa, che "`rabbit` *prototypically inherits* (eredità dal prototipo) da `animal`"
```
In questo caso il corsivo ci sta :)

2021-02-08 08:08 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +2. Il valore di `__proto__` può essere o un oggetto o `null`. Gli altri valore vengono ignorati.
```suggestion
2. Il valore di `__proto__` può essere o un oggetto o `null`. Gli altri valori vengono ignorati.
```

2021-02-08 08:09 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Inoltre, anche se dovrebbe essere già ovvio: può esserci solamente un `[[Prototype]]`. Un oggetto non può eridatare da più oggetti.
```suggestion
Inoltre, anche se dovrebbe essere già ovvio: può esserci solamente un `[[Prototype]]`. Un oggetto non può ereditare da più oggetti.
```

2021-02-08 08:11 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Poichè la notazione `__proto__` risulta essere più intuitiva, la utilizzeremo nei nostri esempi.
```suggestion
Poichpoiché la notazione `__proto__` risulta essere più intuitiva, la utilizzeremo nei nostri esempi.
```

2021-02-08 08:12 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Nell'esempio che vediamo sotto, assegniamo un suo metodo `walk` a `rabbit`:
```suggestion
Nell'esempio che vediamo sotto, assegniamo un metodo `walk` a `rabbit`, che sarà solo suo:
```
Mi sembra piu' chiaro cosi', che ne pensi?

2021-02-08 08:14 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Nell'esempio in linea `(*)` la proprietà `admin.fullName` possiede un getter nel prototype `user`, quindi viene invocato. In linea `(**)` la proprietà ha un setter nel prototype, che viene quindi inv
```suggestion
Nell'esempio in linea `(*)` la proprietà `admin.fullName` ha un getter nel prototype `user`, quindi viene invocato. In linea `(**)` la proprietà ha un setter nel prototype, che viene quindi invocato.
```
Metterei un piu' sobrio *ha*. Che ne pensi?

2021-02-08 08:14 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Dall'esempio sopra potrebbe sorgere una domanda interessante: qual'è il valore di `this` all'interno `set fullName(value)`? Dove vengono scritte le proprietà `this.name` e `this.surname`: in `user` o
```suggestion
Dall'esempio sopra potrebbe sorgere una domanda interessante: qual è il valore di `this` all'interno `set fullName(value)`? Dove vengono scritte le proprietà `this.name` e `this.surname`: in `user` o `admin`?
```

2021-02-08 08:15 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +**Non ha importanza dove viene trovato il metodo: nell'oggetto o in un suo prototupe. Quando invochiamo un metodo, `this` fa sempre riferimento all'oggetto che precede il punto.**
```suggestion
**Non ha importanza dove viene trovato il metodo: nell'oggetto o in un suo prototype. Quando invochiamo un metodo, `this` fa sempre riferimento all'oggetto che precede il punto.**
```

2021-02-08 08:15 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Questo è molto importante, poiché potremmo avere un oggetto molto grande con molti metodi, e avere diversi oggetti che ereditano da esso. Quando gli oggetti che ereditano, eseguono un metodo ereditat
```suggestion
Questo è molto importante, poiché potremmo avere un oggetto molto grande con molti metodi, e avere diversi oggetti che ereditano da esso. Quando gli oggetti che ereditano eseguono un metodo ereditato, andranno a modificare solamente il loro stato, non quello dell'oggetto principale.
```

2021-02-08 08:17 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Ad esempio, qui `animal` rappresenta un "memorizzato di metodi", che `rabbit` utilizza.
```suggestion
Ad esempio, qui `animal` rappresenta un "archivio di metodi", che `rabbit` utilizza.
```

2021-02-08 08:18 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Se avessimo altri oggetti, come `bird`, `snake`, etc., che ereditano da `animal`, avrebbero a loro volta accesso ai metodi di `animal`. In ogni caso, `this` all'interno della chiamata, farebbere rife
```suggestion
Se avessimo altri oggetti, come `bird`, `snake`, etc., che ereditano da `animal`, avrebbero a loro volta accesso ai metodi di `animal`. In ogni caso, `this` all'interno della chiamata farebbe riferimento all'oggetto corrispondente, che viene valutato al momento dell'invocazione (appena prima del punto), e non ad `animal`. Quindi quando scriviamo dati utilizzando `this`, questi verranno memorizzati nell'oggetto corrispondente.
```

2021-02-08 08:18 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Come risultato otteniamo che dei metodi condivisi, mentre lo stato degli oggetti non lo è.
```suggestion
Come risultato i metodi sono condivisi, mentre lo stato degli oggetti non lo è.
```

2021-02-08 08:19 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +// il ciclo for..in itera sia le proprietà di rabbi, che quelle ereditate da animal
```suggestion
// il ciclo for..in itera sia le proprietà di rabbit, che quelle ereditate da animal
```

2021-02-08 08:20 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Se questo non è ciò che ci aspettiamo, e voglia escludere le proprietà ereditate, esiste un metodo integrato [obj.hasOwnProperty(key)](mdn:js/Object/hasOwnProperty): ritorna `true` se `obj` possiede
```suggestion
Se questo non è ciò che ci aspettiamo, e voglia escludere le proprietà ereditate, esiste un metodo integrato [obj.hasOwnProperty(key)](mdn:js/Object/hasOwnProperty): ritorna `true` se `obj` possiede la propria proprietà `key`  (non ereditata).
```

2021-02-08 08:20 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Quindi possiamo filtrare le proprietà ereditate (o farci qualcos altro):
```suggestion
Quindi possiamo filtrare le proprietà ereditate (o farci qualcos'altro):
```

2021-02-08 08:22 UTC, Dorin-David commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +- Le operazioni di scrittrua/rimozione agiscono direttamente nell'oggetto, non utilizzano il prototype (assumendo che questa sia una proprietà e non un setter).
```suggestion
- Le operazioni di scrittura/rimozione agiscono direttamente sull'oggetto, non utilizzano il prototype (assumendo che questa sia una proprietà e non un setter).
```

2021-02-08 08:23 UTC, Dorin-David requested changes
Ho proposto alcune piccole modifiche. Per il resto, gran traduzione!

2021-02-10 19:45 UTC, pasor1 approved these changes
solo qualche piccola correzione

2021-02-10 19:45 UTC, pasor1 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +1. Non possono esserci riferimenti circolari. JavaScript lancerebbe un errore se provassimo ad assegnare a `__proto__` un riferimento circolare.
```suggestion
1. Non possono esserci riferimenti circolari. JavaScript restituirebbe un errore se provassimo ad assegnare a `__proto__` un riferimento circolare.
```

2021-02-10 19:45 UTC, pasor1 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Da notare che `__proto__` non è *la stessa cosa* della proprietà `[[Prototype]]`. E' solamente un getter/setter per `[[Prototype]]`. Più avanti vedremo alcune situazioni in cui questa differenza avrà
```suggestion
Da notare che `__proto__` non è *la stessa cosa* della proprietà `[[Prototype]]`. E' solamente un getter/setter per `[[Prototype]]`. Più avanti vedremo alcune situazioni in cui questa differenza avrà importanza, ma per ora tenetelo solo a mente.
```

2021-02-10 19:45 UTC, pasor1 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Nell'esempio in linea `(*)` la proprietà `admin.fullName` ha un getter nel prototype `user`, quindi viene invocato. In linea `(**)` la proprietà ha un setter nel prototype, che viene quindi invocato.
```suggestion
Nell'esempio, alla linea `(*)` la proprietà `admin.fullName` ha un getter nel prototype `user`, quindi viene invocato. E alla linea `(**)` la proprietà ha un setter nel prototype, che viene quindi invocato.
```

2021-02-10 19:45 UTC, pasor1 commented on 1-js/08-prototypes/01-prototype-inheritance/article.md
> +Se questo non è ciò che ci aspettiamo, e voglia escludere le proprietà ereditate, esiste un metodo integrato [obj.hasOwnProperty(key)](mdn:js/Object/hasOwnProperty): ritorna `true` se `obj` possiede
```suggestion
Se questo non è ciò che ci aspettiamo, e vogliamo escludere le proprietà ereditate, esiste un metodo integrato [obj.hasOwnProperty(key)](mdn:js/Object/hasOwnProperty): ritorna `true` se `obj` possiede la propria proprietà `key` (non ereditata).
```

2021-02-11 20:38 UTC, merged