Moving the mouse: mouseover/out, mouseenter/leave
javascript-tutorial/it.javascript.info pull request #232
Opened 2021-02-24 01:42 UTC by pierangelomiceli

2021-02-26 20:46 UTC, longo-andrea requested changes
@pierangelomiceli ti ho lasciato un paio di commenti, parecchi sono riguardo il termine "il tooltip" che io sono abituato a chiamare "la tooltip", comunque parliamone, in caso puoi ignorarli... un'altra cosa che manca è la traduzione dei commenti nel file script.js.. il resto tutto okay 👍

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +# Spostando il mouse: mouseover/out, mouseenter/leave
so che non è una traduzione letterale, ma io proporrei:
```suggestion
# Movimenti del mouse: mouseover/out, mouseenter/leave
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Proviamo a spostare il cursore dentro e fuori dalla celle della tabella ed anche al loro interno. Velocemente o lentamente -- è irrilevante. Solo l'intero `<td>` deve essere evindenziato, diversament
```suggestion
Proviamo a spostare il cursore dentro e fuori dalla celle della tabella ed anche al loro interno. Velocemente o lentamente -- è irrilevante. Solo l'intero `<td>` deve essere evidenziato, diversamente da quanto fatto nell'esempio precedente.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +L'evento `mouseover` si genera quando il puntatore del mouse passa su un elemento, e `mouseout` -- quando lo abbandona.
```suggestion
L'evento `mouseover` viene generato quando il puntatore del mouse passa su un elemento, e `mouseout` -- quando lo abbandona.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Nel seguente esempio, ogni faccia e le sue proprietà sono elementi separati. Al movimento il mouse, corrispondono degli eventi che vengono descritti nell'area di testo.
```suggestion
Nel seguente esempio, ogni faccia e le sue proprietà sono elementi separati. Muovendo il mouse, vedrete apparire gli eventi corrispondenti all'interno dell'area di testo.
```
oppure

```suggestion
Nel seguente esempio, ogni faccia e le sue proprietà sono elementi separati. Al movimento del mouse, corrispondono degli eventi che vengono descritti nell'area di testo.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Questo HTML ha due elementi nidificati: un `<div id="child">` dentro un `<div id="parent">`. Muovendo il mouse velocemente su di loro, potrebbe accedere che l'evento venga generato solo dal div figli
```suggestion
Questo HTML ha due elementi nidificati: un `<div id="child">` dentro un `<div id="parent">`. Muovendo il mouse velocemente su di loro, potrebbe accadere che l'evento venga generato solo dal div figlio, o magari solo dal genitore, oppure ancora, potrebbe non esserci alcun evento.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +**Coerentemente con la logica del browser, il puntatore del mouse può stare sopra su un *solo* elemento per volta -- il più annidato e con il valore di z-index più alto.**
```suggestion
**Coerentemente con la logica del browser, il puntatore del mouse può stare sopra un *solo* elemento per volta -- il più annidato e con il valore di z-index più alto.**
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +L'esempio seguente è simile al precedente, solo che adesso l'elemento superiore è associato a  `mouseenter/mouseleave` piuttosto che `mouseover/mouseout`.
```suggestion
L'esempio seguente è simile al precedente, solo che in questo caso l'elemento superiore è associato a  `mouseenter/mouseleave` piuttosto che `mouseover/mouseout`.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +La soluzione più naturale sarebbe quella di -- impostare un gestore su `<table>` per elaborare lì gli eventi. Ma il problema è che `mouseenter/leave` non fanno bubbling. Quindi se questi eventi avven
```suggestion
La soluzione più naturale sarebbe quella di -- impostare un gestore su `<table>` per elaborare lì gli eventi. Ma il problema è che `mouseenter/leave` non fanno bubbling. Quindi se questi eventi avvengono su `<td>`, solo un gestore su `<td>` potrà catturarli.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +I gestori per `mouseenter/leave` sulla `<table>` verrebbero generati solo il puntatore entrasse ed uscisse dalla tabella, e sarebbe impossibile ottenere informazioni sugli spostamento al suo interno.
```suggestion
I gestori per `mouseenter/leave` sulla `<table>` verrebbero generati solo se il puntatore entrasse ed uscisse dalla tabella, e sarebbe impossibile ottenere informazioni sugli spostamenti al suo interno.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
> +Scrivere del codice JavaScript che mostri un tooltip su un elemento con un attributo `data-tooltip`. Il valore di questo attributo dovrebbe rappresentare il testo del tooltip.
```suggestion
Scrivere del codice JavaScript che mostri una tooltip su un elemento con un attributo `data-tooltip`. Il valore di questo attributo dovrebbe rappresentare il testo del tooltip.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
> +Questo compito è come quello di <info:task/behavior-tooltip>, con la differenza che qui gli elementi delle annotazioni possono essere annidati. Deve essere mostrato il tooltip più annidato.
```suggestion
Questo compito è come quello di <info:task/behavior-tooltip>, con la differenza che qui gli elementi delle annotazioni possono essere annidati. Deve essere mostrata la tooltip più annidata.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/1-behavior-nested-tooltip/task.md
> +Può essere mostrato solo un tooltip alla volta.
```suggestion
Può essere mostrato solo una tooltip alla volta.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
> +P.S.: Nota bene: i test della soluzione fanno uso di `dispatchEvent` per vedere se il tooltip funziona bene.
```suggestion
P.S.: Nota bene: i test della soluzione fanno uso di `dispatchEvent` per vedere se la tooltip funziona bene.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/solution.md
> +P.S.: Nota bene: i test della soluzione fanno uso di `dispatchEvent` per vedere se il tooltip funziona bene.
```suggestion
P.S.: Nota bene: i test della soluzione fanno uso di `dispatchEvent` per vedere se la tooltip funziona bene.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
> +In altre parole, se il visitatore sposta il mouse su questo elemento e si ferma lì -- mostra il tooltip. Se invece ha solo spostato il mouse passandoci sopra, non ce n'è bisogno, d'altronde chi mai v
```suggestion
In altre parole, se il visitatore sposta il mouse su questo elemento e si ferma lì -- mostra la tooltip. Se invece ha solo spostato il mouse passandoci sopra, non ce n'è bisogno, d'altronde chi mai vorrebbe altri elementi lampeggianti non desiderati?
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
> +Tecnicamente, possiamo misurare la velocità del mouse su un elemento, e se è abbastanza lento possiamo supporre che sta arrivando proprio "sull'elemento", mostrando il tooltip, se è troppo veloce --
```suggestion
Tecnicamente, possiamo misurare la velocità del mouse su un elemento, e se è abbastanza lento possiamo supporre che sta arrivando proprio "sull'elemento", mostrando la tooltip, se è troppo veloce -- lo ignoriamo.
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
> +Ecco un esempio dell'uso di questo oggetto per il tooltip:
```suggestion
Ecco un esempio dell'uso di questo oggetto per la tooltip:
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
> +// un tooltip di esempio
```suggestion
// una tooltip di esempio
```

2021-02-26 20:46 UTC, longo-andrea commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/2-hoverintent/task.md
> +Nota bene: il tooltip non "lampeggia" quando il cursore si muove tra i sottoelementi dell'orologio.
```suggestion
Nota bene: la tooltip non "lampeggia" quando il cursore si muove tra i sottoelementi dell'orologio.
```

2021-02-26 21:55 UTC, pierangelomiceli commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +# Spostando il mouse: mouseover/out, mouseenter/leave
/done

2021-02-26 21:55 UTC, pierangelomiceli commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Proviamo a spostare il cursore dentro e fuori dalla celle della tabella ed anche al loro interno. Velocemente o lentamente -- è irrilevante. Solo l'intero `<td>` deve essere evindenziato, diversament
/done

2021-02-26 21:55 UTC, pierangelomiceli commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +L'evento `mouseover` si genera quando il puntatore del mouse passa su un elemento, e `mouseout` -- quando lo abbandona.
/done

2021-02-26 21:55 UTC, pierangelomiceli commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Nel seguente esempio, ogni faccia e le sue proprietà sono elementi separati. Al movimento il mouse, corrispondono degli eventi che vengono descritti nell'area di testo.
/done

2021-02-27 11:21 UTC, longo-andrea approved these changes

2021-03-01 17:40 UTC, pasor1 approved these changes
Un po' di correzioni, da rompiballe quale sono :-D

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +L'evento `mousemove` viene scaturito col movimento del mouse. Tuttavia, ciò non significa che ogni pixel porterà ad un evento.
```suggestion
L'evento `mousemove` viene attivato dal movimento del mouse. Tuttavia, ciò non significa che ogni pixel porterà ad un evento.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Possiamo testare dal "vivo" il concetto, nel seguente banco di test.
```suggestion
Possiamo testare dal "vivo" il concetto, nel seguente banco di prova.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Se vi fossero alcune azioni a seguito di eventi, che coinvolgessero l'abbandono dell'elemento genitore, ad esempio un'animazione eseguita al `parent.onmouseout`, nella maggioranza dei casi non vorrem
Mi sembra un po' incasinata  questa frase ...

```suggestion
Se vi fossero degli eventi generati dall'abbandono dell'elemento genitore, ad esempio un'animazione eseguita al `parent.onmouseout`, nella maggioranza dei casi non vorremmo che si attivassero se il puntatore entrasse in profondità nel `#parent` andando dentro il figlio (anzi, in generale vorremmo che si attivassero solo quando il puntatore va all'esterno dell'area del `#parent`).
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Gli eventi `mouseenter/mouseleave` si comportano come `mouseover/mouseout`. Vengono scaturiti quando il puntatore del mouse entra/lascia l'elemento.
```suggestion
Gli eventi `mouseenter/mouseleave` si comportano come `mouseover/mouseout`. Vengono attivati quando il puntatore del mouse entra/lascia l'elemento.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +L'esempio seguente è simile al precedente, solo che in questo caso l'elemento superiore è associato a  `mouseenter/mouseleave` piuttosto che `mouseover/mouseout`.
```suggestion
L'esempio seguente è simile al precedente, solo che in questo caso l'elemento superiore è associato a `mouseenter/mouseleave` piuttosto che `mouseover/mouseout`.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Come possiamo notare, gli unici venti generati sono quelli relativi al movimento del puntatore del mouse dentro e fuori dall'elemento superiore. Se il puntatore va dentro l'elemento figlio, non succe
```suggestion
Come possiamo notare, gli unici eventi generati sono quelli relativi al movimento del puntatore del mouse dentro e fuori dall'elemento superiore. Se il puntatore va dentro l'elemento figlio, non succede nulla. Le transizioni tra i figli vengono ignorate.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +1. Usare la event delegation per gestire l'entrata/uscita dai `<td>` dentro la tabella. Quindi usare `mouseover/out` piuttosto che `mouseenter/leave`, in quanto questi ultimi non facendo bubbling,  n
```suggestion
1. Usare la event delegation per gestire l'entrata/uscita dai `<td>` dentro la tabella. Quindi usare `mouseover/out` piuttosto che `mouseenter/leave`, in quanto questi ultimi, non facendo bubbling,  non permetterebbero la event delegation.
```

2021-03-01 17:40 UTC, pasor1 commented on 2-ui/3-event-details/3-mousemove-mouseover-mouseout-mouseenter-mouseleave/article.md
> +Gli eventi `mouseenter/leave` sono differenti da questo punto di vista: vengono scaturiti solo quando il mouse entra o esce del tutto da un elemento. Inoltre non sono soggetti al bubbling.
```suggestion
Gli eventi `mouseenter/leave` sono differenti da questo punto di vista: vengono attivati solo quando il mouse entra o esce del tutto da un elemento. Inoltre non sono soggetti al bubbling.
```

2021-03-02 19:38 UTC, closed without merging