Extending built-in classes
javascript-tutorial/it.javascript.info pull request #237
Opened 2021-03-02 20:19 UTC by longo-andrea

2021-03-05 11:35 UTC, Dorin-David commented on 1-js/09-classes/05-extend-natives/article.md
> +Notiamo una cosa interessante. I metodi built-in come like `filter`, `map` e cosi via -- ritornano nuovi esattamente del nuovo tipo ereditato, cioè `PowerArray`. La loro implementazione interna utili
```suggestion
Notiamo una cosa interessante. I metodi built-in come `filter`, `map` e così via -- ritornano nuovi oggetti del tipo ereditato, cioè `PowerArray`. La loro implementazione interna utilizzata il `costruttore` per farlo.
```

2021-03-05 11:36 UTC, Dorin-David commented on 1-js/09-classes/05-extend-natives/article.md
> +Possiamo aggiungre uno speciale getter statico `Symbol.species` alla classe. Questo dovrebbe ritornare il costruttore utilizzerà internamente per creare le nuove entità in  `map`, `filter` e gli altr
```suggestion
Possiamo aggiungere uno speciale getter statico `Symbol.species` alla classe. Questo dovrebbe ritornare il costruttore che Javascript utilizzerà internamente per creare le nuove entità in  `map`, `filter` e gli altri metodi.
```

2021-03-05 11:37 UTC, Dorin-David commented on 1-js/09-classes/05-extend-natives/article.md
> +Se invece, la nostra intenzione è quella di restituire degli array standard tramite l'utilizzo dei metodi come `map` o `filter`, possiamo ritornare `Array` in `Symbol.species`, come nell'esempio:
```suggestion
Se, invece, la nostra intenzione è quella di restituire degli array standard tramite l'utilizzo dei metodi come `map` o `filter`, possiamo ritornare `Array` in `Symbol.species`, come nell'esempio:
```
Una bella virgoletta in piu' :P

2021-03-05 11:39 UTC, Dorin-David commented on 1-js/09-classes/05-extend-natives/article.md
> +Ma le classi built-in fanno eccezione. Queste infatti, non ereditano i membri statici a vicenda.
```suggestion
Ma le classi built-in fanno eccezione. Queste, infatti, non ereditano i membri statici a vicenda.
```
altra virgoletta :P

2021-03-05 11:40 UTC, Dorin-David requested changes
alcune piccole correzioni

2021-03-05 12:49 UTC, longo-andrea commented
/done

2021-03-07 12:46 UTC, pasor1 approved these changes

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Notiamo una cosa interessante. I metodi built-in come `filter`, `map` e così via -- ritornano nuovi oggetti del tipo ereditato, cioè `PowerArray`. La loro implementazione interna utilizzata il `costr
```suggestion
Notiamo una cosa interessante. I metodi built-in come `filter`, `map` e così via, ritornano nuovi oggetti del tipo ereditato, cioè `PowerArray`. La loro implementazione interna utilizzata la proprietà oggetto `constructor` per farlo.
```

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Quando invochiamo `arr.filter()`, questo creerà internamente il nuovo array contenente i risultati utilizzando `arr.constructor`, non l'`Array` standard. Questo è molto utile, poiché possiamo continu
```suggestion
Quando invochiamo `arr.filter()`, questo creerà internamente il nuovo array contenente i risultati utilizzando `arr.constructor`, non l'oggetto `Array` standard. Questo è molto utile, poiché possiamo continuare ad utilizzare i metodi di `PowerArray` anche dopo aver ottenuto il risultato.
```

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Ancora meglio, possiamo personalizzarne il comportamento.
```suggestion
Inoltre, possiamo personalizzarne il comportamento.
```

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Possiamo aggiungere uno speciale getter statico `Symbol.species` alla classe. Questo dovrebbe ritornare il costruttore che Javascript utilizzerà internamente per creare le nuove entità in  `map`, `fi
```suggestion
Possiamo aggiungere uno speciale getter statico `Symbol.species` alla classe. Questo dovrebbe ritornare il costruttore che Javascript utilizzerà internamente per creare le nuove entità in  `map`, `filter` e così via.
```

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Se, invece, la nostra intenzione è quella di restituire degli array standard tramite l'utilizzo dei metodi come `map` o `filter`, possiamo ritornare `Array` in `Symbol.species`, come nell'esempio:
```suggestion
Se, ad esempio, volessimo che metodi come `map` o `filter` restituiscano un array standard, possiamo ritornare `Array` in `Symbol.species`, come nell'esempio:
```

2021-03-07 12:46 UTC, pasor1 commented on 1-js/09-classes/05-extend-natives/article.md
> +Ma le classi built-in fanno eccezione. Queste, infatti, non ereditano i membri statici a vicenda.
```suggestion
Ma le classi built-in fanno eccezione. Queste, infatti, non ereditano i membri statici a le une dalle altre.
```

2021-03-07 14:54 UTC, merged