Private and protected properties and method
javascript-tutorial/it.javascript.info pull request #240
Opened 2021-03-05 21:29 UTC by longo-andrea

2021-03-06 18:05 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Solitamente, i dispositivi che utilizziamo sono piuttosto complessi. Ma poter delimitare la loro interfaccia interna da quelal esterna, ci consente di utilizzarli senza grossi problemi.
```suggestion
Solitamente, i dispositivi che utilizziamo sono piuttosto complessi. Poter delimitare la loro interfaccia interna da quella esterna, ci consente di utilizzarli senza grossi problemi.
```

2021-03-06 18:05 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +## Un esempio nel mondo reale
```suggestion
## Un esempio del mondo reale
```

2021-03-06 18:07 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ad esempio, una macchina del caffe. Semplice all'esterno: un bottone, un dispaly, un paio di fori... E, ovviamente, il risultato -- un ottimo caffe! :)
```suggestion
Ad esempio, una macchina del caffè. Semplice all'esterno: un bottone, un dispaly, un paio di fori... E, ovviamente, il risultato -- un ottimo caffè! :)
```

2021-03-06 18:10 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Le macchine del caffe sono piuttosto affidabili, giusto? Possono durare per anni, e solamente nel caso in cui qualcosa smetta di funzionare -- la portiamo a riparare.
```suggestion
Le macchine del caffè sono piuttosto affidabili, giusto? Possono durare per anni, e solamente nel caso in cui qualcosa smetta di funzionare -- le portiamo a riparare.
```

2021-03-06 18:10 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Il segreto dietro all'affidabilità e alla semplicità di una macchina del caffe -- tutti i dettagli sono ottimizzati e *nascosti*.
```suggestion
Il segreto dietro all'affidabilità e alla semplicità di una macchina del caffè -- tutti i dettagli sono ottimizzati e *nascosti*.
```

2021-03-06 18:11 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Se rimuovessimo la copertura della macchina del caffe, allora il suo utilizzo sarebbe molto più complesso (dove dovremmo premere?), e pericoloso (potremmo prendere la scossa).
```suggestion
Se rimuovessimo la copertura della macchina del caffè, allora il suo utilizzo sarebbe molto più complesso (dove dovremmo premere?), e pericoloso (potremmo prendere la scossa).
```

2021-03-06 18:11 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Come vedremo in seguito, nella programmazione, gli oggetti, sono come le macchine del caffe.
```suggestion
Come vedremo in seguito, nella programmazione gli oggetti sono come le macchine del caffè.
```

2021-03-06 18:12 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ma per poter nascondere i loro dettagli interni, non utilizzeremo una copertura di sicurezza, ma piuttosto un speciale sintassi del linguaggio ed alcune convenzioni.
```suggestion
Ma per poter nascondere i loro dettagli interni, non utilizzeremo una copertura di sicurezza, ma piuttosto una speciale sintassi del linguaggio ed alcune convenzioni.
```

2021-03-06 18:14 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Continuando con l'analogia della macchina del caffe -- ciò che è nascosto internamente: una pompa, un meccanismo di riscaldamento e cosi via -- al sua interfaccia interna.
```suggestion
Continuando con l'analogia della macchina del caffè -- ciò che è nascosto internamente: una pompa, un meccanismo di riscaldamento è così via -- è la sua interfaccia interna.
```

2021-03-06 18:16 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Quindi, tutto ciò di cui abbiamo bisogno per utilizzare un oggetto è la sua interfaccia esterna. Potremmo essere completamente inconsapevoli del suo funzionamento interno, ciò sarebbe la situazione o
```suggestion
Quindi, tutto ciò di cui abbiamo bisogno per utilizzare un oggetto è la sua interfaccia esterna. Potremmo essere completamente inconsapevoli del suo funzionamento interno; e ciò andrebbe bene.
```
Piccolo suggerimento, che ne pensi?

2021-03-06 18:19 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +In molti altri linguaggi di programmazione esiste anche il concetto di campo "protected" (protetto): accessibile solamente dall'interno della classe e da quelle che al estendono (come i campi privati
```suggestion
In molti altri linguaggi di programmazione esiste anche il concetto di campo "protected" (protetto): accessibile solamente dall'interno della classe e da quelle che la estendono (come i campi privati, ma in aggiunta sono accessibili anche dalle classi che ereditano). Questi sono altrettanto utili per la definizione dell'interfaccia interna. Generalmente sono più diffusi dei campi privati, poiché solitamente la nostra intenzione è quella di renderli accessibili anche nelle sotto-classi.
```

2021-03-06 18:20 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +I campi protetti non sono implementati in JavaScript a livello di linguaggio, ma nella pratica risultano essere molto comodi, per questo vengono spesso emulati.
```suggestion
I campi protetti non sono implementati in JavaScript a livello del linguaggio, ma nella pratica risultano essere molto comodi, per questo vengono spesso emulati.
```

2021-03-06 18:21 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ora costruiremo una macchina del caffe in JavaScript con tutti i tipi di proprietà descritti. Una macchina del caffe è composta da molti dettagli, non la modelleremo per intero, in modo da tenere l'e
```suggestion
Ora costruiremo una macchina del caffè in JavaScript, con tutti i tipi di proprietà descritti. Una macchina del caffè è composta da molti dettagli; non la modelleremo per intero, in modo da mantenere l'esempio semplice (anche se potremmo).
```

2021-03-06 18:22 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Come prima cosa creiamo una semplice classe per modellare una macchina del caffe:
```suggestion
Come prima cosa creiamo una semplice classe per modellare una macchina del caffè:
```

2021-03-06 18:28 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +// creiamo la macchina del caffe
```suggestion
// creiamo la macchina del caffè
```

2021-03-06 18:30 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Questa non è una forzatura del linguaggio, ma piuttosto una convenzione piuttosto diffusa tra i programmatori, che specifica che queste proprietà e metodi non dovrebbero essere accedute dall'esterno.
```suggestion
Questa non è una forzatura del linguaggio, ma piuttosto una convenzione diffusa tra i programmatori, che specifica che queste proprietà e metodi non dovrebbero essere accessibili dall'esterno.
```

2021-03-06 18:30 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +// creiamo la macchina del caffe
```suggestion
// creiamo la macchina del caffè
```

2021-03-06 18:31 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Questo è esattamente il caso per un macchina del caffe: la potenza non può variare.
```suggestion
Questo è esattamente il caso per un macchina del caffè: la potenza non può variare.
```

2021-03-06 18:31 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +// creiamo la macchina del caffe
```suggestion
// creiamo la macchina del caffè
```

2021-03-06 18:33 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ma nella maggior parte dei casi, le funzioni `get.../set...`, si preferisce definirle in questo modo:
```suggestion
Ma nella maggior parte dei casi, le funzioni `get.../set...` si preferisce definirle in questo modo:
```

2021-03-06 18:33 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    i (value < 0) value = 0;
```suggestion
    if (value < 0) value = 0;
```

2021-03-06 18:36 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ad esempio, facciamo si che `waterAmount` sia una proprietà per accedere a `#waterAmount`:
```suggestion
Ad esempio, facciamo sì che `waterAmount` sia una proprietà per accedere a `#waterAmount`:
```

2021-03-06 18:38 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Nel caso in cui stessimo ereditando da `CoffeeMachine`, allora non avremo accesso diretto a `#waterAmount`. Dovremo affidarci al getter/setter `waterAmount`:
```suggestion
Nel caso in cui stessimo ereditando da `CoffeeMachine`, allora non avremmo accesso diretto a `#waterAmount`. Dovremmo affidarci al getter/setter `waterAmount`:
```

2021-03-06 18:39 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +In termini di OOP (Programmazione Orientata agli Oggetti), la delimitazione dell'interfaccia interna da quella esterna, si chiama [incapsulamento](https://en.wikipedia.org/wiki/Encapsulation_(compute
```suggestion
In termini di OOP (Programmazione Orientata agli Oggetti), la delimitazione dell'interfaccia interna da quella esterna si chiama [incapsulamento](https://en.wikipedia.org/wiki/Encapsulation_(computer_programming)).
```

2021-03-06 18:41 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +: Immaginiamo ci sia un team di sviluppatori che utilizzano una macchina del caffe. Costruita dall'azienda "Best CoffeeMachine", che funziona correttamente, ma la protezione viene rimossa. In questo
```suggestion
: Immaginiamo un team di sviluppatori che utilizzano una macchina del caffè costruita dall'azienda "Best CoffeeMachine", che funziona correttamente, ma la cui protezione viene rimossa. In questo modo, la sua interfaccia interna viene esposta.
```

2021-03-06 18:43 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Tutti gli sviluppatori sono civilizzati -- utilizzano la macchina del caffe come previsto. Ma uno di loro, Jhon, che crede di essere il più intelligente, ed effettua alcune modifiche ai component
```suggestion
    Tutti gli sviluppatori sono civilizzati -- utilizzano la macchina del caffè come previsto. Ma uno di loro, John, che crede di essere il più intelligente, effettua alcune modifiche alla macchina. Che si rompe due giorni dopo.
```

2021-03-06 18:43 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Questa non è sicuramente colpa di Jhon, ma piuttosto della persona che ha rimosso la protezione e ha permesso a Jhon di manometterla.
```suggestion
    Questa non è sicuramente colpa di John, ma piuttosto della persona che ha rimosso la protezione e ha permesso a John di manometterla.
```

2021-03-06 18:45 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Manutenibili
```suggestion
Manutenibili
```
Sostenibile

2021-03-06 18:46 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +: La situazione nella programmazione rispetto ad una macchina del caffe, poiché non la compriamo solamente una volta. Il codice è costantemente sotto sviluppo e miglioramenti.
```suggestion
: La situazione, nella programmazione, è più complessa rispetto ad una macchina del caffe, poiché non la compriamo solamente una volta. Il codice è costantemente sotto sviluppo e miglioramenti.
```

2021-03-06 18:48 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Se sei lo sviluppatore di una classe di questo tipo, è ottimo sapere che i metodi privati possono essere rinominati in totale sicurezza, i parametri possono essere modificati, o addirittura rimos
```suggestion
    Se sei lo sviluppatore di una classe di questo tipo, è ottimo sapere che i metodi privati possono essere rinominati in totale sicurezza; i parametri possono essere modificati, o addirittura rimossi, poiché nessun codice esterno dipende da questi.
```

2021-03-06 18:49 UTC, Dorin-David commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +: Le persone adorano utilizzare cose semplici. Almeno esternamente. Ciò che è internamente è una questione diversa.
```suggestion
: Le persone adorano utilizzare cose semplici. Almeno esternamente. Ciò che è interno è una questione diversa.
```

2021-03-06 18:50 UTC, Dorin-David requested changes
Ho suggerito alcune modifiche

2021-03-07 08:44 UTC, longo-andrea commented
/done

2021-03-07 10:45 UTC, longo-andrea commented
Ho aggiunto qui la traduzione del titolo del capitolo, mi ero completamente dimenticato 😅

2021-03-07 13:47 UTC, pasor1 requested changes

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +L'interfaccia interna viene utilizzata per far funzionare l'oggetto, ogni dettaglio viene utilizzato da altri elementi. Ad esempio, la pompa è collegata al meccanismo di riscaldamento.
```suggestion
L'interfaccia interna viene utilizzata per far funzionare l'oggetto, i suoi elementi interagiscono gli uni con gli altri. Ad esempio, la pompa è collegata al meccanismo di riscaldamento.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ma vista dall'esterno, la macchina del caffe è protetta da una copertura, in modo che nessuno possa accedervi. I dettagli sono nascosti ed inaccesibili. Possiamo sfruttarne le caratteristiche tramite
```suggestion
Ma vista dall'esterno, la macchina del caffè è protetta da una copertura, in modo che nessuno possa accedervi. I dettagli sono nascosti ed inaccessibili, ma possiamo sfruttarne le caratteristiche tramite la sua interfaccia esterna.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +I campi protetti non sono implementati in JavaScript a livello del linguaggio, ma nella pratica risultano essere molto comodi, per questo vengono spesso emulati.
```suggestion
I campi protetti non sono implementati in JavaScript a livello di linguaggio, ma nella pratica risultano essere molto utili, per questo vengono spesso emulati.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Ora costruiremo una macchina del caffè in JavaScript, con tutti i tipi di proprietà descritti. Una macchina del caffè è composta da molti dettagli; non la modelleremo per intero, in modo da mantenere
```suggestion
Ora costruiremo una macchina del caffè in JavaScript, con tutti i tipi di proprietà descritti. Una macchina del caffè è composta da molti dettagli; non la modelleremo per intero (anche se potremmo), in modo da mantenere l'esempio semplice.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Come prima cosa creiamo una semplice classe per modellare una macchina del caffè:
```suggestion
Come prima cosa creiamo una semplice classe sul modello di una macchina del caffè:
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Attualmente le proprietà `waterAmount` e `power`  sono pubbliche. Possiamo leggerle/modificarle dall'esterno con un qualsiasi valore.
```suggestion
Per ora le proprietà `waterAmount` e `power`  sono pubbliche. Possiamo leggerle/modificarle dall'esterno con un qualsiasi valore.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Esiste una proposta JavaScript, quasi standard, che fornisce il supporto per le proprietà ed i metodi privati.
```suggestion
Esiste una proposta JavaScript in via di approvazione, che fornisce il supporto per le proprietà ed i metodi privati.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +A differenza di quelli protetti, i campi privati sono forzati dal linguaggio stesso. E questa è una buona cosa.
```suggestion
A differenza di quelli protetti, i campi privati sono forniti dal linguaggio stesso. E questa è una buona cosa.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +In molti casi, una limitazione del genere è troppo severa. Se estendiamo una `CoffeeMachine`, potremmo giustamente voler accedere ai suoi campi interni. Questo è il motivo per cui i campi protetti ve
```suggestion
In molti casi, una limitazione del genere è troppo severa. Se estendiamo una `CoffeeMachine`, potremmo giustamente voler accedere ai suoi campi interni. Questo è il motivo per cui i campi protetti vengono usati più spesso, anche se non sono realmente supportati dalla sintassi del linguaggio.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +: Immaginiamo un team di sviluppatori che utilizzano una macchina del caffè costruita dall'azienda "Best CoffeeMachine", che funziona correttamente, ma la cui protezione viene rimossa. In questo modo
```suggestion
: Immaginiamo un team di sviluppatori che utilizzi una macchina del caffè costruita dall'azienda "Best CoffeeMachine", che funziona correttamente, ma la cui protezione viene rimossa. In questo modo, la sua interfaccia interna viene esposta.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Tutti gli sviluppatori sono civilizzati -- utilizzano la macchina del caffè come previsto. Ma uno di loro, John, che crede di essere il più intelligente, effettua alcune modifiche alla macchina.
```suggestion
    Tutti gli sviluppatori sono educati, ed utilizzano la macchina del caffè come previsto. Ma uno di loro, John, che crede di essere il più intelligente, effettua alcune modifiche alla macchina, la quale si rompe due giorni dopo.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Lo stesso vale nella programmazione. Se un utente prova a cambiare campi che non dovrebbero essere modificati dall'esterno -- le conseguenze sono imprevedibili.
```suggestion
    Lo stesso vale nella programmazione. Se un utente prova a cambiare campi che non dovrebbero essere modificati dall'esterno, le conseguenze saranno imprevedibili.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +: La situazione, nella programmazione, è più complessa rispetto ad una macchina del caffe, poiché non la compriamo solamente una volta. Il codice è costantemente sotto sviluppo e miglioramenti.
```suggestion
: La situazione, nella programmazione, è più complessa rispetto ad una macchina del caffè reale, la quale viene semplicemente comprata ed utilizzata. Il codice è costantemente soggetto a sviluppo e miglioramenti.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    Se sei lo sviluppatore di una classe di questo tipo, è ottimo sapere che i metodi privati possono essere rinominati in totale sicurezza; i parametri possono essere modificati, o addirittura rimos
```suggestion
    Se sei lo sviluppatore di una classe di questo tipo, ti farà piacere sapere che i metodi privati possono essere rinominati in totale sicurezza; i parametri possono essere modificati, o addirittura rimossi, poiché nessun codice esterno dipende da questi.
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +    **E' sempre molto conveniente quando i dettagli dell'implementazione sono nascosti. Una semplice documentazione dell'interfaccia esterna è molto più comoda.**
```suggestion
    **E' sempre preferibile nascondere i dettagli implementativi e fornire una semplice e ben documentata interfaccia esterna.**
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +Per nasconde i componenti interni di un interfaccia posiamo utilizzare le proprietà protette o private:
```suggestion
Per nasconde i componenti interni di un'interfaccia possiamo utilizzare le proprietà protette o private:
```

2021-03-07 13:47 UTC, pasor1 commented on 1-js/09-classes/04-private-protected-properties-methods/article.md
> +- I campi protetti vengono preceduti da `_`. Questa è una convenzione piuttosto diffusa, non forzata a livello di linguaggio. I programmatori dovrebbero sempre accedere ai campi preceduti da `_` sola
```suggestion
- I campi protetti vengono preceduti da `_`. Questa è una convenzione ben conosciuta, non implementata a livello di linguaggio. I programmatori dovrebbero sempre accedere ai campi preceduti da `_` solamente dalla classe stessa o dalle sue sotto-classi.
```

2021-03-07 14:56 UTC, longo-andrea commented
/done

2021-03-07 18:14 UTC, pasor1 approved these changes

2021-03-07 18:14 UTC, merged