Mixins
javascript-tutorial/it.javascript.info pull request #242
Opened 2021-03-06 12:10 UTC by longo-andrea

2021-03-06 19:17 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +Il modo più semplice per implementare un mixin in JavaScript è quello di creare un oggetto con dei metodi utili, in questo modo potremo fondermi molto semplicemente nel prototype di un'altra classe.
```suggestion
Il modo più semplice per implementare un mixin in JavaScript è quello di creare un oggetto con dei metodi utili, in questo modo potremo fonderli molto semplicemente nel prototype di un'altra classe.
```

2021-03-06 19:18 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +    // invocazione del metodo padre
```suggestion
    // invocazione del metodo genitore
```

2021-03-06 19:18 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +Questo accade perché i metodi `sayHi` e `sayBye` sono stati creati in `sayHiMixin`. Quindi, anche dopo essere stati copiati, le loro proprietà `[[HomeObject]]` fanno riferimento a `sayHiMixin`, come
```suggestion
Questo accade perché i metodi `sayHi` e `sayBye` sono stati creati in `sayHiMixin`. Quindi, anche dopo essere stati copiati, le loro proprietà `[[HomeObject]]` fanno riferimento a `sayHiMixin`, come mostrato nella figura.
```

2021-03-06 19:19 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +- Anche il metodo `.on(name, handler)` che aggiunge una funzione `handler` come listener degli eventi con il nome fornito. Sarà invocato nel momento in cui un evento con il `name` fornito verrà invoc
```suggestion
- Anche il metodo `.on(name, handler)`, che aggiunge una funzione `handler` come listener degli eventi con il nome fornito. Sarà invocato nel momento in cui un evento con il `name` fornito verrà invocato dalla chiamata `.trigger`.
```

2021-03-06 19:20 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +Oppure un `menu` potrebbe generare un evento di `"select"` quando un elemento viene selezionato, ed un altro oggetto potrebbe essere in ascolto dell'evento. E cosi via.
```suggestion
Oppure un `menu` potrebbe generare un evento di `"select"` quando un elemento viene selezionato, ed un altro oggetto potrebbe essere in ascolto dell'evento. E così via.
```

2021-03-06 19:21 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +- `.on(eventName, handler)` -- assegna la funzione `handler` in modo tale che venga eseguita quando l'evento con il nome fornito viene generato. Tecnicamente, avremmo a disposizione anche la propriet
```suggestion
- `.on(eventName, handler)` -- assegna la funzione `handler` in modo tale che venga eseguita quando l'evento con il nome fornito viene generato. Tecnicamente, avremmo a disposizione anche la proprietà `_eventHandlers` che memorizza un array di gestori per ogni tipo di evento, quindi potremmo semplicemente aggiungerlo alla lista.
```

2021-03-06 19:22 UTC, Dorin-David commented on 1-js/09-classes/07-mixins/article.md
> +- `.trigger(eventName, ...args)` -- genera l'evento: tutti i gestori in `_eventHandlers[eventName]` vengono invocati, con la lista degli argomenti `...args`.
```suggestion
- `.trigger(eventName, ...args)` -- genera l'evento: tutti i gestori in `_eventHandlers[eventName]` vengono invocati con la lista degli argomenti `...args`.
```

2021-03-06 19:23 UTC, Dorin-David requested changes
-

2021-03-07 08:46 UTC, longo-andrea commented
/done

2021-03-07 17:11 UTC, pasor1 approved these changes
Questa traduzione era veramente ben fatta  :+1:

2021-03-07 17:11 UTC, pasor1 commented on 1-js/09-classes/07-mixins/article.md
> +Dopo aver aggiunto il mixin, un oggetto `user` sarà in grado di generare un evento di `"login"` quando l'utente effettua l'accesso. Ed un altro oggetto, diciamo, `calendar` potrebbe essere in ascolto
```suggestion
Dopo aver aggiunto il mixin, un oggetto `user` sarà in grado di generare un evento di `"login"` quando l'utente effettua l'accesso. Ed un altro oggetto, diciamo, `calendar` può stare in ascolto di questi eventi in modo da caricare il calendario della persona autenticata.
```

2021-03-07 17:11 UTC, pasor1 commented on 1-js/09-classes/07-mixins/article.md
> +Oppure un `menu` potrebbe generare un evento di `"select"` quando un elemento viene selezionato, ed un altro oggetto potrebbe essere in ascolto dell'evento. E così via.
```suggestion
Oppure un `menu` può generare un evento di `"select"` quando un elemento viene selezionato, ed un altro oggetto stare in ascolto dell'evento. E così via.
```

2021-03-07 17:11 UTC, pasor1 commented on 1-js/09-classes/07-mixins/article.md
> +Possiamo utilizzare i mixins per aumentare una classe, andando ad aggiungere diversi comportamenti, come la gestione degli eventi vista sopra.
```suggestion
Possiamo utilizzare i mixins per migliorare una classe, andando ad aggiungere diversi comportamenti, come la gestione degli eventi vista sopra.
```

2021-03-07 19:52 UTC, merged