Export and Import
javascript-tutorial/it.javascript.info pull request #243
Opened 2021-03-06 13:50 UTC by longo-andrea

2021-03-06 19:27 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Molte style guide di JavaScript sconsigliano l'utilizzo del punto e virgola dopo la dichiarazione di una classe o funzione.
```suggestion
Molte guide style di JavaScript sconsigliano l'utilizzo del punto e virgola dopo la dichiarazione di una classe o funzione.
```

2021-03-06 19:28 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Ma ne caso in cui si fossero molti import, potremmo importare tutto come un oggetto, utilizzando `import * as <obj>`, ad esempio:
```suggestion
Ma nel caso in cui ci fossero molti import, potremmo importare tutto come un oggetto, utilizzando `import * as <obj>`, ad esempio:
```

2021-03-06 19:30 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Naturalmente, questa pratica richiede l'utilizzo di molti files, poiché ogni cosa richiede il suo modulo, ma questo non è un problema. In realtà, la navigazione del codice diventa più semplice se tut
```suggestion
Naturalmente, questa pratica richiede l'utilizzo di molti files, poiché ogni cosa richiede il suo modulo, ma questo non è un problema. In realtà, la navigazione del codice diventa più semplice se tutti i file hanno dei nomi descrittivi e sono ben strutturati all'interno di cartelle.
```

2021-03-06 19:30 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +I moduli forniscono una speciali sintassi, `export default` ("export di default"), per rendere la pratica "una cosa per modulo" più elegante.
```suggestion
I moduli forniscono una speciale sintassi, `export default` ("export di default"), per rendere la pratica "una cosa per modulo" più elegante.
```

2021-03-06 19:31 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +E' sufficiente inserire `export default`, prima dell'entità da esportare:
```suggestion
E' sufficiente inserire `export default` prima dell'entità da esportare:
```

2021-03-06 19:31 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Tecnicamente, potremmo avere sia il default che il named export nello stesso modulo, ma nella pratica gli sviluppatori non lo fanno. Un modulo può essere named export o default export.
```suggestion
Tecnicamente, potremmo avere sia il default che il named export nello stesso modulo, ma in pratica gli sviluppatori non lo fanno. Un modulo può essere named export o default export.
```

2021-03-06 19:32 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Nella pratica, esistono principalmente due tipi di moduli.
```suggestion
In pratica, esistono principalmente due tipi di moduli.
```

2021-03-06 19:35 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +...Mentre per un default export, noi possiamo decidere il nome in fase di importazione:
```suggestion
...Mentre per un default export, possiamo decidere il nome in fase di importazione:
```

2021-03-06 19:35 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +// potrebbe essere anche import Anything... e comunque funzionerebbe
```suggestion
// potrebbe essere anche import Anything... e funzionerebbe comunque
```

2021-03-06 19:36 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Solitamente, per evitare questo problema, e mantenere il codice consistente, ci si pone come regole che le variabili importate debbano corrispondere ai nomi dei file, esempio:
```suggestion
Solitamente, per evitare questo problema, e mantenere il codice consistente, ci si pone come regola che le variabili importate debbano corrispondere ai nomi dei file, esempio:
```

2021-03-06 19:38 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Poiché le funzionalità di export sono sparpagliate nel package, possiamo importarle in `auth/index.js` ed esportarle da li:
```suggestion
Poiché le funzionalità di export sono sparpagliate nel package, possiamo importarle in `auth/index.js` ed esportarle da lì:
```

2021-03-06 19:39 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +    Nel caso in cui volessimo ri-esportare sia i named che i defaul export, allora abbiamo bisogno di due istruzioni:
```suggestion
    Nel caso in cui volessimo ri-esportare sia i named che i defaul export, allora avremmo bisogno di due istruzioni:
```

2021-03-06 19:40 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Queste stranezza nella ri-esportazione di un default export, è una delle ragioni del perché alcuni sviluppatori non amano i default export, ma preferiscono quelli di default.
```suggestion
Queste stranezze nella ri-esportazione di un default export sono tra le ragioni del per cui alcuni sviluppatori non amano i default export, ma preferiscono quelli di default.
```

2021-03-06 19:41 UTC, Dorin-David commented on 1-js/13-modules/02-import-export/article.md
> +Possiamo inserire le istruzioni di `import/export` in cima o in cosa allo script, non ha importanza.
```suggestion
Possiamo inserire le istruzioni di `import/export` in cima o in coda allo script, non ha importanza.
```

2021-03-06 19:41 UTC, Dorin-David requested changes
--

2021-03-07 08:48 UTC, longo-andrea commented
/done

2021-03-07 17:50 UTC, pasor1 approved these changes
Altra traduzione ben fatta :wink:

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +Molte guide style di JavaScript sconsigliano l'utilizzo del punto e virgola dopo la dichiarazione di una classe o funzione.
```suggestion
Molte *style guides* di JavaScript sconsigliano l'utilizzo del punto e virgola dopo la dichiarazione di una classe o funzione.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +1. Moduli che contengono una library, pacchetti di funzioni, come `say.js` visto sopra.
```suggestion
1. Moduli che contengono una libreria: pacchetti di funzioni, come `say.js` visto sopra.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +2. Moduli che dichiarano una singola entità, esempio un modulo `user.js` che esporta solamente `class User`.
```suggestion
2. Moduli che dichiarano una singola entità: esempio un modulo `user.js` che esporta solamente `class User`.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +I named export sono espliciti. Elencano esattamente il nome di ciò che vogliono importare, quindi avremo questa informazione (il nome) da loro; questa è sempre una buona cosa.
```suggestion
I named export sono espliciti, elencano esattamente il nome di ciò che vogliono importare. Avere in chiaro questa informazione (il nome), è sempre una buona cosa.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +Quindi i membri del team potrebbero utilizzare nomi differenti per importare le stesse cose, e questa non è una buona cosa.
```suggestion
Quindi i membri del team possono utilizzare nomi differenti per importare le stesse cose, e questa non è una buona cosa.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +Immaginiamo di scrivere un "package" (pacchetto): una cartella contenente molti moduli, con alcune funzionalità esportate esternamente (strumenti come NPM ci consentono di pubblicare e distribuire qu
```suggestion
Immaginiamo di scrivere un "package" (pacchetto): una cartella contenente molti moduli, con alcune funzionalità esportate esternamente (strumenti come NPM ci consentono di pubblicare e distribuire questi pacchetti, ma non li utilizzeremo), e con molti moduli che sono semplicemente "helpers", per uso interno in altri moduli del package.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +L'idea è che gli esterni, gli altri programmatori che utilizzano il nostro package, non dovrebbero preoccuparsi della struttura interna, alla ricerca dei file all'interno del nostro package. Esportia
```suggestion
L'idea è che gli esterni, gli altri programmatori che utilizzano il nostro package, non debbano preoccuparsi della struttura interna e o di cercare files tra le cartelle in esso contenute. Esportiamo solamente ciò che è necessario in `auth/index.js` e teniamo il resto nascosto da occhi indiscreti.
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +// import login/logout e li esportiamo immediatamente
```suggestion
// importiamo login/logout e li esportiamo immediatamente
```

2021-03-07 17:50 UTC, pasor1 commented on 1-js/13-modules/02-import-export/article.md
> +// import default come User e lo esportiamo
```suggestion
// importiamo default come User e lo esportiamo
```

2021-03-07 19:54 UTC, merged