Drag'n'Drop with mouse events
javascript-tutorial/it.javascript.info pull request #252
Opened 2021-03-08 23:42 UTC by pierangelomiceli

2021-03-11 21:34 UTC, longo-andrea requested changes

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Di conseguenza, vedremo come implemntara il Drag'n'Drop solo tramite l'utilizzo degli eventi del mouse.
```suggestion
Di conseguenza, vedremo come implementare il Drag'n'Drop solo tramite l'utilizzo degli eventi del mouse.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Queste sono le basi. Dopo vedremo come gestire altre caratteristiche, come evidenziare gli altri elementi sottostanti mentre effettuiamo il trascoinamento su di essi.
```suggestion
Queste sono le basi. Dopo vedremo come gestire altre caratteristiche, come evidenziare gli altri elementi sottostanti mentre effettuiamo il trascinamento su di essi.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +La differenza è particolarmente visibile se trasciniamo il pallone dall'angolo in basso a destra. Nell'esempio precendente il pallone "salterebbe" sotto il puntatore. Adesso segue fluidamente il punt
```suggestion
La differenza è particolarmente visibile se trasciniamo il pallone dall'angolo in basso a destra. Nell'esempio precedente, il pallone "salterebbe" sotto il puntatore. Adesso segue fluidamente il puntatore dalla posizione corrente.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ma gli eventi Drag Events hanno anche delle limitazioni. Ad esempio, non possiamo prevenire il trascinamento da una certa sezione.Inoltre non possiamo rendere il trascinamento solo "orizzontale" o "v
```suggestion
Ma gli eventi Drag Events hanno anche delle limitazioni. Ad esempio, non possiamo prevenire il trascinamento da una certa sezione. Inoltre non possiamo rendere il trascinamento solo "orizzontale" o "verticale". E ci sono tante altre azioni drag'n'drop che non è possibile sfruttare. Inoltre il supporto dei dispositivi mobile per questo tipo di eventi è abbastanza debole.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +## Algortimeo del Drag'n'Drop
```suggestion
## Algortimo del Drag'n'Drop
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ecco una implementazione del trascinamento di un pallone:
```suggestion
Ecco un'implementazione del trascinamento di un pallone:
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Eseguendo il codice, noteremo qualcosa di anomalo. All'inizio del drag'n'drop, il pallone si "duplica": cominceremo trascinando il suo "clone".
```suggestion
Eseguendo il codice, noteremo qualcosa di anomalo. All'inizio del drag'n'drop, il pallone si "duplica": abbiamo cominciato trascinando il suo "clone".
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Questo accade perché il browser ha un suo supporto al drag'n'drop per le immagini e su qualche altro elemento. Lo esegue in automatico e andrebbe in conflitto con il nostro.
```suggestion
Questo accade perché il browser ha una sua implementazione del drag'n'drop per immagini e qualche altro elemento. La esegue in automatico e va quindi in conflitto con la nostra.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Negli esempi precedenti il pallone viene sempre spostata in modo che il suo centro si sotto il puntatore:
```suggestion
Negli esempi precedenti il pallone viene sempre spostato in modo che il suo centro sia sotto il puntatore:
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Non male, ma c'è un effetto collaterale. Cominciando il drag'n'drop, potremmo cominciare `mousedown` da un punto qualunque del pallone. Ma se lo "prendessimo" dai bordi, si centrerebbe repentinamente
```suggestion
Non male, ma c'è un effetto collaterale. Per innescare il drag'n'drop, potremmo cominciare `mousedown` da un punto qualunque del pallone. Ma se lo "prendessimo" dai bordi, si centrerebbe repentinamente sotto il puntatore facendo una specie di "salto".
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. Quindi, durante il trascinamento posizioneremo il pallone con lo stesso spostamento relativa al puntatore, in questo modo:
```suggestion
2. Quindi, durante il trascinamento posizioneremo il pallone con lo stesso spostamento relativo al puntatore, in questo modo:
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Questo è il motivo per cui l'idea iniziale di impostare i gestori su dei potenziali droppables non funzionerebbero. Non verrebbero eseguiti.
```suggestion
Questo è il motivo per cui l'idea iniziale di impostare i gestori su dei potenziali droppables non funziona. I gestori non verrebbero eseguiti.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Possiamo usare questo codice per sapere quale elemento stiamo "sorvolando" in ogni momento. E gestire il rilasciamento quando accade.
```suggestion
Possiamo usare questo codice per sapere quale elemento stiamo "sorvolando" in ogni momento. E gestire il rilascio quando accade.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // glie venti mousemove possono essere generati fuori dalla window (quando il pallone è trascinato fuori dallo schermo)
```suggestion
  // gli eventi mousemove possono essere generati fuori dalla window (quando il pallone è trascinato fuori dallo schermo)
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. All'inizio del trascinamento -- ricorda lo spostamento iniziale del puntatore rispetto all'elemento: `shiftX/shiftY` e mantenerlo durante il tutta la fase di trascinamento.
```suggestion
2. All'inizio del trascinamento -- ricorda lo spostamento iniziale del puntatore rispetto all'elemento: `shiftX/shiftY` e mantenerlo durante tutta la fase di trascinamento.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ci sono frameworks che intere architetture su di esso: `DragZone`, `Droppable`, `Draggable` ed altre classi. La maggior parte di essi fanno cose simili a quelle appena descritte, quindi potrebbe esse
```suggestion
Esistono frameworks che basano intere architetture su di esso: `DragZone`, `Droppable`, `Draggable` ed altre classi. La maggior parte di essi fanno cose simili a quelle appena descritte, quindi potrebbe essere semplice comprenderle adesso. Oppure potresti preparartelo da te, dal momento che abbiamo visto quanto sia facile da fare, talvolta più semplice di adattare una soluzione terze parti.
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <p>I supereroi ed il pallone sono elementi che hanno la classe "draggable". Renderli realmente trascinabili.</p>
```suggestion
  <p>I supereroi ed il pallone sono elementi che hanno la classe "draggable". Rendili realmente trascinabili.</p>
```

2021-03-11 21:34 UTC, longo-andrea commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +- Gli elemetni tascinabili o le loro parti non devono mai uscire fuori dalla finestra, anche dopo movimenti veloci.
```suggestion
- Gli elementi trascinabili o le loro parti non devono mai uscire fuori dalla finestra, anche dopo movimenti veloci.
```

2021-03-13 07:16 UTC, pierangelomiceli commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +- Gli elemetni tascinabili o le loro parti non devono mai uscire fuori dalla finestra, anche dopo movimenti veloci.
/done

2021-03-13 08:07 UTC, longo-andrea approved these changes

2021-03-15 09:48 UTC, pasor1 approved these changes

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/task.md
> +La demo è troppo grande per entrare in quest'area, quindi ecco il link.
```suggestion
La demo è troppo grande per essere inclusa qui, quindi ecco il link.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/soccer.css
> +/* erori e pallone (draggables) */
```suggestion
/* eroi e pallone (draggables) */
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
> +  <h2>Piazza i supereroi nel campo di calcio.</h2>
```suggestion
  <h2>Posizionare i supereroi nel campo di calcio.</h2>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
> +  <p>Importante: limitare il trascinamento nella finestra. Se un oggetto trascinabile arriva sulla parte alta o bassa dello schermo la pagina dovrebbe scrollare per permettere di trascinare ancora.</
```suggestion
  <p>Importante: limitare il trascinamento nella finestra. Se un oggetto trascinabile arriva sulla parte alta o bassa dello schermo, la pagina dovrebbe scrollare per permettere proseguire il trascinamento.</p>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/source.view/index.html
> +  <p>Se lo schermo è abbstanza grande da contenere l'intero documento, rendere la finestra più piccola per poter attivare lo scrolling verticale, in modo da poterlo testare.</p>
```suggestion
  <p>Se lo schermo è abbastanza grande da contenere l'intero documento, rendere la finestra più piccola per poter attivare lo scrolling verticale, in modo da poterlo testare.</p>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.md
> +Per trascinare l'elemento possiamo usare `position:fixed`, il quale semplifica la gestione delle coordinate. Alla fine  dovremmo tornare ad utilizzare `position:absolute` per posizionare l'elemento a
```suggestion
Per trascinare l'elemento possiamo usare `position:fixed`, il quale semplifica la gestione delle coordinate. Alla fine dovremmo tornare ad utilizzare `position:absolute` per posizionare l'elemento all'interno del document.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <h2>Piazza i supereroi nel campo di calcio.</h2>
```suggestion
  <h2>Posizionare i supereroi nel campo di calcio.</h2>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <p>I supereroi ed il pallone sono elementi che hanno la classe "draggable". Rendili realmente trascinabili.</p>
```suggestion
  <p>I supereroi ed il pallone sono elementi che hanno la classe "draggable". Renderli realmente trascinabili.</p>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <p>Importante: limitare il trascinamento nella finestra. Se un oggetto trascinabile arriva sulla parte alta o bassa dello schermo la pagina dovrebbe scrollare per permettere di trascinare ancora.</
```suggestion
  <p>Importante: limitare il trascinamento nella finestra. Se un oggetto trascinabile arriva sulla parte alta o bassa dello schermo la pagina dovrebbe scrollare per permettere di proseguire il trascinamento.</p>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/2-drag-heroes/solution.view/index.html
> +  <p>Se lo schermo è abbstanza grande da contenere l'intero documento, rendere la finestra più piccola per poter attivare lo scrolling verticale, in modo da poterlo testare.</p>
```suggestion
  <p>Se lo schermo è abbastanza grande da contenere l'intero documento, rendere la finestra più piccola per poter attivare lo scrolling verticale, in modo da poterlo testare.</p>
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Questi eventi ci permettono di supportare tipi particolari di drag'n'drop, come gestire il trascinamento di un file dal gestore file dell'OS e rilasciarlo dentro la finestra del browser. Successivame
```suggestion
Questi eventi ci permettono di supportare tipi particolari di drag'n'drop, come gestire il trascinamento di un file dal sistema operativo ed il rilascio dentro la finestra del browser, in modo che JavaScript possa accedere al contenuto di tali files.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Ma gli eventi Drag Events hanno anche delle limitazioni. Ad esempio, non possiamo prevenire il trascinamento da una certa sezione. Inoltre non possiamo rendere il trascinamento solo "orizzontale" o "
```suggestion
Ma i Drag Events hanno anche delle limitazioni. Ad esempio, non possiamo prevenire il trascinamento da una certa sezione. Inoltre non possiamo rendere il trascinamento solo "orizzontale" o "verticale". E ci sono tante altre azioni drag'n'drop che non è possibile sfruttare. Inoltre il supporto dei dispositivi mobile per questo tipo di eventi è abbastanza scarso.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // (3) rilascio del pallone, rimozione di gestori non necessari
```suggestion
  // (3) rilascio del pallone, rimozione dei gestori non necessari
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +    Per ottenere questi spostamenti possiamo sottrarre le coordinate:
```suggestion
    Per ottenere questi scostamenti possiamo sottrarre le coordinate:
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. Quindi, durante il trascinamento posizioneremo il pallone con lo stesso spostamento relativo al puntatore, in questo modo:
```suggestion
2. Quindi, durante il trascinamento posizioneremo il pallone con lo stesso scostamento relativo al puntatore, in questo modo:
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +    Per ottenere questi spostamenti possiamo sottrarre le coordinate:
ho inserito il termine scostamento, ma potrebbe essere valido anche il concetto di "margine"

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +  // tenendo conto dello spostamento iniziale
```suggestion
  // tenendo conto dello scostamento iniziale
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +C'è un metodo chiamato `document.elementFromPoint(clientX, clientY)`. Restituisce le coordinate relative alla window, dell'elemento più annidato (o `null` se le coordinate restituite sono fuori dalla
```suggestion
C'è un metodo chiamato `document.elementFromPoint(clientX, clientY)` che restituisce le coordinate relative alla window, dell'elemento più annidato (o `null` se le coordinate restituite sono fuori dalla window).
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +    //   currentDroppable=null se non siamo su un elemento prima di questo evento (e.g su uno spazio vuoto)
```suggestion
    //   currentDroppable=null se non siamo su un elemento prima di questo evento (es. su uno spazio vuoto)
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Adesso abbiamo l'attuale "obiettivo drop", sul quale stiamo sorvolando, dentro la variabile `currentDroppable` durante tutta l'operazione, e possiamo usarlo per evidenziarlo o per altre cose.
```suggestion
Adesso abbiamo l' "obiettivo drop" corrente, sul quale stiamo sorvolando, dentro la variabile `currentDroppable` durante tutta l'operazione, e possiamo usarlo per evidenziarlo o per altre cose.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +2. All'inizio del trascinamento -- ricorda lo spostamento iniziale del puntatore rispetto all'elemento: `shiftX/shiftY` e mantenerlo durante tutta la fase di trascinamento.
```suggestion
2. All'inizio del trascinamento -- ricorda lo scostamento iniziale del puntatore rispetto all'elemento: `shiftX/shiftY` e di mantenerlo durante tutta la fase di trascinamento.
```

2021-03-15 09:48 UTC, pasor1 commented on 2-ui/3-event-details/4-mouse-drag-and-drop/article.md
> +Esistono frameworks che basano intere architetture su di esso: `DragZone`, `Droppable`, `Draggable` ed altre classi. La maggior parte di essi fanno cose simili a quelle appena descritte, quindi potre
```suggestion
Esistono frameworks che basano intere architetture su di esso: `DragZone`, `Droppable`, `Draggable` ed altre classi. La maggior parte di essi fanno cose simili a quelle appena descritte, quindi potrebbe essere semplice comprenderle adesso. Oppure potresti preparartelo da te, dal momento che abbiamo visto quanto sia facile da fare, talvolta più semplice di adattare una soluzione di terze parti.
```

2021-03-15 15:02 UTC, pierangelomiceli commented
\done

2021-03-15 19:53 UTC, merged