Walking the DOM
javascript-tutorial/it.javascript.info pull request #253
Opened 2021-03-09 19:56 UTC by pasor1

2021-03-11 07:22 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
> +// oppure (il primo nodo e' uno spazio, quindi prendiamo il secondo)
```suggestion
// oppure (il primo nodo è uno spazio, quindi prendiamo il secondo)
```

2021-03-11 07:22 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/1-dom-children/task.md
> +# figli nel DOM
```suggestion
# Figli nel DOM
```

2021-03-11 07:23 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/3-navigation-links-which-null/solution.md
> +Se non ci sono figli, `elem.lastChild` è `null`, quindi non possiamo accedere a `elem.lastChild.nextSibling`. E la collection `elem.children` sarà vuota (Come un array vuoto `[]`).
```suggestion
Se non ci sono figli, `elem.lastChild` è `null`, quindi non possiamo accedere a `elem.lastChild.nextSibling`. E la collection `elem.children` sarà vuota (come un array vuoto `[]`).
```

2021-03-11 07:24 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Il DOM ci consente di fare qualsiasi cosa con gli elementi ed il loro contenuto, ma prima dobbiamo essere in grado raggiungere l'oggetto DOM corrispondente.
```suggestion
Il DOM ci consente di fare qualsiasi cosa con gli elementi ed il loro contenuto, ma prima dobbiamo essere in grado di raggiungere l'oggetto DOM corrispondente.
```

2021-03-11 07:25 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +## In cima: documentElement a body
```suggestion
## In cima: documentElement e body
```

2021-03-11 07:25 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +In particolare, se uno script si trova all'intendo di `<head>`, `document.body` non è disponibile, perché il browser non lo ha ancora letto.
```suggestion
In particolare, se uno script si trova all'interno di `<head>`, `document.body` non è disponibile, perché il browser non lo ha ancora letto.
```

2021-03-11 07:28 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Non possiamo un nodo figlio con qualcos'altro con l'assegnazione `childNodes[i] = ...`.
```suggestion
Non possiamo sostituire un nodo figlio con qualcos'altro con l'assegnazione `childNodes[i] = ...`.
```

2021-03-11 07:28 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Salvo poche eccezioni, tutte le DOM collections sono *vive*. In altre parole, riflettono lo stato corrente DOM.
```suggestion
Salvo poche eccezioni, tutte le DOM collections sono *vive*. In altre parole, riflettono lo stato corrente del DOM.
```

2021-03-11 07:29 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +## i fratelli (*siblings*) ed il genitore (*parent*)
```suggestion
## I fratelli (*siblings*) ed il genitore (*parent*)
```

2021-03-11 07:30 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +// il genitore di <body> e' <html>
```suggestion
// il genitore di <body> è <html>
```

2021-03-11 07:30 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +// dopo di <head> c'e' <body>
```suggestion
// dopo di <head> c'è <body>
```

2021-03-11 07:31 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +// prima di <body> c'e' <head>
```suggestion
// prima di <body> c'è <head>
```

2021-03-11 07:31 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +## navigazione solo tra elementi
```suggestion
## Navigazione solo tra elementi
```

2021-03-11 07:32 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +La proprietà `parentElement` restituisce l' "elemento" genitore, mentre `parentNode` restituisce "qualsiasi nodo" genitore. Queste proprietà in genere coincidono: entrambe restituiscono lo stesso gen
```suggestion
La proprietà `parentElement` restituisce l'elemento genitore, mentre `parentNode` restituisce "qualsiasi nodo" genitore. Queste proprietà in genere coincidono: entrambe restituiscono lo stesso genitore.
```
Io qui toglierei le virgolette, che ne pensi?

2021-03-11 07:33 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Questo dettaglio può essere utile quando volgiamo risalire da un elemento arbitrario `elem` verso `<html>`, ma senza arrivare a `document`:
```suggestion
Questo dettaglio può essere utile quando vogliamo risalire da un elemento arbitrario `elem` verso `<html>`, ma senza arrivare a `document`: 
```

2021-03-11 07:34 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +- `table.tBodies` -- la collection degli elementi `<tbody>` (secondo lo standard possono essere molti, ma ce ne sarà sempre almeno uno. Anche se non è nell' HTML di origine, il browser lo inserirà au
```suggestion
- `table.tBodies` -- la collection degli elementi `<tbody>` (secondo lo standard possono essere molti, ma ce ne sarà sempre almeno uno. Anche se non è nell'HTML di origine, il browser lo inserirà automaticamente nel DOM).
```

2021-03-11 07:36 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Proprietà di navigazione aggiuntive, sono anche disponibili per i moduli HTML. Li esamineremo più avanti, quando inizieremo a lavorare con i moduli.
```suggestion
Proprietà di navigazione aggiuntive, sono anche disponibili per i moduli HTML. Le esamineremo più avanti, quando inizieremo a lavorare con i moduli.
```
Qui ci riferiamo a proprieta', non ai moduli, corretto? Non e' chiarissimo, ma se ci si riferisce alle proprieta' (penso di si' perche' subito dopo specifica moduli) va al femminile

2021-03-11 07:37 UTC, Dorin-David commented on 2-ui/1-document/03-dom-navigation/article.md
> +Ne esistono di due tipi principali:
```suggestion
Ne esistono due tipi principali:
```
Questo e' solo un suggerimento soggettivo, accetta o no come preferisci :)

2021-03-11 07:37 UTC, Dorin-David reviewed
Corretti dei refusi. Ottima traduzione!

2021-03-11 07:56 UTC, pasor1 commented on 2-ui/1-document/03-dom-navigation/article.md
> +Proprietà di navigazione aggiuntive, sono anche disponibili per i moduli HTML. Li esamineremo più avanti, quando inizieremo a lavorare con i moduli.
Yes, hai ragione tu, penso che il riferimento sia alle proprietà

2021-03-11 07:57 UTC, pasor1 commented
/done

2021-03-12 20:07 UTC, longo-andrea requested changes
Ottima traduzione 👍  la metto in request changes perché ci sono alcune righe non tradotte. Ho proposto anche migliorie ad alcune frasi, ma sentiti libero di non accettarle/discuterne

2021-03-12 20:07 UTC, longo-andrea commented on 2-ui/1-document/03-dom-navigation/article.md
> +Per favore non farlo. I cicli `for..in` iterano su tutte le proprietà enumerabili, e le collections possiedono alcune proprietà "extra", che vengono usare raramente, e che in genere non vorremmo ci f
```suggestion
E' una pratica sconsigliata. I cicli `for..in` iterano su tutte le proprietà enumerabili, e le collections possiedono alcune proprietà "extra", che vengono usate raramente, e che in genere non vorremmo ci fossero restituite dal ciclo:
```

2021-03-12 20:07 UTC, longo-andrea commented on 2-ui/1-document/03-dom-navigation/article.md
> +````smart header="Why `parentElement`? Può un genitore *non* essere un elemento?"
```suggestion
````smart header="Perché `parentElement`? Può un genitore *non* essere un elemento?"
```

2021-03-12 20:07 UTC, longo-andrea commented on 2-ui/1-document/03-dom-navigation/article.md
> +Dato un nodo DOM, possiamo puntare ai suoi vicini usando le proprietà di navigazione.
```suggestion
Dato un nodo DOM, possiamo spostarci tra i suoi vicini usando le proprietà di navigazione.
```

2021-03-12 20:07 UTC, longo-andrea commented on 2-ui/1-document/03-dom-navigation/1-dom-children/solution.md
>  There are many ways, for instance:
```suggestion
E' possibile farlo in diversi modi, ad esempio:
```

2021-03-14 14:17 UTC, pasor1 commented
/done

2021-03-14 14:20 UTC, longo-andrea approved these changes

2021-03-14 14:21 UTC, merged