dom searching translation
javascript-tutorial/it.javascript.info pull request #254
Opened 2021-03-09 22:15 UTC by Dorin-David

2021-03-10 10:03 UTC, pasor1 approved these changes
Sono stato un po' pignolo :sweat_smile:

2021-03-11 07:10 UTC, Dorin-David commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +Le pseudo-classi come `:hover` e `:active` sono altresì supportate. Ad esempio, `document.querySelectorAll(':hover')` ritornerà una collezione con gli elementi sopra cui punta il cursore in questo mo
Sono d'accordo.

2021-03-11 07:20 UTC, Dorin-David commented
/done

2021-03-12 20:32 UTC, longo-andrea requested changes
Ottima traduzione 👍 ti ho lasciato un paio di spunti, sentiti libero di non accettarli/discuterne

2021-03-12 20:32 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +Questo comportamento è descritto [nella specifica](http://www.whatwg.org/specs/web-apps/current-work/#dom-window-nameditem), quindi è quasi uno standart, ma è supportato principalmente per una questi
```suggestion
Questo comportamento è descritto [nella specifica](http://www.whatwg.org/specs/web-apps/current-work/#dom-window-nameditem), quindi è quasi uno standard, ma è supportato principalmente per una questione di compatibilità.
```

2021-03-12 20:32 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +```warn header="Non utilizzate le variabili globali per accedere agli elementi"
Qui non è troppo chiaro cosa si intenda per variabili globali. Quello che intende dire in lingua inglese è che se tu dichiari un elemento con id, verrà automaticamente creata una variabile, e potrai accedere al nodo con `window.[nomeId]`... però non saprei nemmeno io come tradurre in maniera elegante questo titoletto

```suggestion
```warn header="Non utilizzate le variabili globali denominate dall'id per accedere agli elementi"
```

2021-03-12 20:32 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +Qui li studiamo per completezza, mentre possono essere ancora trovati nei vecchi script.
```suggestion
Qui li studiamo per completezza, poiché possono essere ancora trovati nei vecchi script.
```

2021-03-12 20:32 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +Tutti i metodi `"getElementsBy*"` ritornano una collection *viva*. Questa collction rispecchia sempre lo stato corrente del documento e si "auto-aggiorna" quando questo cambia.
```suggestion
Tutti i metodi `"getElementsBy*"` ritornano una collection *viva*. Questa collection rispecchia sempre lo stato corrente del documento e si "auto-aggiorna" quando questo cambia.
```

2021-03-12 20:32 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +I più utilizzati sono `querySelector` e `querySelectorAll`, ma `getElement(s)By*` può essere utile qualche volta, e si trova nei vecchi script.
```suggestion
I più utilizzati sono `querySelector` e `querySelectorAll`, ma `getElement(s)By*` può essere utile in alcuni casi, e si trova nei vecchi script.
```

2021-03-12 21:58 UTC, Dorin-David commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +```warn header="Non utilizzate le variabili globali per accedere agli elementi"
```suggestion
```warn header="Non utilizzate le variabili-id globali per accedere agli elementi"
```
Che ne dici di cosi'? Un po' banale forse ma e' leggermente piu' chiaro, non trovi?

2021-03-12 22:13 UTC, longo-andrea commented on 2-ui/1-document/04-searching-elements-dom/article.md
> +```warn header="Non utilizzate le variabili globali per accedere agli elementi"
Si molto piu chiaro cosi! Vai pure con la tua modifica, poi è pronta per il merge

2021-03-12 22:13 UTC, longo-andrea approved these changes

2021-03-13 20:08 UTC, merged