Pointer events
javascript-tutorial/it.javascript.info pull request #260
Opened 2021-03-14 12:16 UTC by pierangelomiceli

2021-03-14 21:39 UTC, longo-andrea requested changes
Ottima traduzione 👍 ti ho lasciato un paio di note per rendere la lettura piu scorrevole, valuta tu se e quali appunti integrare

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +- Il dispositivo di puntamento è stato fisicamene disabilitato.
```suggestion
- Il dispositivo di puntamento è stato fisicamente disabilitato.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +2. Nel caso vi fossero altri gestori `pointermove` nel documento, non verrebbero innescati dal puntatore mentre l'utente è intento a trascinare il curosore.
```suggestion
2. Nel caso vi fossero altri gestori `pointermove` nel documento, non verrebbero innescati dal puntatore mentre l'utente è intento a trascinare il cursore.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Gli eventi del puntatore estendon gli eventi del mouse. Possiamo sostituire `mouse` con `pointer` nei nomi degli evenit ed aspettarci che il codice continui a funzionare per il mouse, con un supporto
```suggestion
Gli eventi del puntatore estendono gli eventi del mouse. Possiamo sostituire `mouse` con `pointer` nei nomi degli eventi ed aspettarci che il codice continui a funzionare per il mouse, con un supporto migliore per altri tipi di dispositivi.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +- Proprietà spiecifiche per alcuni dispositivi, come `pressure`, `width/height`, ed altri.
```suggestion
- Proprietà specifiche per alcuni dispositivi, come `pressure`, `width/height`, ed altri.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Ad oggi, gli eventi del puntore sono supportati da tutti i principali browser, quindi possiamo passare a questi, specialmente se IE10- e Safari 12- non sono necessari. Tuttavia, anche con questi brow
```suggestion
Ad oggi, gli eventi del puntatore sono supportati da tutti i principali browser, quindi possiamo passare a questi, specialmente se IE10- e Safari 12- non sono necessari. Tuttavia, anche con questi browser, esistono i polyfill che abilitano il supporto degli eventi di tipo puntatore.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Facciamo una breve panoramica, in modo da comprendere la visione generale e il posto che occupano gli questi eventi, rispetto agli altri.
```suggestion
Facciamo una breve panoramica, in modo da averne una visione generale del posto che occupano gli questi eventi, rispetto agli altri.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +    Ad un certo punto, si diffusero i dispositivi touch, in particolar modo telefoni e tablet. Per fare in modo che gli script esistenti potessero continuare a funzionare, questi generavano (e lo fan
```suggestion
    Ad un certo punto, iniziarono a diffondersi i dispositivi touch, in particolar modo telefoni e tablet. Per fare in modo che gli script esistenti potessero continuare a funzionare, questi generavano (e lo fanno ancora oggi) eventi del mouse. Ad esempio, un touchscreen al tocco, genera un `mousedown`. In questa maniera i nuovi dispositivi poterono funzionare correttamente con le pagine web.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +- Quindi vennero introdotti gli eventi touch, come `touchstart`, `touchend`, `touchmove`, che hanno delle proprietà apposite (non le affronteremo adesso in dettaglio, perché gli eventi del puntatore
```suggestion
- Quindi vennero introdotti gli eventi touch, come `touchstart`, `touchend`, `touchmove`, che possiedono delle proprietà dedicate (non le affronteremo adesso in dettaglio, perché gli eventi del puntatore sono migliori).
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +```smart header="Replacing `mouse<event>` con `pointer<event>` nel codice"
```suggestion
```smart header="Rimpiazzare `mouse<event>` con `pointer<event>` nel codice"
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Alcuni dispositivi di puntamento misurano l'area di contatto e la pressione, ad esempi, nel caso del dito sul touchscreen, esistono delle apposite proprietà aggiuntive:
```suggestion
Alcuni dispositivi di puntamento misurano l'area di contatto e la pressione, ad esempio, nel caso del dito sul touchscreen, esistono delle apposite proprietà aggiuntive:
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Queste proprietà non sono supportate dalla maggioranza dei dispositivi, quindi sono usate raramente. In caso di necessità potete trovarne i dettagli nelle [specifiche](https://w3c.github.io/pointerev
```suggestion
Queste proprietà non sono supportate dalla maggioranza dei dispositivi, per questo vengono usate raramente. In caso di necessità potete trovarne i dettagli nelle [specifiche](https://w3c.github.io/pointerevents/#pointerevent-interface).
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Una delle cose assolutamente non supportate dagli eventi del mouse è il multi-touch: quando un utente può toccare lo schermo contemporaneamente in più punti sul telefono o tablet, o esegue gesti part
```suggestion
Una delle cose assolutamente non supportate dagli eventi del mouse è il multi-touch: un utente può toccare lo schermo contemporaneamente in più punti sul telefono o tablet, o eseguire gesti particolari.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Ecco ciò che succede quando un utente tocca il touchscreen in punto, e successivamente poggia un altro dito in su qualche altro punto dello schermo:
```suggestion
Ecco ciò che succede quando un utente tocca il touchscreen in punto, e successivamente poggia un altro dito su qualche altro punto dello schermo:
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Nota bene: Per vedere la differenza dei valori di `pointerId/isPrimary` è necessario usare un dispositivo touch, ad esempi un telefono o un tablet. Per dispositivi a tocco singolo, come i mouse, ci s
```suggestion
Nota bene: Per vedere la differenza dei valori di `pointerId/isPrimary` è necessario usare un dispositivo touch, ad esempio un telefono o un tablet. Per dispositivi a tocco singolo, come i mouse, ci sarà sempre lo stesso `pointerId` con `isPrimary=true`, per tutti gli eventi del puntatore.
```

2021-03-14 21:39 UTC, longo-andrea commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Così, anche se l'utente sposta il cursore attorno a tutto il documento, i gestori evento verranno chiamati su `thumb`. Oltretutto, le coordinate degli oggetti evento, come `clientX/clientY` saranno a
```suggestion
Così, anche se l'utente sposta il cursore in un qualsiasi punto della pagina, i gestori evento verranno chiamati su `thumb`. Oltretutto, le coordinate degli oggetti evento, come `clientX/clientY` saranno ancora corrette, perché la cattura influenza solamente `target/currentTarget`.
```

2021-03-14 23:05 UTC, pierangelomiceli commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Così, anche se l'utente sposta il cursore attorno a tutto il documento, i gestori evento verranno chiamati su `thumb`. Oltretutto, le coordinate degli oggetti evento, come `clientX/clientY` saranno a
/done

2021-03-14 23:06 UTC, pierangelomiceli commented
/done

2021-03-15 19:56 UTC, longo-andrea approved these changes

2021-03-19 17:33 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
>  ## The brief history
```suggestion
## Una breve storia
```

2021-03-19 17:35 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
>  # Pointer events
```suggestion
# Eventi del puntatore
```
Suggerisco traduzione, visto che la utilizzi sotto; per me si potrebbe anche lasciare il titolo in inglese

2021-03-19 17:37 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Facciamo una breve panoramica, in modo da averne una visione generale del posto che occupano gli questi eventi, rispetto agli altri.
```suggestion
Facciamo una breve panoramica, in modo da avere una visione generale del posto che occupano questi eventi rispetto agli altri.
```

2021-03-19 17:38 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +    Ad un certo punto, iniziarono a diffondersi i dispositivi touch, in particolar modo telefoni e tablet. Per fare in modo che gli script esistenti potessero continuare a funzionare, questi generava
```suggestion
    Ad un certo punto, iniziarono a diffondersi i dispositivi touch, in particolar modo telefoni e tablet. Per fare in modo che gli script esistenti potessero continuare a funzionare, questi generavano (e lo fanno ancora oggi) eventi del mouse. Ad esempio, un touchscreen, al tocco, genera un `mousedown`. In questa maniera i nuovi dispositivi poterono funzionare correttamente con le pagine web.
```

2021-03-19 17:40 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Il supporto ai dispositivi touch inoltre migliorerà "magicamente". Sebbene, saremo costretti ad aggiungere  `touch-action: none` in alcune sezioni del CSS. Affronteremo questa cosa più avanti nella s
```suggestion
Il supporto ai dispositivi touch inoltre migliorerà "magicamente". Sebbene saremo costretti ad aggiungere  `touch-action: none` in alcune sezioni del CSS. Affronteremo questa cosa più avanti nella sezione del `pointercancel`. 
```

2021-03-19 17:42 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Ecco ciò che succede quando un utente tocca il touchscreen in punto, e successivamente poggia un altro dito su qualche altro punto dello schermo:
```suggestion
Ecco ciò che succede quando un utente tocca il touchscreen in un punto, e successivamente poggia un altro dito su qualche altro punto dello schermo:
```

2021-03-19 17:44 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +L'evento `pointercancel` si genera se nel bel mezzo di una interazione, avviene qualcosa che ne causa la cancellazione, tale che non venga generato nessun evento del puntatore.
```suggestion
L'evento `pointercancel` si genera se, nel bel mezzo di una interazione, avviene qualcosa che ne causa la cancellazione, tale che non venga generato nessun evento del puntatore.
```

2021-03-19 17:49 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Questa soluzione sembra un po' "sporca". Uno dei problemi è che i movimenti del puntatore sul documento possono causare effetti collaterali, innescare altri gestori evento, per nulla correlate allo s
```suggestion
Questa soluzione sembra un po' "sporca". Uno dei problemi è che i movimenti del puntatore sul documento possono causare effetti collaterali, innescare altri gestori evento, per nulla correlati allo slider.
```

2021-03-19 17:50 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +// avviene autamaticamente al pointerup
```suggestion
// avviene automaticamente al pointerup
```

2021-03-19 17:51 UTC, Dorin-David commented on 2-ui/3-event-details/6-pointer-events/article.md
> +Per i drag'n'drop ed interazioni touch complesse che il browser potrebbe decidere di dirottare sulla propria gestione, dobbiamo ricordarci di disabilitarne l'azione predifinita sugli eventi ed impost
```suggestion
Per i drag'n'drop ed interazioni touch complesse che il browser potrebbe decidere di dirottare sulla propria gestione, dobbiamo ricordarci di disabilitarne l'azione predefinita sugli eventi ed impostare sul CSS `touch-events: none`, per gli elementi che vogliamo coinvolgere.
```

2021-03-19 17:52 UTC, Dorin-David reviewed
Bella traduzione. Ho suggerito alcune piccole modifiche e corretto dei typo

2021-03-20 21:50 UTC, pierangelomiceli commented
/done

2021-03-20 22:34 UTC, merged