Translate chapters' headers
javascript-tutorial/it.javascript.info pull request #262
Opened 2021-03-14 14:14 UTC by longo-andrea

2021-03-15 11:23 UTC, pasor1 requested changes

2021-03-15 11:23 UTC, pasor1 commented on 2-ui/1-document/index.md
> +Impareremo come manipolare una pagina web con JavaScript.
```suggestion
Impareremo come manipolare una pagina web usando JavaScript.
```

2021-03-15 11:23 UTC, pasor1 commented on 2-ui/2-events/index.md
> +# Ibntroduzione agli Events
Mi chiedevo se non fosse il caso di tradurre "Events". Evento è comunemente usato in italiano.

2021-03-17 20:26 UTC, longo-andrea commented
ho aggiornato i riferimenti a `Events` (ora `Eventi`), come discusso... se non hai altri dubbi, procedi pure con il merge

2021-03-17 20:31 UTC, merged