Keyboard: keydown and keyup
javascript-tutorial/it.javascript.info pull request #265
Opened 2021-03-15 14:55 UTC by pierangelomiceli

2021-03-19 17:54 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.view/index.html
> +        // si, lo sono
```suggestion
        // sì, lo sono
```

2021-03-19 17:56 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Quindi, se vogliamo tenere traccia di qualunque input dentro un campo `<input>`, allora gli eventi della tastiera non saranno sufficienti. Esiste però un altro evento chiamato `input` per tenere trac
```suggestion
Quindi, se vogliamo tenere traccia di qualunque input dentro un campo `<input>`, allora gli eventi della tastiera non saranno sufficienti. Esiste però un altro evento chiamato `input` per tenere traccia delle modifiche degli `<input>`, indipendentemente dalla modalità di inserimento. Questa potrebbe essere la scelta corretta per questo tipo di attività. L'argomento verrà affrontato più avanti nel capitolo <info:events-change-input>.
```

2021-03-19 18:07 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +L'evento `keydown` viene scaturito alla pressione di un tasto, `keyup`, invece, quando viene rilasciato.
```suggestion
L'evento `keydown` scaturisce alla pressione di un tasto; `keyup`, invece, quando viene rilasciato.
```

2021-03-19 18:39 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +La proprietà `key` dell'oggetto evento, permette di ottenere il carattere, mentre la proprietà `code` ci restituisce il "codice fisico del tasto".
```suggestion
La proprietà `key` dell'oggetto evento permette di ottenere il carattere, mentre la proprietà `code` ci restituisce il "codice fisico del tasto".
```

2021-03-19 18:40 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Prendendo questo tasto come riferimento, se un utente facesse uso di diverse lingue nello stesso sistema operativo, il passaggio ad un'altra lingua, potrebbe portare ad avere tutt'altro carattere ris
```suggestion
Prendendo questo tasto come riferimento, se un utente facesse uso di diverse lingue nello stesso sistema operativo, il passaggio ad un'altra lingua potrebbe portare ad avere tutt'altro carattere rispetto a `"Z"`. Quest'ultimo sarebbe il valore di `event.key`, mentre `event.code` sarebbe sempre `"KeyZ"`.
```

2021-03-19 18:40 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Ogni tasto ha un codice che dipende dalla sua posizione sulla tastiera. Questi codici, vengono descritti nelle [specifiche dei codici Evento UI](https://www.w3.org/TR/uievents-code/).
```suggestion
Ogni tasto ha un codice che dipende dalla sua posizione sulla tastiera. Questi codici vengono descritti nelle [specifiche dei codici Evento UI](https://www.w3.org/TR/uievents-code/).
```

2021-03-19 18:41 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Per avere informazioni sui vari codici fare riferimento alla [sezione alfanumerica delle specifiche](https://www.w3.org/TR/uievents-code/#key-alphanumeric-section), oppure, è sufficiente premere un t
```suggestion
Per avere informazioni sui vari codici, fare riferimento alla [sezione alfanumerica delle specifiche](https://www.w3.org/TR/uievents-code/#key-alphanumeric-section), oppure, è sufficiente premere un tasto nel [banco di test](#keyboard-test-stand) precedente.
```

2021-03-19 18:42 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Mettiamo il caso che volessimo gestire una scorciatoia: `key:Ctrl+Z` (o `key:Cmd+Z` su Mac). La maggior parte degli editor di testo associa a questa combinazione, l'azione "Undo". A quel punto potrem
```suggestion
Mettiamo il caso che volessimo gestire una scorciatoia: `key:Ctrl+Z` (o `key:Cmd+Z` su Mac). La maggior parte degli editor di testo associa a questa combinazione, l'azione "Undo". A quel punto potremmo impostare un listener sul `keydown` e controllare quale tasto venga premuto.
```

2021-03-19 18:43 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Da una parte, il valore di `event.key` è un carattere, e cambia a seconda del linguaggio. Se il visitatore gestisce più lingue nel suo sistema operativo e passa da uno all'altro, lo stesso tasto rest
```suggestion
Da una parte, il valore di `event.key` è un carattere, e cambia a seconda del linguaggio. Se il visitatore gestisce più lingue nel suo sistema operativo e passa da una all'altra, lo stesso tasto restituirebbe caratteri differenti. Quindi ha senso controllare `event.code`, che è sempre lo stesso.
```
(Ti riferivi al passaggio da una lingua all'altra, giusto? non del sistema operativo)

2021-03-19 18:46 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Per il tracciamento affidabile dei caratteri, che siano dipendenti dal layout, `event.key` potrebbe essere la soluzione migliore.
```suggestion
Per il tracciamento affidabile dei caratteri che sono dipendenti dal layout, `event.key` potrebbe essere la soluzione migliore.
```
In questo contesto, mi sembra, 'siano' non e' molto intuitivo. Opinione personale eh, sentiti libero di accettare o meno il suggerimento :)

2021-03-19 18:47 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Di contro, `event.code` ha il beneficio di essere sempre lo stesso, legato alla posizione fisica del tasto, anche se il visitatore dovesse modificare la lingua. E le scorciatoie ad essi relative funz
```suggestion
Di contro, `event.code` ha il beneficio di essere sempre lo stesso, legato alla posizione fisica del tasto, anche se il visitatore dovesse modificare la lingua. E le scorciatoie ad esso relative funzioneranno bene anche in caso di cambio lingua.
```
Qui ti riferisci al tasto, non a tasti, corretto?

2021-03-19 18:48 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Se un tasto viene premuto abbastanza a lungo, si instaura l'"auto-repeat": l'evento `keydown` viene scaturito ancora e ancora, e alla fine, quando viene rilasciato, otteniamo un evento `keyup`. Quind
```suggestion
Se un tasto viene premuto abbastanza a lungo, si instaura l'"auto-repeat": l'evento `keydown` scaturisce ancora e ancora e, alla fine, quando viene rilasciato, otteniamo un evento `keyup`. Quindi è abbastanza normale avere molti `keydown` ed un solo `keyup`.
```

2021-03-19 18:50 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +C'erano tante di quelle incompatibilità tra i vari browser, anche durante lo sviluppo delle specifiche da parte degli sviluppatori che cercavano di implementarle, che l'unica soluzione fu quella di d
```suggestion
C'erano tante di quelle incompatibilità tra i vari browser, anche durante lo sviluppo delle specifiche da parte degli sviluppatori che cercavano di implementarle, che l'unica soluzione fu quella di deprecarli tutti, e creare degli eventi nuovi e moderni (descritti sopra in questo capitolo). Il codice vecchio funziona ancora, dal momento che i browser continuano a supportarli, ma non c'è assolutamente nessuna ragione per continuare a farlo.
```

2021-03-19 18:51 UTC, Dorin-David commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +In passato, gli eventi da tastiera erano talvolta usati per tenere traccia degli input dell'utente nei campi dei form, cosa non molto affidabile perché l'input può avvenire in vari modi. Per gestire
```suggestion
In passato, gli eventi da tastiera erano talvolta usati per tenere traccia degli input dell'utente nei campi dei form, cosa non molto affidabile perché l'input può avvenire in vari modi. Per gestire qualunque tipo di input abbiamo `input` e `change` (affrontati più avanti nel capitolo <info:events-change-input>). Questi scaturiscono da qualunque tipo di input, inclusi il copia-incolla o il riconoscimento vocale.
```

2021-03-19 18:55 UTC, Dorin-David reviewed
Ottima traduzione Pier! Mi sono permesso di suggerire alcune piccole modifiche, fanne quello che vuoi.

2021-03-20 21:51 UTC, pierangelomiceli commented
/done

2021-03-21 10:11 UTC, pasor1 requested changes

2021-03-21 10:11 UTC, pasor1 commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +Le azioni di default possono essere tante e variegate, dal momento che sono tante le cose che possono essere iniziate tramite la tastiera.
```suggestion
Le azioni di default possono essere tante e variegate, dal momento che sono tante le cose che possono essere attivate tramite la tastiera.
```

2021-03-21 10:11 UTC, pasor1 commented on 2-ui/3-event-details/7-keyboard-events/article.md
> +...Tuttavia, siamo ancora in grado di inserire qualunque valore, usando il mouse, attraverso la funzionalità tasto destro + Incolla. Quindi il filtro non è al 100% affidabile. Volendo, possiamo lasci
```suggestion
...Tuttavia, siamo ancora in grado di inserire qualunque valore, usando il mouse, attraverso la funzionalità tasto destro + Incolla. Quindi il filtro non è al 100% affidabile. Volendo, possiamo lasciarlo così, dato che funzionerà la maggior parte delle volte. Un approccio alternativo, invece, potrebbe essere quello di tenere traccia dell'evento `input`, che scaturisce dopo ogni modifica al campo di testo. In questo modo possiamo sempre verificare il nuovo valore ed evidenziarlo/modificarlo se non ritenuto valido.
```

2021-03-23 19:39 UTC, longo-andrea commented
visto che è aperta da oltre una settimana, prendo io in carico le modifiche suggerite cosi poi è pronta per il merge

2021-03-23 19:41 UTC, longo-andrea commented
/done

2021-03-23 19:44 UTC, pasor1 approved these changes

2021-03-23 19:55 UTC, pierangelomiceli commented on 2-ui/3-event-details/7-keyboard-events/2-check-sync-keydown/solution.md
> +Andiamo a creare un set `pressed = new Set()` per mantenere i tasti attualmente premuti.
no. è un set..non andrebbe cambiato. usa l'oggetto Set

2021-03-23 21:02 UTC, pierangelomiceli commented
potete fare merge quando volete.

2021-03-24 10:27 UTC, merged