Attributes and properties
javascript-tutorial/it.javascript.info pull request #267
Opened 2021-03-17 21:35 UTC by Dorin-David

2021-03-20 17:55 UTC, longo-andrea requested changes
Ottima traduzione as always 👍 Principalmente sono tutte piccolezze, se hai dubbi su qualche correzione fammi sapere!

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Quando il browser carica una pagina, "legge" (in altre parole: "analizza") l'HTML e genera gli oggetti DOM. Per i nodi elemento, i più degli attributi HTML standart diventano automaticamente propriet
```suggestion
Quando il browser carica una pagina, "legge" (in altre parole: "analizza") l'HTML e genera gli oggetti DOM. Per i nodi elemento, i più degli attributi HTML standard diventano automaticamente proprietà degli oggetti DOM.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +I nodi del DOM sono regolari oggetti Javascript. Possiamo modificarli.
```suggestion
I nodi del DOM sono regolari oggetti JavaScript. Possiamo modificarli. 
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Quindi, le proprietà e i metodi del DOM si comportano come regolari oggetti Javascript:
```suggestion
Quindi, le proprietà e i metodi del DOM si comportano come regolari oggetti JavaScript:
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Qualche volta gli attributi non standart sono utilizzati per passare dati personalizzati dall'HTML a Javascript, o per "contrassegnare" elementi.
```suggestion
Qualche volta gli attributi non standard sono utilizzati per passare dati personalizzati dall'HTML a JavaScript, o per "contrassegnare" elementi.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Perciò, quando un elemento ha `id` o un altro attributo *standard*, la proprietà corrispondente viene creata. Ma questo non succede se l'attributo non è standart.
```suggestion
Perciò, quando un elemento ha `id` o un altro attributo *standard*, la proprietà corrispondente viene creata. Ma questo non succede se l'attributo non è standard. 
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Nota che un attributo standart di un elemento può essere sconosciuto ad un altro. Ad esempio, `"type"` è standard per `<input>` ([HTMLInputElement](https://html.spec.whatwg.org/#htmlinputelement)), m
```suggestion
Nota che un attributo standard di un elemento può essere sconosciuto ad un altro. Ad esempio, `"type"` è standard per `<input>` ([HTMLInputElement](https://html.spec.whatwg.org/#htmlinputelement)), ma non per `<body>` ([HTMLBodyElement](https://html.spec.whatwg.org/#htmlbodyelement)). Gli attributi standard sono descritti nella specifica della classe corrispondente dell'elemento.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Dunque, se un attributo non è standart, non vi sarà una corrispondente proprietà del DOM. C'è un modo per accedere a questi attributi?
```suggestion
Dunque, se un attributo non è standard, non vi sarà una corrispondente proprietà del DOM. C'è un modo per accedere a questi attributi?
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Segue un esempio di lettura di proprietà non standart:
```suggestion
Segue un esempio di lettura di proprietà non standard:
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Quando un attributo standart viene cambiato, la proprietà corrispondente viene automaticamente aggiornata, e (con qualche eccezione) vice versa.
```suggestion
Quando un attributo standard viene cambiato, la proprietà corrispondente viene automaticamente aggiornata, e (con qualche eccezione) vice versa.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Quando scriviamo HTML, utilizziamo molti attributi standart. E quelli non standart, personalizzati? Prima di tutto, vediamo se sono utili o meno, e per cosa.
```suggestion
Quando scriviamo HTML, utilizziamo molti attributi standard. E quelli non standard, personalizzati? Prima di tutto, vediamo se sono utili o meno, e per cosa.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Ma c'è un potenziale problema con gli attributi personalizzati. Che succederebbe se utilizzassimo un attributo non standart che in seguito verrebbe reso tale, con le sue caratteristiche? Il linguaggi
```suggestion
Ma c'è un potenziale problema con gli attributi personalizzati. Che succederebbe se utilizzassimo un attributo non standard che in seguito verrebbe reso tale, con le sue caratteristiche? Il linguaggio HTML è vivo, cresce, e altri attributi potrebbero apparire per soddisfare le necessità degli sviluppatori.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +- Abbiamo bisogno di un attributo non standart. Ma se comincia con `data-`, allora dovremmo utilizzare `dataset`.
```suggestion
- Abbiamo bisogno di un attributo non standard. Ma se comincia con `data-`, allora dovremmo utilizzare `dataset`.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Si possono altresì leggere tutti gli attributi utilizzando `elem.attributes`: una collection di oggetti che appartengono alla classe integrata [Attr](https://dom.spec.whatwg.org/#attr), con proprietà
```suggestion
Si possono altresì leggere tutti gli attributi utilizzando `elem.attributes`: una collection di oggetti che appartengono alla classe integrata [Attr](https://dom.spec.whatwg.org/#attr), con proprietà come `name` e `value`.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +## Le proprietà del DOM sono tipate
```suggestion
## Le proprietà del DOM sono tipizzate
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +|Tipo|Qualsiasi valore, le proprietà standard hanno i tipi descritti descritti nella specifica|Una stringa|
```suggestion
|Tipo|Qualsiasi valore, le proprietà standard hanno i tipi descritti nella specifica|Una stringa|
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Ma la mappatura attributo-proprietà non va di pari passo! In questo capitolo faremo attenzione a separare queste due nozioni, vedremo come lavorare con esse, quando sono la stessa cosa e quando invec
In questo caso mi sembra molto più chiara la traduzione letterale uno a uno... Se non ho interpretato male i significato, quello che vuole dire è che non tutti gli attributi hanno la corrispettiva proprietà, o comunque non con lo stesso nome

```suggestion
Ma la mappatura attributo-proprietà non è uno a uno! In questo capitolo faremo attenzione a separare queste due nozioni, vedremo come lavorare con esse, quando sono la stessa cosa e quando invece sono differenti. 
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Abbiamo già visto proprietà integrate del DOM. Ce ne sono molte. Ma tecnicamente nessuna di esse ci limita, e se non ce ne sono abbastanza, possiamo aggiungerne.
```suggestion
Abbiamo già visto proprietà integrate del DOM. Ce ne sono molte. Ma tecnicamente nessuna di esse ci limita, e se non ci sono sufficienti, possiamo aggiungerne. 
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +In HTML, i tag possono avere attributi. Quando il browser analizza l'HTML per creare oggetti DOM per i tag, riconosce gli attributi *standart* e crea proprietà del DOM a partire da essi.
```suggestion
In HTML, i tag possono avere attributi. Quando il browser analizza l'HTML per creare gli oggetti DOM corrispondenti, riconosce gli attributi *standard* e crea proprietà del DOM a partire da essi.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +1. `getAttribute('About')` -- la prima lettera è maiuscola, mentre in HTML è minuscola. Ma non importa: i nomi degli attributi sono insensibili alle maiuscole.
```suggestion
1. `getAttribute('About')` -- la prima lettera è maiuscola, mentre in HTML è minuscola. Non ha importanza: i nomi degli attributi sono insensibili alle maiuscole. 
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Ci sono altri esempi. L'attributo `style` è una stringa, ma la proprietà `style` non la è.
```suggestion
Ci sono altri esempi. L'attributo `style` è una stringa, ma la proprietà `style` non lo è.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +La maggior parte dell proprietà, comunque, sono stringhe.
```suggestion
La maggior parte delle proprietà, comunque, sono stringhe.
```

2021-03-20 17:55 UTC, longo-andrea commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Per evitare conflitti, abbiamo gli attributi [data-*](https://html.spec.whatwg.org/#embedding-custom-non-visible-data-with-the-data-*-attributes).
```suggestion
Per evitare conflitti, abbiamo a disposizione gli attributi [data-*](https://html.spec.whatwg.org/#embedding-custom-non-visible-data-with-the-data-*-attributes).
```

2021-03-20 18:23 UTC, Dorin-David commented
/done

2021-03-20 18:47 UTC, longo-andrea approved these changes

2021-03-21 10:44 UTC, pasor1 requested changes

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Abbiamo già visto proprietà integrate del DOM. Ce ne sono molte. Ma tecnicamente nessuna di esse ci limita, e se non ci sono sufficienti, possiamo aggiungerne.
```suggestion
Abbiamo già visto proprietà integrate del DOM. Ce ne sono molte. Ma tecnicamente nessuna di esse ci limita, e se non sono sufficienti, possiamo aggiungerne. 
```

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Quindi, le proprietà e i metodi del DOM si comportano come regolari oggetti JavaScript:
```suggestion
Quindi, le proprietà e i metodi del DOM si comportano come normali oggetti JavaScript:
```

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +    alert(body.type); // undefined: proprietà del DOM non creata perché non standard
```suggestion
    alert(body.type); // undefined: proprietà del DOM non creata, perché non standard
```

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +- Dobbiamo leggere un valore così "come scritto" in HTML. Il valore della corrispondente proprietà DOM potrebbe essere diverso; ad esempio la proprietà `href` è sempre una URL intera, e vorremmo il v
```suggestion
- Dobbiamo leggere un valore così "come scritto" in HTML. Il valore della corrispondente proprietà DOM potrebbe essere diverso; ad esempio la proprietà `href` è sempre un URL completo, e vorremmo il valore "originale".
```

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/article.md
> +Raramente, anche se il tipo di una proprietà è una stringa, questa potrebbe essere diversa dall'attributo. Ad esempio, la proprietà DOM `href` è sempre una URL *intera*, anche se l'attributo contiene
```suggestion
Raramente, anche se il tipo di una proprietà è una stringa, questa potrebbe essere diversa dall'attributo. Ad esempio, la proprietà DOM `href` è sempre un URL *completo*, anche se l'attributo contiene un URL relativo o semplicemente un `#hash`.
```

2021-03-21 10:44 UTC, pasor1 commented on 2-ui/1-document/06-dom-attributes-and-properties/2-yellow-links/solution.md
> +  if (!href.includes('://')) continue; // nessun protocolo
```suggestion
  if (!href.includes('://')) continue; // nessun protocollo
```

2021-03-21 12:23 UTC, Dorin-David commented
/done

2021-03-23 15:48 UTC, pasor1 approved these changes

2021-03-23 19:42 UTC, merged