Node properties: type, tag and contents
javascript-tutorial/it.javascript.info pull request #268
Opened 2021-03-20 09:22 UTC by marcellosurdi

2021-03-20 09:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=268) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=268) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/it.javascript.info?pullRequest=268) it.</sub>

2021-03-20 18:26 UTC, Dorin-David commented on 2-ui/1-document/05-basic-dom-node-properties/2-tree-info/solution.md
> +Possiamo leggere il testo dal primo nodo figlio di `li` che è un nodo di testo:
```suggestion
Possiamo leggere il testo dal primo nodo figlio di `li`, che è un nodo di testo:
```

2021-03-20 18:39 UTC, Dorin-David commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Come possiamo notare i nodi DOM sono oggetti JavaScript regolari ed usano classi basate sui prototipi per l'ereditarietà.
```suggestion
Come possiamo notare i nodi DOM sono regolari oggetti JavaScript ed usano classi basate sui prototipi per l'ereditarietà.
```
Piccolo suggerimento, mi sembra suoni meglio, ma anche la tua versione va benissimo :)

2021-03-20 18:40 UTC, Dorin-David commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +La maggior parte dei browser supportano due comandi nei loro strumenti per sviluppatori: `console.log` e `console.dir` che mostrano in console i loro argomenti. Per quanto riguarda gli oggetti JavaSc
```suggestion
La maggior parte dei browser supportano due comandi nei loro strumenti per sviluppatori: `console.log` e `console.dir` che mostrano in console i loro argomenti. Per quanto riguarda gli oggetti JavaScript, solitamente questi comandi funzionano allo stesso modo.
```

2021-03-20 18:43 UTC, longo-andrea requested changes
Complimenti, ottima traduzione! 👍 ti ho lasciato un paio di spunti per migliorare la scorrevolezza, sentiti libero di accettarli/rifiutarli/discuterne.

C'è solo una modifica obbligatoria che ti ho segnalato sotto, hai trovato un caso speciale che rompe la renderizzazione della pagina 😆

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +```smart header="I tag <script> non vengono eseguiti"
Complimenti hai beccato un caso particolare finora sconosciuto 😆 Non puoi mettere le parentesi angolari su uno smart header, se vuoi farlo, devi racchiuderli dentro i backtick

```suggestion
```smart header="I tag `<script>` non vengono eseguiti"
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Nella linea `(*)` sostituiamo `div` con `<p>A new element</p>`. Nel documento (il DOM) possiamo osservare che il nuovo contenuto ha preso il posto di `<div>`. Tuttavia, come possiamo notare nella lin
```suggestion
Nella linea `(*)` sostituiamo `div` con `<p>A new element</p>`. Nel documento (il DOM) possiamo osservare che il nuovo contenuto ha preso il posto di `<div>`. Tuttavia, come possiamo notare nella linea `(**)`, il precedente valore della variabile `div` non è cambiato!
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +: Per gli elementi indica il nome del tag (in lettere maiuscole a meno che il browser non sia in modalità XML). Per tutti gli altri nodi `nodeName` contiene una stringa destrittiva. La proprietà è in
```suggestion
: Per gli elementi indica il nome del tag (in lettere maiuscole a meno che il browser non sia in modalità XML). Per tutti gli altri nodi `nodeName` contiene una stringa descrittiva. La proprietà è in sola lettura.
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Nodi del DOM differenti possono avere proprietà differenti. Ad esempio, un nodo elemento corrispondente ad un tag `<a>` avrà proprietà tipiche dei link ed un nodo corrispondente al tag `<input>` avrà
```suggestion
Nodi del DOM differenti possono avere proprietà differenti. Ad esempio, un nodo elemento corrispondente ad un tag `<a>` avrà proprietà tipiche dei link ed un nodo corrispondente al tag `<input>` avrà proprietà tipiche dei campi di testo e così via. I nodi di testo sono differenti dai nodi elemento, tuttavia condividono alcune proprietà e metodi comuni a tutti, perché tutte le classi dei nodi del DOM costituiscono un'unica gerarchia.
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Questo è anche facile da osservare esaminando un elemento in un browser con `console.dir(elem)`. Nella console potremo vedere `HTMLElement.prototype`, `Element.prototype` e così via.
```suggestion
Questo è facilmente osservabile esaminando un elemento in un browser con `console.dir(elem)`. Nella console potremo vedere `HTMLElement.prototype`, `Element.prototype` e così via.
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Eccone un estratto, con commenti:
```suggestion
Eccone un estratto commentato:
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Possiamo anche modificarla e pertanto è uno dei più potenti strumenti per cambiare la pagina.
Suggerisco una modifica che si discosta leggermente dall'articolo inglese, che mi sembra poco chiaro in questo caso.. infatti quel "change the page", può essere fuorviante

```suggestion
Possiamo anche modificarla e pertanto è uno dei più potenti strumenti per modificare porzioni della pagina.
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +L'esempio mostra il contenuto di `document.body` e quindi lo rimpiazza completamente:
In questo caso il "then" è inteso come "poi".. infatti guardando l'esempio, fa un alert del body e poi lo rimpiazza

```suggestion
L'esempio mostra il contenuto di `document.body` e successivamente lo rimpiazza completamente:
```

2021-03-20 18:43 UTC, longo-andrea commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +## Sommario
"Summary" lo traduciamo come "Riepilogo", non ricordo se è a Glossario, nel caso ora lo aggiungo

```suggestion
## Riepilogo
```

2021-03-20 18:45 UTC, Dorin-David commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Nell'esempio `chatDiv` sopra, la linea `chatDiv.innerHTML+="How goes?"` ricrea il contenuto HTML e ricarica `smile.gif` (speriamo sia in cache). Se `chatDiv` ha molto altro testo e immagini, in quel
```suggestion
Nell'esempio `chatDiv` sopra, la linea `chatDiv.innerHTML+="How goes?"` ricrea il contenuto HTML e ricarica `smile.gif` (speriamo sia in cache). Se `chatDiv` ha molto altro testo e immagini il tempo di ricaricamento potrebbe diventare chiaramente percepibile.
```
"in quel caso" e' un po' superfluo e verboso, la frase originale e' piu' intuitiva, si capisce gia' bene qual e' il caso in questione...

2021-03-20 18:49 UTC, Dorin-David reviewed
Complimenti!

2021-03-21 07:11 UTC, marcellosurdi commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Come possiamo notare i nodi DOM sono oggetti JavaScript regolari ed usano classi basate sui prototipi per l'ereditarietà.
Sì, effettivamente vanno bene entrambe. Continuo ad avere una leggera preferenza per l'aggettivo dopo: mi sembra che dia più evidenza al termine "regolari"

2021-03-21 07:13 UTC, marcellosurdi commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +```smart header="I tag <script> non vengono eseguiti"
Volevo vedere se eravate attenti :rofl:

2021-03-21 07:25 UTC, marcellosurdi commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +Possiamo anche modificarla e pertanto è uno dei più potenti strumenti per cambiare la pagina.
A me sembrava chiaro, cambiare un singolo elemento equivale a cambiare la pagina (non necessariamente nella sua interezza), però capisco che possa essere frainteso. Se vogliamo discostarci un po' dall'inglese originario (cosa utile in molti casi), che ne pensi di "modificare l'HTML di un elemento della pagina"? In questo modo ricorriamo ad una perifrasi esplicativa senza allontanarci troppo dal "change the page" originale

2021-03-21 07:28 UTC, marcellosurdi commented on 2-ui/1-document/05-basic-dom-node-properties/article.md
> +L'esempio mostra il contenuto di `document.body` e quindi lo rimpiazza completamente:
D'accordissimo! Userei "poi lo rimpiazza" perché mi suonano male due avverbi di modo troppo vicini

2021-03-21 09:43 UTC, marcellosurdi commented
/done

2021-03-21 20:25 UTC, longo-andrea approved these changes

2021-03-21 20:25 UTC, merged