URL objects
javascript-tutorial/it.javascript.info pull request #271
Opened 2021-03-23 22:09 UTC by pierangelomiceli

2021-03-24 20:31 UTC, longo-andrea requested changes
Nice 👍 tradotta bene, non ho molto da suggerirti

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +Non esistono metodi networking che richiedono esattamente un oggetto `URL` object, in quanto le stringhe sono già abbastanza adatte allo scopo. Quindi, tecnicamente non siamo obbligati all'utilizzo d
```suggestion
Non esistono metodi di networking che richiedono esattamente un oggetto di tipo `URL`, in quanto le stringhe sono già abbastanza adatte allo scopo. Quindi, tecnicamente non siamo obbligati all'utilizzo di `URL`. Talvolta però può essere molto utile.
```

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +- **`url`** -- l'URL completo o solo il path (se il parametro base è stato impostato, il parametro seguente),
```suggestion
- **`url`** -- l'URL completo o solo il path (se il parametro base è stato impostato, vedi il parametro seguente),
```

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +L'oggetto `URL` ci permette di accedere alle sue componenti, in modo da avere un modo elegante di effettuare il parsing dell'url, ad esempio:
```suggestion
L'oggetto `URL` ci permette di accedere alle sue componenti, fornendo un modo elegante di effettuare il parsing dell'url, ad esempio:
```

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +- **`append(name, value)`** -- aggiunge il parametro per nome `name`,
Propongo di aggiungere i due punti, perché in italiano risulta poco scorrevole da leggere
```suggestion
- **`append(name, value)`** -- aggiunge il parametro per nome: `name`,
```

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +- **`get(name)`** -- recupera il parametro dal nome `name`,
```suggestion
- **`get(name)`** -- recupera il parametro dal nome: `name`,
```

2021-03-24 20:31 UTC, longo-andrea commented on 5-network/07-url/article.md
> +Quelli non permessi devono essere codificati, per esempio lettere non latine e spazi, e devono essere sostituiti con il relativo codice, con il prefisso `%`, come `%20` (lo spazio può essere codifica
```suggestion
I caratteri non permessi devono essere codificati, per esempio lettere non latine e spazi, e devono essere sostituiti con il relativo codice, con il prefisso `%`, come `%20` (lo spazio può essere codificato con `+`, per ragioni storiche, ma si tratta di una eccezione).
```

2021-03-25 07:40 UTC, pierangelomiceli commented
/done

2021-03-25 19:40 UTC, longo-andrea approved these changes

2021-03-26 15:18 UTC, pasor1 approved these changes
Solo qualche piccola correzione :+1:

2021-03-26 15:18 UTC, pasor1 commented on 5-network/07-url/article.md
> +- **`url`** -- l'URL completo o solo il path (se il parametro base è stato impostato, vedi il parametro seguente),
```suggestion
- **`url`** -- l'URL completo o solo il path (se il parametro `base` è stato impostato, vedi il parametro seguente),
```
ho messo `base` in codice perché altrimenti leggere "parametro base" è un po' fuorviante...

2021-03-26 15:18 UTC, pasor1 commented on 5-network/07-url/article.md
> +- **`base`** -- un base URL opzionale: se è impostato e l'argomento `url` contiene solamente il path, l'URL viene generato in relazione a `base`.
```suggestion
- **`base`** -- un *base URL* opzionale: se è impostato e l'argomento `url` contiene solamente il path, l'URL viene generato in relazione a `base`.
```

2021-03-26 15:18 UTC, pasor1 commented on 5-network/07-url/article.md
> +Le classi [URL](https://url.spec.whatwg.org/#url-class) e [URLSearchParams](https://url.spec.whatwg.org/#interface-urlsearchparams) sono entrambi basati sulle ultime specifiche URI: [RFC3986](https:/
```suggestion
Le classi [URL](https://url.spec.whatwg.org/#url-class) e [URLSearchParams](https://url.spec.whatwg.org/#interface-urlsearchparams) sono entrambe basate sulle ultime specifiche URI: [RFC3986](https://tools.ietf.org/html/rfc3986), mentre le funzioni `encode*` sono basate sulla vecchia versione [RFC2396](https://www.ietf.org/rfc/rfc2396.txt).
```

2021-03-26 23:04 UTC, pierangelomiceli commented
/done

2021-03-27 08:30 UTC, merged