Update 2-ui\1-document\08-styles-and-classes
javascript-tutorial/it.javascript.info pull request #272
Opened 2021-03-23 22:24 UTC by marcellosurdi

2021-03-24 11:21 UTC, pasor1 requested changes
Qualche piccola correzione e suggerimento. In generale, ottimo lavoro :+1:

2021-03-24 11:21 UTC, pasor1 commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Attualmente, quindi, restituisce il valore resolved della proprietà, di solito espressa in `px` per le proprietà geometriche.
```suggestion
Attualmente, quindi, `getComputedStyle` restituisce il valore resolved della proprietà, di solito espressa in `px` per le proprietà geometriche.
```

2021-03-24 11:21 UTC, pasor1 commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Per esempio, se ci sono le proprietà `paddingLeft/paddingTop`, cosa dovremmo ottenere con `getComputedStyle(elem).padding`? Niente, o forse un valore "generato" a partire dai valori di padding noti?
```suggestion
Per esempio, se ci sono le proprietà `paddingLeft/paddingTop`, cosa otterremmo con `getComputedStyle(elem).padding`? Niente, o forse un valore "generato" a partire dai valori di padding noti? Non esiste una regola standard in questo caso.
```

2021-03-24 11:21 UTC, pasor1 commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Tuttavia `getComputedStyle non dà accesso a quel colore, poiché diversamente una pagina arbitraria potrebbe scoprire se l'utente ha visitato un link creandolo sulla pagina e verificandone gli stili.
```suggestion
Tuttavia `getComputedStyle non dà accesso a quel colore, poiché diversamente, una pagina arbitraria potrebbe scoprire se l'utente ha visitato un link creandolo e verificandone gli stili.
```

2021-03-24 11:21 UTC, pasor1 commented on 2-ui/1-document/08-styles-and-classes/article.md
> +- `classList` -- il valore oggetto con i metodi `add/remove/toggle/contains`, ottimo per gestire le classi individualmente.
```suggestion
- `classList` -- l'oggetto con i metodi `add/remove/toggle/contains`, ottimo per gestire le classi individualmente.
```

2021-03-24 12:24 UTC, marcellosurdi commented
/done

2021-03-24 20:05 UTC, longo-andrea requested changes
Great 👍 mi spiace darti cosi pochi suggerimenti, ma è tradotto veramente bene

2021-03-24 20:05 UTC, longo-andrea commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Per gestire le classi ci sono due proprietà DOM:
```suggestion
Per gestire le classi abbiamo a disposizione due proprietà DOM:
```

2021-03-25 07:34 UTC, marcellosurdi commented on 2-ui/1-document/08-styles-and-classes/article.md
> +Per gli altri casi, come rendere rosso un testo o aggiungere un'icona di sfondo, definiamo degli stili CSS e poi applichiamo la classe con JavaScript. È più flessibile e più facile da gestire.
Avevo pensato la stessa cosa. Comunque anche se non fosse un errore e l'autore avesse inteso proprio icona, un'icona è, di fatto, un'immagine. Pienamente d'accordo!

2021-03-25 07:42 UTC, marcellosurdi commented
/done

2021-03-25 19:39 UTC, longo-andrea approved these changes

2021-03-28 12:42 UTC, merged