Resumable file upload
javascript-tutorial/it.javascript.info pull request #275
Opened 2021-03-27 00:16 UTC by pierangelomiceli

2021-03-28 11:03 UTC, longo-andrea requested changes

2021-03-28 11:35 UTC, pierangelomiceli commented on 5-network/09-resume-upload/article.md
> +## Evento di progresso non-così-utile
Credo che l'autore volesse indicare proprio questa forma.
Altrimenti avrebbe scritto.
The progress event is not so useful.
Lo manterrei

2021-03-28 11:35 UTC, pierangelomiceli commented
/done

2021-03-28 12:41 UTC, longo-andrea approved these changes

2021-03-31 18:26 UTC, Dorin-David commented on 5-network/09-resume-upload/article.md
> +Per ripristinare un upload, dobbiamo conoscere la quantità di dato trasferito prima che la connessione si interrompesse.
```suggestion
Per ripristinare un upload, dobbiamo conoscere la quantità di dati trasferiti prima che la connessione si interrompesse.
```

2021-03-31 18:28 UTC, Dorin-David commented on 5-network/09-resume-upload/upload-resume.view/server.js
> +  // se startByte e' 0 o non e' impostato, crea un nuovo file, altrimenti controlla la dimensione del file e lo accoda a quello esistente
```suggestion
  // se startByte è 0 o non è impostato, crea un nuovo file, altrimenti controlla la dimensione del file e lo accoda a quello esistente
```

2021-03-31 18:29 UTC, Dorin-David commented on 5-network/09-resume-upload/upload-resume.view/uploader.js
> +    // potremmo usare l'identificatore di sessione dell'utente (avendone uno) per essere ancora piu' sicuri della sua univocita'
```suggestion
    // potremmo usare l'identificatore di sessione dell'utente (avendone uno) per essere ancora più sicuri della sua univocità
```

2021-03-31 18:30 UTC, Dorin-David commented on 5-network/09-resume-upload/upload-resume.view/uploader.js
> +    //   true se l'upload e' andato a buon fine
```suggestion
    //   true se l'upload è andato a buon fine
```

2021-03-31 18:30 UTC, Dorin-David reviewed
Corretti piccoli typo

2021-03-31 21:36 UTC, pierangelomiceli commented
/done

2021-04-01 18:35 UTC, merged