Custom elements
javascript-tutorial/it.javascript.info pull request #277
Opened 2021-03-27 17:01 UTC by pierangelomiceli

2021-03-29 20:08 UTC, longo-andrea requested changes

2021-03-29 20:08 UTC, longo-andrea commented on 8-web-components/2-custom-elements/article.md
> +I nomi degli elementi personalizzati devono contenere un trattino `-`, ad esempio `my-element` e `super-button` sono nomi validi, al contrario di `myelement`.
```suggestion
I nomi degli elementi personalizzati devono contenere un trattino `-`, ad esempio `my-element` e `super-button` sono nomi validi, al contrario di `myelement` che non lo è.
```

2021-03-29 21:38 UTC, pierangelomiceli commented
/done

2021-03-29 21:39 UTC, pierangelomiceli commented
/done

2021-03-30 18:32 UTC, longo-andrea approved these changes

2021-04-03 06:15 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +1. **Elementi personalizzati autonomi** -- elementi "nuovi di zecca", che estendono la casse astratta `HTMLElement`.
```suggestion
1. **Elementi personalizzati autonomi** -- elementi "nuovi di zecca", che estendono la classe astratta `HTMLElement`.
```

2021-04-03 06:16 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +Prima di tutto, affrontiamo gli elementi autonomi, dopodiché ci spostiamo su quelli built-in personalizzati.
```suggestion
Prima di tutto, affrontiamo gli elementi autonomi, dopodiché ci sposteremo a quelli built-in personalizzati.
```

2021-04-03 06:17 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +// fa in modo che il browser sappia che <my-element> venga fornito dalla nostra classe
```suggestion
// fa in modo che il browser sappia che <my-element> viene fornito dalla nostra classe
```

2021-04-03 06:19 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +Il motivo è semplice: quando viene chiamato `constructor`, è ancora troppo presto. L'elemento è stato creato, ma in questa fase, il browser non ha ancora processato/assegnato gli i vari attributi: in
```suggestion
Il motivo è semplice: quando viene chiamato `constructor`, è ancora troppo presto. L'elemento è stato creato, ma in questa fase, il browser non ha ancora processato/assegnato i vari attributi: in questo frangente, una chiamata a `getAttribute` restituirebbe `null`. Di conseguenza, non possiamo renderizzare proprio nulla in quel punto.
```

2021-04-03 06:20 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +2. Possiamo chiamarlo una sola volta quando l'elemento viene inserito in pagina.
```suggestion
2. Possiamo chiamarlo una sola volta quando l'elemento viene inserito nella pagina.
```

2021-04-03 06:21 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +Questo è proprio perché in questa fase non ci sono figli, ed il DOM è ancora incompleto. Il parser ha collegato l'elemento custom `<user-info>`, e sta procedendo verso i suoi figli, ma nient'altro.
```suggestion
Questo proprio perché in questa fase non ci sono figli, ed il DOM è ancora incompleto. Il parser ha collegato l'elemento custom `<user-info>`, e sta procedendo verso i suoi figli, ma nient'altro.
```

2021-04-03 06:22 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +Oppure, se davvero abbiamo necessità di avere a che fare con i figli, possiamo ritardarne impostare un `setTimeout` a latenza zero.
```suggestion
Oppure, se davvero abbiamo necessità di avere a che fare con i figli, possiamo ritardare l'accesso impostando un `setTimeout` a latenza zero.
```

2021-04-03 06:23 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +D'altra parte, la soluzione non è perfetta, perchè se anche i figli utilizzassero `setTimeout` per inizializzare sé stessi a loro volta, si metterebbero in coda: a quel punto prima verrebbe eseguito
```suggestion
D'altra parte, la soluzione non è perfetta, perché se anche i figli utilizzassero `setTimeout` per inizializzare sé stessi a loro volta, si metterebbero in coda: a quel punto prima verrebbe eseguito il `setTimeout` esterno, e poi quello interno.
```

2021-04-03 06:24 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +I nuovi elementi che creiamo, come `<time-formatted>`, non hanno una semantica associata. Sono del tutto sconosciuti per motori di ricerca, e dispositivi di accessibilità, che non possono quindi gest
```suggestion
I nuovi elementi che creiamo, come `<time-formatted>`, non hanno una semantica associata. Sono del tutto sconosciuti per i motori di ricerca e i dispositivi di accessibilità, che non possono quindi gestirli.
```

2021-04-03 06:25 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +2. Forniamo il terzo argomenti a `customElements.define`, che specifica il tag:
```suggestion
2. Forniamo il terzo argomento a `customElements.define`, che specifica il tag:
```

2021-04-03 06:26 UTC, Dorin-David commented on 8-web-components/2-custom-elements/article.md
> +Il nostro nuovo pulsante estende quello built-in. Ne mantiene gli stili e le caratteristiche standard come ad esempio, l'attributo `disabled`.
```suggestion
Il nostro nuovo pulsante estende quello built-in. Ne mantiene gli stili e le caratteristiche standard, come ad esempio l'attributo `disabled`.
```

2021-04-03 06:27 UTC, Dorin-David requested changes
Ottima traduzione! Ho corretto alcuni typo e lasciato dei piccoli suggerimenti, fanne quello che vuoi

2021-04-05 19:46 UTC, merged