The clickjacking attack
javascript-tutorial/it.javascript.info pull request #278
Opened 2021-03-27 19:08 UTC by longo-andrea

2021-03-27 19:08 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=278) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/javascript-tutorial/it.javascript.info?pullRequest=278) before we can accept your contribution.<br/><hr/>**longo-andrea** seems not to be a GitHub user. You need a GitHub account to be able to sign the CLA. If you have already a GitHub account, please [add the email address used for this commit to your account](https://help.github.com/articles/why-are-my-commits-linked-to-the-wrong-user/#commits-are-not-linked-to-any-user).<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/javascript-tutorial/it.javascript.info?pullRequest=278) it.</sub>

2021-04-03 06:48 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +Ma in questo caso avremo un problema. Tutto ciò che l'utente scriverà sarà invisibile, perché anche l'iframe lo è.
```suggestion
Ma in questo caso avremmo un problema. Tutto ciò che l'utente scriverà sarà invisibile, perché anche l'iframe lo è.
```

2021-04-03 06:48 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +Un utente solitamente smette di digitare quando notano che nessun carattere sta apparendo sullo schermo.
```suggestion
Un utente solitamente smette di digitare quando notanche nessun carattere sta apparendo sullo schermo.
```

2021-04-03 06:50 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +Deve essere inviato come HTTP-header: il browser lo ignorerà se provate ad inserirlo tarmite il tag `<meta>`. Quindi, `<meta http-equiv="X-Frame-Options"...>` non avrá alcun effetto.
```suggestion
Deve essere inviato come HTTP-header: il browser lo ignorerà se provate ad inserirlo tarmite il tag `<meta>`. Quindi, `<meta http-equiv="X-Frame-Options"...>` non avrà alcun effetto.
```

2021-04-03 06:50 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +: Consenti di mostrare una pagina dentro gli iframe, se appartengono alla stessa origine.
```suggestion
: Consenti di mostrare una pagina dentro gli iframe, se appartiene alla stessa origine.
```
Al singolare perche' qui ti riferisci a "pagina"

2021-04-03 06:52 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +: Consenti agli iframe di mostrare una pagina se il documento padre appartiene al `domain` fornito.
```suggestion
: Consenti agli iframe di mostrare una pagina se il documento genitore appartiene al `domain` fornito.
```

2021-04-03 06:52 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +In base al browser che state utilizzando, l'`iframe` definito sopra, potrebbe o essere vuoto oppure avvertirvi che il browser non permette alla pagina questo tipo di navigazione.
```suggestion
In base al browser che state utilizzando, l'`iframe` definito sopra potrebbe o essere vuoto oppure avvertirvi che il browser non permette alla pagina questo tipo di navigazione.
```

2021-04-03 06:54 UTC, Dorin-David commented on 3-frames-and-windows/06-clickjacking/article.md
> +L'attacco può essere piuttosto pericoloso, perché quando studiano la UI (interfaccia utente), solitamente, non prendiamo in considerazione il fatto che un hacker potrebbe effettuare click al posto di
```suggestion
L'attacco può essere piuttosto pericoloso, perché quando studiano la UI (interfaccia utente), solitamente non prendiamo in considerazione il fatto che un hacker potrebbe effettuare un click al posto di un utente. Quindi possiamo trovare vulnerabilità nei posti più inaspettati.
```

2021-04-03 06:55 UTC, Dorin-David requested changes
Ho corretto alcuni piccoli typo e ti ho lasciato dei suggerimenti, fanne quello che vuoi

2021-04-03 08:14 UTC, longo-andrea commented
/done

2021-04-05 15:03 UTC, pasor1 approved these changes

2021-04-05 15:03 UTC, pasor1 commented on 3-frames-and-windows/06-clickjacking/article.md
> +L'attacco può essere piuttosto pericoloso, perché quando studiano la UI (interfaccia utente), solitamente non prendiamo in considerazione il fatto che un hacker potrebbe effettuare un click al posto
```suggestion
L'attacco può essere piuttosto pericoloso, perché quando implementiamo la UI (interfaccia utente), solitamente non prendiamo in considerazione il fatto che un hacker potrebbe effettuare un click al posto di un utente. Quindi possiamo trovare vulnerabilità nei posti più inaspettati.
```

2021-04-05 19:47 UTC, merged