Element size and scrolling
javascript-tutorial/it.javascript.info pull request #279
Opened 2021-03-28 23:13 UTC by marcellosurdi

2021-03-29 20:35 UTC, longo-andrea requested changes
Ottima traduzione 👍 ti ho lasciato un paio di commenti su alcune inesattezze, sono presenti anche nella versione inglese, quindi risolviamole lato nostro, poi apriremo una issue al repo inglese

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
> +P.S. Certamente, il posizionamento al centro potrebbe essere ottenuto con i CSS, ma qui vi chiediamo di farlo proprio con JavaScript. Più avanti incotreremo altri casi e situzioni più complesse in cu
```suggestion
P.S. Certamente, il posizionamento al centro potrebbe essere ottenuto con i CSS, ma qui vi chiediamo di farlo proprio con JavaScript. Più avanti incontreremo altri casi e situazioni più complesse in cui JavaScript è l'unica alternativa. Ora ci stiamo solo "scaldando".
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Ci sono molte proprietà JavaScript che ci consentono di leggere informazioni circa la larghezza, l'altezza di un elemento e le altre proprietà geometriche.
so che non è una traduzione letterale, ma mi suona veramente strano avere le due opzioni (larghezza, altezza ) poi 'elemento', e dopo un'altra opzione

```suggestion
Ci sono molte proprietà JavaScript che ci consentono di leggere informazioni circa la larghezza, l'altezza e altre proprietà geometriche di un elemento.
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +L'immagine sopra rappresenta il caso più complesso in cui l'elemento possiede una barra di scorrimento. Alcuni browser (non tutti) ricavano lo spazio per la barra prendendolo dall'area del contenuto
```suggestion
L'immagine sopra rappresenta il caso più complesso, quello in cui l'elemento possiede una barra di scorrimento. Alcuni browser (non tutti) ricavano lo spazio per la barra prendendolo dall'area del contenuto (indicata sopra come "content width").
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Senza la barra di scorrimento, pertanto, l'area del contenuto sarebbe `300px`, ma se la barra di scorrimento è larga `16px` (la larghezza è variabile in base al dispositivo ed al browser) allora rima
```suggestion
Senza la barra di scorrimento, pertanto, l'area del contenuto sarebbe `300px`, ma se la barra di scorrimento è larga `16px` (la larghezza è variabile in base al dispositivo ed al browser) allora rimane soltanto `300 - 16 = 284px`, ed è questa la misura che dovremmo tenere in considerazione. Ecco perché gli esempi di questo capitolo presumono che ci sia una barra di scorrimento. Senza questa, alcuni calcoli sarebbero più semplici.
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +- `scrollHeight = 723` -- è l'intera altezza del contenuto includendo le parti fuori dall'area visibile di scorrimento.
```suggestion
- `scrollHeight = 723` -- è l'intera altezza del contenuto, include le parti fuori dall'area visibile di scorrimento.
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +In altre parole, con `scrollTop` si intende "quanto l'elemento è stato fatto scorrere verso l'alto".
Questo è sbagliato (anche in inglese), è esattamente il contrario. Ti lascio il mio suggerimento, se hai idee migliori vai pure 😄 

```suggestion
In altre parole, con `scrollTop` si intende "quanto il contenuto di un elemento viene fatto scorrere verticalmente".
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +La maggior parte delle proprietà geometriche trattate sono in sola lettura, ma `scrollLeft/scrollTop` possono essere modificate, e il browser farà scorrere l'elemento.
Anche qui, non è l'elemento a scrollare ma il contenuto... purtroppo anche in inglese non è stato scritto benissimo.

```suggestion
La maggior parte delle proprietà geometriche trattate sono in sola lettura, ma `scrollLeft/scrollTop` possono essere modificate, e il browser farà scorrere il contenuto.
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Nell'elemento sottostante ogni clic esegue il codice `elem.scrollTop += 10`. Ciò comporta che il contenuto dell'elemento scorre verso il basso di `10px`.
```suggestion
Nell'elemento sottostante ogni clic esegue il codice `elem.scrollTop += 10`. Ciò comporta lo scorrimento del contenuto verso il basso di `10px`.
```

2021-03-29 20:35 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +Tutte le proprietà sono in sola lettura tranne `scrollLeft/scrollTop` che, se modificate, fanno scorrere l'elemento nel browser.
```suggestion
Tutte le proprietà sono in sola lettura tranne `scrollLeft/scrollTop` che, se modificate, fanno scorrere il contenuto nel browser.
```

2021-03-30 10:26 UTC, marcellosurdi commented on 2-ui/1-document/09-size-and-scroll/article.md
> +In altre parole, con `scrollTop` si intende "quanto l'elemento è stato fatto scorrere verso l'alto".
In realtà credo che l'articolo sia corretto 😊 : l'elemento viene fatto scorrere verso l'alto facendo in modo che l'utente possa visualizzare la parte bassa del contenuto. Infatti `scrollTop` è la misura della parte alta di `element` fuori dall'area visibile di scorrimento. Se traduci con *verticalmente* non rendi il testo inglese che vuole spiegare perché `scrollTop` abbia questo nome. Gli altri suggerimenti dove usi la parola contenuto al posto di elemento vanno bene perché possono risultare più intuitive ma qui lascerei la traduzione inalterata, anche perché, nell'articolo, subito prima c'è un'immagine esplicativa che rende il concetto.

2021-03-30 10:33 UTC, marcellosurdi commented
/done

2021-03-30 18:37 UTC, longo-andrea commented on 2-ui/1-document/09-size-and-scroll/article.md
> +In altre parole, con `scrollTop` si intende "quanto l'elemento è stato fatto scorrere verso l'alto".
woo, ora ho capito 😄 però ho dovuto rileggerlo un paio di volte! Okay allora come traduzione ci può stare, però imho questa frase fa solo più confusione, probabilmente io la interpreto male 😄

2021-03-30 18:37 UTC, longo-andrea approved these changes

2021-04-02 06:11 UTC, Dorin-David commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/solution.md
> +...Ma se impostiamo tali valori per `ball.style.left/top`, allora si troverebbe al centro non la palla ma il suo bordo superiore sinistro
```suggestion
...Ma se impostiamo tali valori per `ball.style.left/top`, allora si troverebbe al centro non la palla ma il suo bordo superiore sinistro:
```

2021-04-02 06:12 UTC, Dorin-David commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
> +- L'elemento dovrebbe essere spostato con JavaScript, non con i CSS.
```suggestion
- L'elemento dovrebbe essere spostato con JavaScript, non con CSS.
```

2021-04-02 06:12 UTC, Dorin-David commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
> +P.S. Certamente, il posizionamento al centro potrebbe essere ottenuto con i CSS, ma qui vi chiediamo di farlo proprio con JavaScript. Più avanti incontreremo altri casi e situazioni più complesse in
```suggestion
P.S. Certamente, il posizionamento al centro potrebbe essere ottenuto con CSS, ma qui vi chiediamo di farlo proprio con JavaScript. Più avanti incontreremo altri casi e situazioni più complesse in cui JavaScript è l'unica alternativa. Ora ci stiamo solo "scaldando".
```

2021-04-02 06:13 UTC, Dorin-David commented on 2-ui/1-document/09-size-and-scroll/6-width-vs-clientwidth/solution.md
> +3. `clientWidth` è l'area del contenuto interna di un elemento più i padding, mentre la proprietà width dei CSS (con il valore predefinito di `box-sizing`) è l'area del contenuto interna *senza i pad
```suggestion
3. `clientWidth` è l'area del contenuto interna di un elemento più il padding, mentre la proprietà width dei CSS (con il valore predefinito di `box-sizing`) è l'area del contenuto interna *senza il padding*.
```

2021-04-03 13:08 UTC, marcellosurdi commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
> +P.S. Certamente, il posizionamento al centro potrebbe essere ottenuto con i CSS, ma qui vi chiediamo di farlo proprio con JavaScript. Più avanti incontreremo altri casi e situazioni più complesse in
Mmm credo che di averlo sempre trovato con l'articolo in italiano, io lo lascerei così

2021-04-03 13:12 UTC, marcellosurdi commented on 2-ui/1-document/09-size-and-scroll/4-put-ball-in-center/task.md
> +- L'elemento dovrebbe essere spostato con JavaScript, non con i CSS.
Mmm credo che di averlo sempre trovato con l'articolo in italiano, io lo lascerei così

2021-04-03 13:14 UTC, marcellosurdi commented
/done

2021-04-05 19:48 UTC, merged