Template element
javascript-tutorial/it.javascript.info pull request #307
Opened 2021-04-20 20:34 UTC by pierangelomiceli

2021-04-25 18:33 UTC, Dorin-David commented on 8-web-components/4-template-element/article.md
> +Per esempio, possiamo possiamo inserire una riga di una tabella `<tr>`:
```suggestion
Per esempio, possiamo inserire la riga di una tabella `<tr>`:
```

2021-04-25 18:34 UTC, Dorin-David commented on 8-web-components/4-template-element/article.md
> +Solitamente, se proviamo a inserire un `<tr>` per esempio dentro un `<div>`, il browser riconoscerà una struttura non valida, "correggendola", aggiungendovi una tabella attorno. Questo non è il compo
```suggestion
Solitamente, se proviamo a inserire un `<tr>`, per esempio, dentro un `<div>`, il browser riconoscerà una struttura non valida, "correggendola", aggiungendovi una tabella attorno. Questo non è il comportamento corretto, ma d'altra parte `<template>` mantiene le cose esattamente come le inseriamo.
```

2021-04-25 18:35 UTC, Dorin-David commented on 8-web-components/4-template-element/article.md
> +  // Clona il contenuto del template per riutilizzarlo piu' volte
```suggestion
  // Clona il contenuto del template per riutilizzarlo più volte
```

2021-04-25 18:36 UTC, Dorin-David commented on 8-web-components/4-template-element/article.md
> +- il contenuto di `<template>` essendo considerato "avulso dal documento", non modificherà, nè eseguirà alcunché al suo interno.
```suggestion
- il contenuto di `<template>` essendo considerato "avulso dal documento", non modificherà, né eseguirà alcunché al suo interno.
```

2021-04-25 18:36 UTC, Dorin-David approved these changes
Corretti alcuni typo

2021-04-25 21:23 UTC, pierangelomiceli commented on 8-web-components/4-template-element/article.md
> +  // Clona il contenuto del template per riutilizzarlo piu' volte
I caratteri accentati nei commenti li lascio con l'apice per non incorrere in errori di visualizzazione di questo tipo:
![Schermata 2021-04-25 alle 23 19 21](https://user-images.githubusercontent.com/26161607/116010080-36e26080-a61d-11eb-8c3b-27b89ed177d1.png)

2021-04-25 21:25 UTC, pierangelomiceli commented
/done

2021-04-26 18:47 UTC, longo-andrea requested changes

2021-04-26 18:47 UTC, longo-andrea commented on 8-web-components/4-template-element/article.md
> +Il contenuto prende vita (gli stili vengono applicati, gli script vengono eseguiti, etc) solo quando viene inseririto dentro il documento.
```suggestion
Il contenuto prende vita (gli stili vengono applicati, gli script vengono eseguiti, etc) solo quando viene inserito dentro il documento.
```

2021-04-26 18:47 UTC, longo-andrea commented on 8-web-components/4-template-element/article.md
> +Il tag `<template>` ha delle pecurialità uniche, in quanto:
```suggestion
Il tag `<template>` ha delle peculiarità uniche, in quanto:
```

2021-04-26 19:24 UTC, pierangelomiceli commented
/done

2021-04-27 08:18 UTC, longo-andrea approved these changes

2021-04-27 18:50 UTC, merged