Sets and ranges
javascript-tutorial/it.javascript.info pull request #308
Opened 2021-04-21 14:32 UTC by mrkrash

2021-04-22 09:24 UTC, marcellosurdi requested changes
Complessivamente va bene, qualche modica è necessaria. Complimenti 👍

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +...Ma se decidiamo di effettuarne l'escape "giusto per non sbagliare", il risultato non cambierebbe:
```suggestion
...Ma se decidete di effettuare l'escape "per ogni evenienza", il risultato non cambierebbe:
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +// Escape tutto
```suggestion
// Escape di ogni carattere
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +// (la ricerca è stata eseguita in modo errato, mezzo-carattere restituito)
```suggestion
// (la ricerca è stata eseguita in modo errato, viene restituito mezzo-carattere)
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +Il risultato non è corretto, perché di base la regular expressions "non sa nulla" riguardo le coppie surrogate.
```suggestion
Il risultato non è corretto, perché di base le espressioni regolari "non sanno nulla" riguardo le coppie surrogate.
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +Il motore delle regular expression pensa che `[𝒳𝒴]` -- non sono due, ma quattro caratteri:
```suggestion
Il motore delle espressioni regolari pensa che `[𝒳𝒴]` -- non sono due, ma quattro caratteri:
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +// cerca per i caratteri da 𝒳 a 𝒵
```suggestion
// cerca i caratteri da 𝒳 a 𝒵
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +La ragione è che senza il flag `pattern:u` le coppie surrogate sono percepite come due caratteri, quindi `[𝒳-𝒴]` è interpretato come `[<55349><56499>-<55349><56500>]` (ogni coppia di surrogato è sost
```suggestion
La ragione è che senza il flag `pattern:u` le coppie surrogate sono percepite come due caratteri, quindi `[𝒳-𝒴]` è interpretato come `[<55349><56499>-<55349><56500>]` (ogni coppia surrogata è sostituita con i suoi codici). Ora è facile osservare che l'intervallo `56499-55349` non è valido: il suo codice iniziale `56499` è maggiore di quello finale `55349`. Questa è la ragione formale dell'errore.
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/task.md
> +Corrisponde a qualcosa nella stringa `subject:Java`? E nella stringa `subject:JavaScript`?
```suggestion
Cosa corrisponde nella stringa `subject:Java`? E nella stringa `subject:JavaScript`?
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md
> +- Nello script `subject:Java` non corrisponde nulla, dato che per `pattern:[^script]` si intende "qualunque carattere eccetto quelli dati". Quindi la regexp cerca per `"Java"` seguito da uno di quest
```suggestion
- Nello script `subject:Java` non c'è corrispondenza, dato che per `pattern:[^script]` si intende "qualunque carattere eccetto quelli dati". Quindi la regexp cerca `"Java"` seguito da uno di tali caratteri, ma c'è la fine della stringa, non ci sono caratteri dopo di esso.
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/1-find-range-1/solution.md
> +- Sì, poiché la parte `pattern:[^script]` al carattere `"S"`, non è uno di `pattern:script`. Poiché la regexp fa distinzione tra maiuscole e minuscole (non c'è il flag `pattern:i`), tratta `"S"` come
```suggestion
- Sì, poiché `pattern:[^script]` trova il carattere `"S"` che non è uno di `pattern:script`. Considerato che la regexp fa distinzione tra maiuscole e minuscole (non c'è il flag `pattern:i`), tratta `"S"` come un carattere differente da `"s"`.
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
> +L'orario può essere nel formato `ore:minuti` o `ore-minuti`. Entrambi ore e minuti hanno 2 numeri:  `09:00` o `21-30`.
```suggestion
L'orario può essere nel formato `ore:minuti` o `ore-minuti`. Entrambi, ore e minuti, hanno 2 numeri:  `09:00` o `21-30`.
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/task.md
> +Scrivi una regexp per trovare l'orario:
Abbiamo deciso di usare la seconda persona plurale nella traduzione dei task

```suggestion
Scrivete una regexp per trovare l'orario:
```

2021-04-22 09:24 UTC, marcellosurdi commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/2-find-time-2-formats/solution.md
> +Perfavore notate che il trattino `pattern:'-'` ha un significato speciale tra le parentesi quadre, ma solo tra gli altri caratteri, non quando è all'inizio o alla fine, quindi non c'è bisogno dell'es
```suggestion
Fate attenzione al fatto che il trattino `pattern:'-'` ha un significato speciale tra le parentesi quadre, ma solo tra gli altri caratteri, non quando è all'inizio o alla fine, quindi non c'è bisogno dell'escape.
```

2021-04-22 10:00 UTC, mrkrash commented
/done

2021-04-23 19:12 UTC, longo-andrea requested changes
Ottimo, ho trovato solamente un typo, l'articolo è tradotto bene!

2021-04-23 19:12 UTC, longo-andrea commented on 9-regular-expressions/08-regexp-character-sets-and-ranges/article.md
> +- `Join_Control` (`Join_C`) - due codici specialis `200c` e `200d`, usati nelle legature, a.e. in Arabo.
```suggestion
- `Join_Control` (`Join_C`) - due codici speciali `200c` e `200d`, usati nelle legature, a.e. in Arabo.
```

2021-04-24 15:54 UTC, longo-andrea approved these changes

2021-04-24 15:54 UTC, merged