Update article.md
javascript-tutorial/it.javascript.info pull request #334
Opened 2021-08-13 22:02 UTC by guebre-aziz

There was some parts of the text untranslated.

2021-08-15 05:21 UTC, pasor1 requested changes

2021-08-15 05:21 UTC, pasor1 commented on 1-js/09-classes/01-class/article.md
> +    Ci sono altre differenze, gli scopriremo più avanti.
```suggestion
    Ci sono altre differenze, che scopriremo più avanti.
```

2021-08-15 05:21 UTC, pasor1 commented on 1-js/09-classes/01-class/article.md
> +Come dimostrato nel capitolo <info:bind> le funzioni in JavaScript hanno un `this` dinamico. Dipende dal contesto della chiamata.
```suggestion
Come dimostrato nel capitolo <info:bind>, le funzioni in JavaScript hanno un `this` dinamico che dipende dal contesto della chiamata.
```

2021-08-17 21:02 UTC, guebre-aziz reviewed
/done

2021-12-26 21:16 UTC, merged